### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by Aurora11111** [Sierkinhane/crnn_chinese_characters_rec#1]

**Comment by haneSier** [comment]
训练集图片里的文字内容最好具有语意信息，因为这样神经网络仿佛是学习某种语意信息的语法，所以这样收敛更快，

**Comment by Aurora11111** [comment]
非常感谢你的回复！！还有一些疑问：
１．我的训练很慢是不是因为我的字符是随机的，没有语义的原因？你是完全采用的下载数据集从头训练的吗
２．假如我的训练图片是(442,64)那么就应该将图片乘以４４２／６４这个比例对不对

**Comment by Sierkinhane** [comment]
收敛很慢可能的原因有：
1. 学习率设置太小，可以多设置几个学习率观察收敛的趋势来确定一个学习率。
2. 字符随机组合成训练图片多少会影响收敛和最后的准确率的提升

我是从头开始训练的，没有做迁移学习。
我不知道（442， 64）代表的是训练图片的宽和高吗？

**Comment by Sierkinhane** [comment]
训练图片和输入到神经网络的图片的高是一样的，假设生成的训练及图片的尺寸为（280， 32），然后将图片resize成（160， 32）输入到网络中训练。最后你用随机长度的图片（width， 32）测试时，就需要将它resize成（width * （160/280)， 32），对于不定高也是同样道理

**Comment by Aurora11111** [comment]
我的训练图片尺寸是w=442, h=64
我看你的训练ｗ设置的２５６啊，怎么resize成１６０
test_dataset = dataset.lmdbDataset(
        root=opt.valroot, transform=dataset.resizeNormalize((256, 32)))
你是这样设置不是吗？

**Comment by Aurora11111** [comment]
好的！谢谢你

**Comment by Aurora11111** [comment]
我的训练图片的 高度是64,这样是直接resize到32吗?还是说训练的时候直接用64,识别的时候要resize到64
