### ISSUE TITLE
请问为什么会出现准确率为0， 并且训练过程中只出现一个字的情况？（附图）

### ISSUE THREAD

**Issue by Roxbili** [Sierkinhane/crnn_chinese_characters_rec#102]
![Screenshot from 2019-05-15 19-15-13](https://user-images.githubusercontent.com/29780560/57774866-41680000-774e-11e9-9110-be35debfdfa2.png)

**Comment by Sierkinhane** [comment]
请问你使用的是什么数据集呢

**Comment by Roxbili** [comment]
是使用generator生成的数据集，类似这样的
![val_25](https://user-images.githubusercontent.com/29780560/57847309-ba2b9280-7808-11e9-97d3-83c626cd57f3.png)
![val_37](https://user-images.githubusercontent.com/29780560/57847334-c879ae80-7808-11e9-8249-f124fbd03b31.png)

**Comment by Sierkinhane** [comment]
我也有遇到这种情况。我写的generator的程序比较简单，最好是混合在360中文数据集使用，不建议单独使用。

**Comment by Roxbili** [comment]
哦哦哦好的谢谢！

**Comment by jx8791608** [comment]
我也遇到过这个问题，把params.py中的batchSize设置大一点就好了，batchSize = 30。@Roxbili

**Comment by Roxbili** [comment]
好哒～十分感谢～

**Comment by vlzzhou** [comment]
请问你的loss值有没有出现负值的情况啊？

**Comment by Roxbili** [comment]
没有呢。。感觉快降到0之下后就变成NAN了
