### ISSUE TITLE
不用指定GPU号吗？直接--cuda加速就能使用到GPU吗？

### ISSUE THREAD

**Issue by PALMJJ** [Sierkinhane/crnn_chinese_characters_rec#103]
我的服务器有多张GPU卡，训练时候直接指定了--cuda可以用到GPU资源吗，我看我每秒大约只能训练5步，一个epoch要360W多步，这个是不是有点慢啊，哪出错了吗？

**Comment by Sierkinhane** [comment]
你可以查看下显卡占用情况，watch-n 1 nvidia-smi. 服务器多卡的话可以指定下GPU id.

**Comment by PALMJJ** [comment]
请问是在crnn_main.py中加下面这个吗？
import os
os.environ["CUDA_DEVICES_ORDER"]="PCI_BUS_IS"
os.environ["CUDA_VISIBLE_DEVICES"]=1
指定GPU？
我试了一下，速度提升了一些，但感觉还是有点慢啊，还是怎么改呢？谢谢

**Comment by Sierkinhane** [comment]
你可以查看官方给的文档

**Comment by PALMJJ** [comment]
请问您是训练300个epochs吗，每个epoch一共360W步，一共花了多长时间呀

**Comment by vinceyzw** [comment]
你好 请问你单个GPU的显存多大？我只有一块8G显卡，运行的时候torch.cuda()一直卡住，怀疑是显存不够的问题。 @PALMJJ @Sierkinhane

**Comment by Tian14267** [comment]
8G的显卡，完全够了。我训练的时候batchsize=128，只占用4G内存。 @vinceyzw 
另外，我有两个问题。第一，指定GPU。我试了，指定不成功。其他的训练都可以正常指定，但是这个代码就是默认GPU=0。
第二，训练过程中，训练熟读越来越慢，之前每个batch速度很快，现在一个batch要耗时好久才行。请问这是什么情况。 @ @Sierkinhane

**Comment by 15850864092** [comment]
GPU利用率才1%，会不会是cpu的IO读取图像速度慢，导致GPU利用率低
