### ISSUE TITLE
lmdbDataset类的问题，'NoneType'

### ISSUE THREAD

**Issue by jx8791608** [Sierkinhane/crnn_chinese_characters_rec#104]
这个问题好像别的issues中有提到，我想再问下作者，在dataset.py中的第40行以及第44行：
line40:return self.nSamples + 1
line44:index += 1
1，为什么__len__(self)要在self.nSamples的基础上加1
2，index为什么要加1
我是将40行改成return self.nSamples，将44行（index += 1）注释，才没有报TypeError:a bytes-like object is required,not 'NoneType'的错误，否则会报错。
作者是否有空回答一下，谢谢。

**Comment by zhangchurong** [comment]
同问 我也遇到这个问题了 但是加1不管用

**Comment by ahappycutedog** [comment]
@jx8791608 @zhangchurong 后来你们怎么解决了这个问题吗 我试了大家说的那几个改动，都不起作用

**Comment by jx8791608** [comment]
我是将40行改成return self.nSamples，同时将44行（index += 1）注释掉，正常运行。

**Comment by zhangchurong** [comment]
> @jx8791608 @zhangchurong 后来你们怎么解决了这个问题吗 我试了大家说的那几个改动，都不起作用

我找到的问题是这样，比如我有10w张图片，索引是0到99999，但是如果索引100000和10w+1时就会报错。把这个解决后就好了。
