### ISSUE TITLE
loss值

### ISSUE THREAD

**Issue by cqray1990** [Sierkinhane/crnn_chinese_characters_rec#105]
你好，我想请教个问题，我用360万的数据和我自己标注的10万数据，训练，开始的loss值为啥是四点几，感觉和楼主开始相差很大啊，到后面一个epoch都没跑完，损失就到了0.0几，搞不清楚？？？我的batchsize是16

**Comment by liaomingg** [comment]
我的loss值也是这样，请问你这样训练后的结果怎么样，正常吗？

**Comment by zhangchurong** [comment]
我的loss也是 acc为0

**Comment by lyd953621450** [comment]
loss值刚开始0.11   一个epoch就到0.05 了，accu为0,这是啥情况嘛！
