### ISSUE TITLE
有关BN问题

### ISSUE THREAD

**Issue by loralyc** [Sierkinhane/crnn_chinese_characters_rec#107]
您好，我看这个网络和原论文的BN层的位置不一样，想请问下为什么要这样调整

**Comment by dc-chengchao** [comment]
> 您好，我看这个网络和原论文的BN层的位置不一样，想请问下为什么要这样调整

[论文作者自己的repo里BN层的位置也和文章里不同](https://github.com/bgshih/crnn/blob/master/model/crnn_demo/config.lua)
这个应该就是自己的一些网络设计与调整吧。
