### ISSUE TITLE
Training japanese dataset

### ISSUE THREAD

**Issue by tuandzung** [Sierkinhane/crnn_chinese_characters_rec#109]
Hi, I'm currently training on a japanese dataset of about 3 million generated images, 10 chars, 280x32 same as the 3.6 million chinese dataset, split 99:1 for training/testing. The best val accuracy I could get is only 88%, any advice ?

**Comment by Sierkinhane** [comment]
The code for generating synthetic data is simple，maybe you should add some augmentations to your data.

**Comment by ph0ngt3p** [comment]
The generator I used is [https://github.com/Sanster/text_renderer](url), which I think provided very similar results compare to the synthetic chinese dataset. I'll try to add more variations though, thanks.
