### ISSUE TITLE
360万数据集和训练问题

### ISSUE THREAD

**Issue by itomorrower08** [Sierkinhane/crnn_chinese_characters_rec#110]
请问下360万的数据集是自己制作生成的还是网上的开源数据集，另外如果要用自己的数据集(一万左右)是用您的数据集先跑，之后迁移过去呢，还是两种数据集混在一起直接训练呢？

**Comment by Sierkinhane** [comment]
我是先预训练，然后混合在一起训练。

**Comment by leigaoxiang** [comment]
你好，自己的数据有做什么处理？是直接放进去？

**Comment by leigaoxiang** [comment]
@Sierkinhane

**Comment by stillarrow** [comment]
360万数据集的出处好像来自这里
https://github.com/senlinuc/caffe_ocr

**Comment by Lanme** [comment]
请问下你们训练的时候参数怎么配置？

**Comment by Lanme** [comment]
请问下你们训练的时候参数怎么配置？300个epoch岂不是得训练几周了...

**Comment by jamesbondzhou** [comment]
请问一下，我数据集做好之后运行时会出现CUDA error: out of memory，我把batch_size调到1了还是会报这个是怎么回事呀
@Sierkinhane

**Comment by Lanme** [comment]
@jamesbondzhou 加载了多大的数据集，显卡内存多少？

**Comment by zwy4896** [comment]
@Sierkinhane 请问训练集混在一起训练是把所有图片混在一起，然后统一生成lmbd吗？

**Comment by Cocoalate** [comment]
> 我是先预训练，然后混合在一起训练。

请问是怎么混合在一起训练的呢，我看见crnn_main_v2.py里面读取数据图像是
dataset = baiduDataset("H:/DL-DATASET/360M/images", "E:/08-Github-resources/00-MY-GitHub-Entries/crnn_chinese_characters_rec-master/crnn_chinese_characters_rec-master/label/train.txt", params.alphabet, False, (params.imgW, params.imgH))
val_dataset = baiduDataset("H:/DL-DATASET/360M/images", "E:/08-Github-resources/00-MY-GitHub-Entries/crnn_chinese_characters_rec-master/crnn_chinese_characters_rec-master/label/test.txt", params.alphabet, False, (params.imgW, params.imgH))
看起来是只读取了360万数据集的图像呢
