### ISSUE TITLE
训练出的模型对单行文字检测的很好，但是对英文的比较差

### ISSUE THREAD

**Issue by jamesbondzhou** [Sierkinhane/CRNN_Chinese_Characters_Rec#115]
楼主好，我训练之后模型对单行文字检测效果不错，但是英文检测的结果还是汉字，但我看给的alphabets里有6736个字符是包含了英文字母的呀，咋回事呢，另外如果我想识别多行文字或者变形的文字应该怎么改进呀

**Comment by Tian14267** [comment]
请问你得训练过程持续了多久？我训练几个epoch之后就变的很慢了，每个batch要还一会才结束。 @jamesbondzhou

**Comment by dc-chengchao** [comment]
会不会是因为毕竟原训练集内的中文字符实际上还是占绝对多数的，另外，训练图片绝大多数也都是接近于白底黑字。如果你的测试图片环境与训练图片环境差异比较大的话，我觉得检测效果不一定会好。

**Comment by LJXLJXLJX** [comment]
数据集不均衡
