### ISSUE TITLE
关于训练速度的问题

### ISSUE THREAD

**Issue by Tian14267** [Sierkinhane/CRNN_Chinese_Characters_Rec#118]
你好作者，我按照你的代码进行了训练，用的是360W的数据。Batch_size = 128。我在刚开始训练的时候，训练速度很快，一个batch瞬间就过去了。但是训练了几轮epoch之后，速度越来越慢，一个batch要好一会才完成。请问这是什么情况？我的显卡是1080Ti。

**Comment by Tian14267** [comment]
另外，训练的Loss很低，同时精度也很低。这个正常吗？
![QQ截图20190712142031](https://user-images.githubusercontent.com/27938135/61112226-f3594980-a4bd-11e9-89f4-1b3f05131d61.png)
![QQ截图20190712142141](https://user-images.githubusercontent.com/27938135/61112236-f94f2a80-a4bd-11e9-9a2c-9b10d90f4e62.png)

**Comment by Tian14267** [comment]
@Sierkinhane

**Comment by Sierkinhane** [comment]
不好意思这么迟才回复，这个问题应该是warp-ctc与pytorch自带的ctcloss的计算方法不同导致的，我最近正在更新代码，周末会上传代码

**Comment by Sierkinhane** [comment]
@Tian14267 已经更新代码，不过由于时间关系我没有完成训练，只是观察了loss的变化，和之前warp-ctc的loss变化已经较为一致，dataloader也已经修改，具体操作看readme。

**Comment by Tian14267** [comment]
好的，多谢作者。回头我看一看哈 @Sierkinhane

**Comment by zhangdaxia1** [comment]
@Sierkinhane 感谢作者的分享！我最近再跑您的实验，加入了自己的一些数据（10W张图）后用gpu训练一个epoch需要一个白天，请问可能是什么原因导致训练这么慢呢？以前没用过pytorch，显卡是2080ti
