### ISSUE TITLE
关于generator.py生成的图片文字越界的问题

### ISSUE THREAD

**Issue by Tian14267** [Sierkinhane/crnn_chinese_characters_rec#119]
我用这个脚本生成了一些文本，但是发现生成的很多文字都越界了，如下图：
![0](https://user-images.githubusercontent.com/27938135/61207064-b643c000-a726-11e9-92ef-8d3d8db3a7cf.png)
![3](https://user-images.githubusercontent.com/27938135/61207067-ba6fdd80-a726-11e9-85a3-774cd46f4859.png)
![14](https://user-images.githubusercontent.com/27938135/61207072-bf349180-a726-11e9-90cb-f93334b3a8f9.png)
我已经调整了坐标点（x,y）但是还是有些图片会越界。请问这是什么情况啊？
字体大小（28，30），图片h=32
@Sierkinhane

**Comment by Sierkinhane** [comment]
有些字体贴合的位置不一样，你可以预留字体高的一半作为左上角

**Comment by Tian14267** [comment]
我也检查了，确实是字体的原因导致的。谢谢啦
