### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Crescentz** [Sierkinhane/CRNN_Chinese_Characters_Rec#120]
小弟安装这个repo的时候各种坑，哪位大哥有安装好的readme文档，方便分享下，本机GPU Ubuntu18.04
已知遇到问题：
1.Warp-ctc安装后不能导入，提示没包
2.python3 test.py时， pytorch1.1和0.4均不行。提示GPU不能跑 
3. python2 各种ascii 和 utf问题

**Comment by Tian14267** [comment]
其实没必要专门装readme，先跑一下，遇到什么问题解决什么问题。pytorch好像带了ctc。反正我没有专门安装ctc。我的torch是1.0.1

**Comment by Sierkinhane** [comment]
这几天会更新代码，使用pytorch的CTCloss

**Comment by Sierkinhane** [comment]
@Crescentz  已经更新代码，不过由于时间关系我没有完成训练，只是观察了loss的变化，和之前warp-ctc的loss变化已经较为一致，dataloader也已经修改，具体操作看readme。
