### ISSUE TITLE
Loss为nan

### ISSUE THREAD

**Issue by CharlesWu123** [Sierkinhane/CRNN_Chinese_Characters_Rec#123]
为什么我训练的时候 Loss 一直 为 nan呢？

**Comment by CharlesWu123** [comment]
<img src=https://img-blog.csdnimg.cn/20190725162930655.png>

**Comment by Hhllo** [comment]
降低学习率试试

**Comment by Sierkinhane** [comment]
我最近更新了代码，周日会上传。

**Comment by CharlesWu123** [comment]
好的，我试试

**Comment by ganliqiang** [comment]
> 我最近更新了代码，周日会上传。

期待你更新的代码，ｃｔｃ_loss 太难装了　一直出现问题．

**Comment by Sierkinhane** [comment]
@ganliqiang @CharlesWu123 已经更新代码，不过由于时间关系我没有完成训练，只是观察了loss的变化，和之前warp-ctc的loss变化已经较为一致，dataloader也已经修改，具体操作看readme。

**Comment by AemaH** [comment]
@ganliqiang 您好，请问您训练时候loss还是会变为nan吗？

**Comment by CharlesWu123** [comment]
我这边使用的是自己的数据训练的，使用这个pytorch 版本的时候，loss刚开始就为nan。但是我使用另一版tensorflow程序的时候loss不是Nan，但是刚开始很大，loss为200多。如果使用Synthetic Chinese String Dataset这个数据集的话，是没有问题的，因为我自己的数据集因为整体图片宽度比较大，所以我全部按照宽度1000训练的，可能有这部分影响吧。

**Comment by Sierkinhane** [comment]
#124 Loss为nan的解决办法
