### ISSUE TITLE
关于识别精度的问题

### ISSUE THREAD

**Issue by shuanggezhi** [Sierkinhane/CRNN_Chinese_Characters_Rec#125]
我识别了一张图片，发现只识别出来一两个字，图片如下
![er](https://user-images.githubusercontent.com/38790667/62004582-8b5f6000-b159-11e9-9e6b-2783cc48e301.png)
![捕获2](https://user-images.githubusercontent.com/38790667/62004643-41c34500-b15a-11e9-8725-915489d0dc25.PNG)

其实除了val_set里面的图片识别效果很好，其他的图片我试了几张好像都不怎么样，想问问有啥解决方法没有

**Comment by Sierkinhane** [comment]
你应该解决一下过拟合的问题

**Comment by shuanggezhi** [comment]
所以大概率应该是训练模型.pth文件引起的过拟合问题吧，解决的话是应该换一个训练模型吗?
