### ISSUE TITLE
finetune后进行测试效果不好，请指教

### ISSUE THREAD

**Issue by changwh** [Sierkinhane/crnn_chinese_characters_rec#126]
作者您好，我想基于另外一个项目中给出的权重文件进行finetune，自己生成了如下图片共150K张作为训练集，50K张作为验证集，字与字之间的间隔固定不变
![2019-07-29 19-39-58屏幕截图](https://user-images.githubusercontent.com/22048098/62045722-ae147600-b238-11e9-97d1-d7a7e54d0b0c.png)
训练的过程中LOSS能够下降到1以下，在验证集上的准确率也能达到90%以上，但是当我使用其他图片进行测试时，却出现了如下的结果
![2019-07-29 19-43-59屏幕截图](https://user-images.githubusercontent.com/22048098/62045923-4579c900-b239-11e9-8abc-46264f70ea0c.png)
![2019-07-29 19-44-13屏幕截图](https://user-images.githubusercontent.com/22048098/62045928-47438c80-b239-11e9-9e19-924beebbc333.png)
用于测试的图片如下
![2019-07-29 19-45-48屏幕截图](https://user-images.githubusercontent.com/22048098/62046069-98538080-b239-11e9-876c-f1cbcf95a947.png)
![2019-07-29 19-46-32屏幕截图](https://user-images.githubusercontent.com/22048098/62046077-9be70780-b239-11e9-8566-ef4a8faacad9.png)
测试的结果基本上都在字与字之间的间隙上出现了识别错误，请问这是怎么回事呢？需要怎样处理训练集才能提升识别的效果？

PS：使用的ctc是warp-ctc，finetune之前的权重在白底黑字情况下的识别效果不错，finetune是希望能够提升泛化性，提升黑底白字和彩色背景白色文字的识别准确度。

**Comment by Sierkinhane** [comment]
crnn网络的输入是深度为1的灰度图，所以你提供的彩色图应该没有用处；测试效果不好的话可能与测试[代码](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/test.py#L39)中的放缩的比率有关，这里给出我训练时候的图片宽高信息：训练图片尺寸为w,h=280,32，并缩小至w,h=160,32作为网络输入。

**Comment by changwh** [comment]
> 
> 
> crnn网络的输入是深度为1的灰度图，所以你提供的彩色图应该没有用处；测试效果不好的话可能与测试[代码](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/test.py#L39)中的放缩的比率有关，这里给出我训练时候的图片宽高信息：训练图片尺寸为w,h=280,32，并缩小至w,h=160,32作为网络输入。

彩色图是希望转换成灰度图之后能够引入噪声，我是不是应该先把彩色图转成灰度图再训练呢？
另外需要在生成图片的时候固定w，h，然后在输入网络时再缩小吗？现在是固定字号，根据各种字体的每个文字的宽度和高度生成图片后，按比例缩小至h为32：）

**Comment by Sierkinhane** [comment]
这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)

**Comment by changwh** [comment]
> 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)

果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）

**Comment by vlzzhou** [comment]
怎么进行迁移学习啊？博主的代码中给出了训练模型，但如何进行迁移学习麻烦不吝赐教

**Comment by changwh** [comment]
> 怎么进行迁移学习啊？博主的代码中给出了训练模型，但如何进行迁移学习麻烦不吝赐教

1.准备好自己的训练集和测试集，转换成lmdb格式（使用的是原来版本的代码，新版本好像不需要转换，暂时没有继续测试，之后有时间再看看）
2.读取预训练模型，根据需要冻结前几层，对后面几层网络进行训练（这里我没有冻结，直接进行训练，效果也不错）

**Comment by vlzzhou** [comment]
您好，这个读取预训练模型是指读取作者之前的那个.pth文件是吗？不是直接将自己的数据集送进crnn_main训练进行了吗？怎么操作啊？请大神指教一下，十分感谢

**Comment by changwh** [comment]
> 您好，这个读取预训练模型是指读取作者之前的那个.pth文件是吗？不是直接将自己的数据集送进crnn_main训练进行了吗？怎么操作啊？请大神指教一下，十分感谢

1.修改[crnn='你的预训练模型.pth'](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/params.py#L14)
crnn=''时将会重新训练一个权重，指定预训练模型后将读取其参数进行微调，这里可以根据需要冻结参数，冻结参数应该需要在crnn_main.py中修改代码，具体如何操作你应该问问repo owner
2.生成lmdb，需要修改[to_lmdb/tolmdb_py3.py#L18](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/to_lmdb/tolmdb_py3.py#L18) [to_lmdb/tolmdb_py3.py#L23](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/to_lmdb/tolmdb_py3.py#L23) [to_lmdb/tolmdb_py3.py#L28](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/to_lmdb/tolmdb_py3.py#L28)
运行python tolmdb_py3.py
3.运行python crnn_main.py --trainroot 你的lmdb格式的train set --valroot 你的lmdb格式的val set --cuda

**Comment by vlzzhou** [comment]
懂了，十分感谢，感激不尽。祝大佬越来越牛

**Comment by vlzzhou** [comment]
懂了，十分感谢，感激不尽。祝大佬越来越牛

**Comment by mrlihellohorld** [comment]
> > 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)
> 
> 果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）

请问您如何修改缩放比例的呢

**Comment by changwh** [comment]
> 
> 
> > > 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)
> > 
> > 
> > 果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）
> 
> 请问您如何修改缩放比例的呢

我是先将h设定为32px后，w按比例缩放的
```python
w = int(image.size[0] / (image.size[1] * 1.0 / 32))
```

**Comment by mrlihellohorld** [comment]
> > > > 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)
> > > 
> > > 
> > > 果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）
> > 
> > 
> > 请问您如何修改缩放比例的呢
> 
> 我是先将h设定为32px后，w按比例缩放的
> 
> ```python
> w = int(image.size[0] / (image.size[1] * 1.0 / 32))
> ```

谢谢您的回复！
可以再请问您一个问题吗，我现在正遇到的：
我在自己生成的数据集上微调另一个项目里的模型，迭代一两次之后准确率还可以，val识别也是正确的，如图：
![image](https://user-images.githubusercontent.com/31719207/80079291-ab09a480-8582-11ea-9c86-f987c3aad573.png)
但是我用微调后的模型去识别测试图像，输出是错误的（乱码的），如图：
![image](https://user-images.githubusercontent.com/31719207/80079674-2cf9cd80-8583-11ea-82d8-0a30707a684f.png)
图中netCRNN63.pth为预训练模型，crnn_best.pth为微调后的。
可以请您帮忙分析一下吗，谢谢！！

**Comment by changwh** [comment]
> 
> 
> > > > > 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)
> > > > 
> > > > 
> > > > 果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）
> > > 
> > > 
> > > 请问您如何修改缩放比例的呢
> > 
> > 
> > 我是先将h设定为32px后，w按比例缩放的
> > ```python
> > w = int(image.size[0] / (image.size[1] * 1.0 / 32))
> > ```
> 
> 谢谢您的回复！
> 可以再请问您一个问题吗，我现在正遇到的：
> 我在自己生成的数据集上微调另一个项目里的模型，迭代一两次之后准确率还可以，val识别也是正确的，如图：
> ![image](https://user-images.githubusercontent.com/31719207/80079291-ab09a480-8582-11ea-9c86-f987c3aad573.png)
> 但是我用微调后的模型去识别测试图像，输出是错误的（乱码的），如图：
> ![image](https://user-images.githubusercontent.com/31719207/80079674-2cf9cd80-8583-11ea-82d8-0a30707a684f.png)
> 图中netCRNN63.pth为预训练模型，crnn_best.pth为微调后的。
> 可以请您帮忙分析一下吗，谢谢！！

能把训练集和测试图片贴出来看看吗？

**Comment by changwh** [comment]
> 
> 
> > > > > 这个仓库的代码会将彩色图在输入时转化为[灰度图](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L57)；图片的宽一定要为32，所以图片的宽高按w/32比例放缩，[新的代码会将图片宽高放缩](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/4c2c24bf96d92fca54b4af7cc35ce8a8801ad91d/dataset_v2.py#L65)
> > > > 
> > > > 
> > > > 果然是缩放的问题，修改了一下训练时图片的缩放比例，测试的结果提升了不少，感谢：）
> > > 
> > > 
> > > 请问您如何修改缩放比例的呢
> > 
> > 
> > 我是先将h设定为32px后，w按比例缩放的
> > ```python
> > w = int(image.size[0] / (image.size[1] * 1.0 / 32))
> > ```
> 
> 谢谢您的回复！
> 可以再请问您一个问题吗，我现在正遇到的：
> 我在自己生成的数据集上微调另一个项目里的模型，迭代一两次之后准确率还可以，val识别也是正确的，如图：
> ![image](https://user-images.githubusercontent.com/31719207/80079291-ab09a480-8582-11ea-9c86-f987c3aad573.png)
> 但是我用微调后的模型去识别测试图像，输出是错误的（乱码的），如图：
> ![image](https://user-images.githubusercontent.com/31719207/80079674-2cf9cd80-8583-11ea-82d8-0a30707a684f.png)
> 图中netCRNN63.pth为预训练模型，crnn_best.pth为微调后的。
> 可以请您帮忙分析一下吗，谢谢！！

还有一点需要确认的是，训练代码和测试代码里的图像缩放方法需要统一，举个例子，训练代码中缩放方法为固定大小，但在测试代码中为等比例，这种情况下一旦固定大小缩放改变了文字的字形，在测试中就很容易得到错误的结果。

**Comment by mrlihellohorld** [comment]
训练代码和测试代码都没有改动，只是更改了对应的路径。
训练图像使用https://github.com/Belval/TextRecognitionDataGenerator生成的，生成时大小就为32*280；训练集200W，测试集15W。生成的时候也是考虑了多个背景和字体、字体颜色等，样本大致为：
![image](https://user-images.githubusercontent.com/31719207/80091834-5c650600-8594-11ea-8246-5e9766c85183.png)
测试图像满足同分布。

**Comment by changwh** [comment]
> 
> 
> 训练代码和测试代码都没有改动，只是更改了对应的路径。
> 训练图像使用[https://github.com/Belval/TextRecognitionDataGenerator生成的，生成时大小就为32*280；训练集200W，测试集15W。生成的时候也是考虑了多个背景和字体、字体颜色等，样本大致为：](https://github.com/Belval/TextRecognitionDataGenerator%E7%94%9F%E6%88%90%E7%9A%84%EF%BC%8C%E7%94%9F%E6%88%90%E6%97%B6%E5%A4%A7%E5%B0%8F%E5%B0%B1%E4%B8%BA32*280%EF%BC%9B%E8%AE%AD%E7%BB%83%E9%9B%86200W%EF%BC%8C%E6%B5%8B%E8%AF%95%E9%9B%8615W%E3%80%82%E7%94%9F%E6%88%90%E7%9A%84%E6%97%B6%E5%80%99%E4%B9%9F%E6%98%AF%E8%80%83%E8%99%91%E4%BA%86%E5%A4%9A%E4%B8%AA%E8%83%8C%E6%99%AF%E5%92%8C%E5%AD%97%E4%BD%93%E3%80%81%E5%AD%97%E4%BD%93%E9%A2%9C%E8%89%B2%E7%AD%89%EF%BC%8C%E6%A0%B7%E6%9C%AC%E5%A4%A7%E8%87%B4%E4%B8%BA%EF%BC%9A)
> ![image](https://user-images.githubusercontent.com/31719207/80091834-5c650600-8594-11ea-8246-5e9766c85183.png)
> 测试图像满足同分布。

测试图像满足同分布是指？
因为没有看到你的测试图像具体长什么样子，所以具体是什么原因我也暂时无法确定。
从你的测试结果来看，似乎后半部分（“有限公司”）的识别是正确的，说明训练什么的应该是没有问题的，只是前半部分可能由于背景或者字形等原因识别错误了，还是需要看一下测试的图片才能进一步分析。

**Comment by mrlihellohorld** [comment]
谢谢您百忙之中给予我指导！
我主要是想通过微调另一个项目的模型来识别船名。例如测试图像：
![image](https://user-images.githubusercontent.com/31719207/80165862-139e6300-860f-11ea-9e31-036b1879d209.png)
用预训练模型可以识别一部分的字符：
![image](https://user-images.githubusercontent.com/31719207/80165925-3892d600-860f-11ea-822b-0366dd202fb4.png)
但是用微调后的模型（val准确率93%左右）识别这张船名，输出是乱码的。
![image](https://user-images.githubusercontent.com/31719207/80165993-637d2a00-860f-11ea-912d-9cac49172eb0.png)
再比如测试图像：
![image](https://user-images.githubusercontent.com/31719207/80166091-accd7980-860f-11ea-8481-80e4423187be.png)
yu预训练模型和微调模型识别结果：
![image](https://user-images.githubusercontent.com/31719207/80166126-c242a380-860f-11ea-8f00-22fad9e79ad9.png)
![image](https://user-images.githubusercontent.com/31719207/80166134-c79fee00-860f-11ea-8b7d-95a0204c2098.png)
请问出现这种情况是为什么呢，我测试了验证集图像都能准确识别。然后测试了作者项目中的test2.png
![image](https://user-images.githubusercontent.com/31719207/80165315-d38ab080-860d-11ea-94bd-89c2ca0058e7.png)
我用微调后的模型用test.py来测试该图像的结果：能够识别一部分字体
![image](https://user-images.githubusercontent.com/31719207/80165267-b6ee7880-860d-11ea-87ac-99534c26f2ef.png)  
但是用test_v2.py来测试同样的图像得到结果会差很多：
![image](https://user-images.githubusercontent.com/31719207/80165440-059c1280-860e-11ea-9c02-20431c0ef2d1.png)

**Comment by changwh** [comment]
> 
> 
> 谢谢您百忙之中给予我指导！
> 我主要是想通过微调另一个项目的模型来识别船名。例如测试图像：
> ![image](https://user-images.githubusercontent.com/31719207/80165862-139e6300-860f-11ea-9e31-036b1879d209.png)
> 用预训练模型可以识别一部分的字符：
> ![image](https://user-images.githubusercontent.com/31719207/80165925-3892d600-860f-11ea-822b-0366dd202fb4.png)
> 但是用微调后的模型（val准确率93%左右）识别这张船名，输出是乱码的。
> ![image](https://user-images.githubusercontent.com/31719207/80165993-637d2a00-860f-11ea-912d-9cac49172eb0.png)
> 再比如测试图像：
> ![image](https://user-images.githubusercontent.com/31719207/80166091-accd7980-860f-11ea-8481-80e4423187be.png)
> yu预训练模型和微调模型识别结果：
> ![image](https://user-images.githubusercontent.com/31719207/80166126-c242a380-860f-11ea-8f00-22fad9e79ad9.png)
> ![image](https://user-images.githubusercontent.com/31719207/80166134-c79fee00-860f-11ea-8b7d-95a0204c2098.png)
> 请问出现这种情况是为什么呢，我测试了验证集图像都能准确识别。然后测试了作者项目中的test2.png
> ![image](https://user-images.githubusercontent.com/31719207/80165315-d38ab080-860d-11ea-94bd-89c2ca0058e7.png)
> 我用微调后的模型用test.py来测试该图像的结果：能够识别一部分字体
> ![image](https://user-images.githubusercontent.com/31719207/80165267-b6ee7880-860d-11ea-87ac-99534c26f2ef.png)
> 但是用test_v2.py来测试同样的图像得到结果会差很多：
> ![image](https://user-images.githubusercontent.com/31719207/80165440-059c1280-860e-11ea-9c02-20431c0ef2d1.png)

船名识别出现问题，我觉得应该是中文下方的拼音对识别产生了干扰，你可以看到训练集中的样本都是干净的，只有一行中文，但是这里下方却出现了一行拼音。
如果你做的东西是检测加识别的话，可能需要改进或换一种方法得到更加准确的文字框，即能将中文和拼音分别放在两个文字框中，之后再使用crnn识别应该能得到不错的效果。

对于下面的使用作者提供的测试图片进行测试，使用finetune后的模型得到的结果不理想。因为不知道你数据集的构造是否含有类似的白底黑字的样本，是否冻结了提取特征的卷积层参数，训练的epoch数量等信息，有可能还是因为训练集和测试图片不是同分布导致的。
test_v2.py的问题，应该还是缩放引起的，大致上就是训练时的缩放和测试时的缩放不一致。缩放这个问题有点复杂，跟你构造的训练集也有关系，像作者构造的训练集尺寸都是280\*32的，在train时缩放为160\*32，只在w上进行缩放，而且缩放的比例也比较大。test2.png的尺寸为331\*36，如果你没有修改，在test.py中，w是按照280缩放到160的比例对331进行缩放，h则是直接压缩至32；在test_v2.py中，实现的效果应该和test.py是相同的，也就是说两段代码最后得到的结果应该是一样的。
你试着用test.py加载netCRNN63.pth测试test2.png，再用test_v2.py加载crnn_best.pth测试test2.png验证一下。看看是不是因为加载的模型不同，所以结果不同，而两个test.py实际上没有区别。

理论上，测试样本在缩放后的字形上与训练集的相似程度越高，测试的效果会越好。

**Comment by mrlihellohorld** [comment]
> > 谢谢您百忙之中给予我指导！
> > 我主要是想通过微调另一个项目的模型来识别船名。例如测试图像：
> > ![image](https://user-images.githubusercontent.com/31719207/80165862-139e6300-860f-11ea-9e31-036b1879d209.png)
> > 用预训练模型可以识别一部分的字符：
> > ![image](https://user-images.githubusercontent.com/31719207/80165925-3892d600-860f-11ea-822b-0366dd202fb4.png)
> > 但是用微调后的模型（val准确率93%左右）识别这张船名，输出是乱码的。
> > ![image](https://user-images.githubusercontent.com/31719207/80165993-637d2a00-860f-11ea-912d-9cac49172eb0.png)
> > 再比如测试图像：
> > ![image](https://user-images.githubusercontent.com/31719207/80166091-accd7980-860f-11ea-8481-80e4423187be.png)
> > yu预训练模型和微调模型识别结果：
> > ![image](https://user-images.githubusercontent.com/31719207/80166126-c242a380-860f-11ea-8f00-22fad9e79ad9.png)
> > ![image](https://user-images.githubusercontent.com/31719207/80166134-c79fee00-860f-11ea-8b7d-95a0204c2098.png)
> > 请问出现这种情况是为什么呢，我测试了验证集图像都能准确识别。然后测试了作者项目中的test2.png
> > ![image](https://user-images.githubusercontent.com/31719207/80165315-d38ab080-860d-11ea-94bd-89c2ca0058e7.png)
> > 我用微调后的模型用test.py来测试该图像的结果：能够识别一部分字体
> > ![image](https://user-images.githubusercontent.com/31719207/80165267-b6ee7880-860d-11ea-87ac-99534c26f2ef.png)
> > 但是用test_v2.py来测试同样的图像得到结果会差很多：
> > ![image](https://user-images.githubusercontent.com/31719207/80165440-059c1280-860e-11ea-9c02-20431c0ef2d1.png)
> 
> 船名识别出现问题，我觉得应该是中文下方的拼音对识别产生了干扰，你可以看到训练集中的样本都是干净的，只有一行中文，但是这里下方却出现了一行拼音。
> 如果你做的东西是检测加识别的话，可能需要改进或换一种方法得到更加准确的文字框，即能将中文和拼音分别放在两个文字框中，之后再使用crnn识别应该能得到不错的效果。
> 
> 对于下面的使用作者提供的测试图片进行测试，使用finetune后的模型得到的结果不理想。因为不知道你数据集的构造是否含有类似的白底黑字的样本，是否冻结了提取特征的卷积层参数，训练的epoch数量等信息，有可能还是因为训练集和测试图片不是同分布导致的。
> test_v2.py的问题，应该还是缩放引起的，大致上就是训练时的缩放和测试时的缩放不一致。缩放这个问题有点复杂，跟你构造的训练集也有关系，像作者构造的训练集尺寸都是280*32的，在train时缩放为160*32，只在w上进行缩放，而且缩放的比例也比较大。test2.png的尺寸为331*36，如果你没有修改，在test.py中，w是按照280缩放到160的比例对331进行缩放，h则是直接压缩至32；在test_v2.py中，实现的效果应该和test.py是相同的，也就是说两段代码最后得到的结果应该是一样的。
> 你试着用test.py加载netCRNN63.pth测试test2.png，再用test_v2.py加载crnn_best.pth测试test2.png验证一下。看看是不是因为加载的模型不同，所以结果不同，而两个test.py实际上没有区别。
> 
> 理论上，测试样本在缩放后的字形上与训练集的相似程度越高，测试的效果会越好。


感谢大佬百忙之中如此悉心、仔细地对我所提问题的回复！！
结合您的分析和建议，我仔细检查自己的数据集和训练参数等等，发现问题还是出在数据集复杂程度不够，导致模型泛化能力不足。我在丰富数据集之后，准确率有逐渐提升。
但是现在遇到一个很苦恼的问题，就是在params.py文件中设置的模型保存地址为expr文件夹，之前训练的模型都在此文件夹下保存，没有更改相应的参数，最近几次训练突然此文件夹下没有新的模型被保存，整个项目目录下也没有新的pth文件生成，请问您知道这种情况是如何产生的吗？
再次感谢您的回复和建议！

**Comment by terrynx** [comment]
> 谢谢您百忙之中给予我指导！
> 我主要是想通过微调另一个项目的模型来识别船名。例如测试图像：
> ![image](https://user-images.githubusercontent.com/31719207/80165862-139e6300-860f-11ea-9e31-036b1879d209.png)
> 用预训练模型可以识别一部分的字符：
> ![image](https://user-images.githubusercontent.com/31719207/80165925-3892d600-860f-11ea-822b-0366dd202fb4.png)
> 但是用微调后的模型（val准确率93%左右）识别这张船名，输出是乱码的。
> ![image](https://user-images.githubusercontent.com/31719207/80165993-637d2a00-860f-11ea-912d-9cac49172eb0.png)
> 再比如测试图像：
> ![image](https://user-images.githubusercontent.com/31719207/80166091-accd7980-860f-11ea-8481-80e4423187be.png)
> yu预训练模型和微调模型识别结果：
> ![image](https://user-images.githubusercontent.com/31719207/80166126-c242a380-860f-11ea-8f00-22fad9e79ad9.png)
> ![image](https://user-images.githubusercontent.com/31719207/80166134-c79fee00-860f-11ea-8b7d-95a0204c2098.png)
> 请问出现这种情况是为什么呢，我测试了验证集图像都能准确识别。然后测试了作者项目中的test2.png
> ![image](https://user-images.githubusercontent.com/31719207/80165315-d38ab080-860d-11ea-94bd-89c2ca0058e7.png)
> 我用微调后的模型用test.py来测试该图像的结果：能够识别一部分字体
> ![image](https://user-images.githubusercontent.com/31719207/80165267-b6ee7880-860d-11ea-87ac-99534c26f2ef.png)
> 但是用test_v2.py来测试同样的图像得到结果会差很多：
> ![image](https://user-images.githubusercontent.com/31719207/80165440-059c1280-860e-11ea-9c02-20431c0ef2d1.png)

老哥，请问你训练成功了么，能否加个联系方式交流一下，我qq是1850061652

**Comment by sssimpleboy** [comment]
大佬。我做的是自然场景的文字识别。
目前的数据集有真实场景的 百度17W ，RECTS 10W, RCTW 2W 以及自己合成的一些图片 不到200W，
由于带着真实数据训练 loss会变成nan。 所以现在是只用生成的图片训练，8W验证集，180W训练集，一共是3600个类别（3500汉字+英文，数字，标点）。 
生成的图片 是彩色背景(一张图只有一个色)+彩色字。然后经过透视变换。然后将原来的CNN部分替换成了resnet，并把预处理的灰度图部分去掉改成了彩色图。（这个resnet部分是从aster拿过来的，aster由于转onnx遇到了问题，就没再继续了）。


目前训练集损失可达到0.3以下，而验证集损失却高达4以上，准确率只有0.2
请问该怎么训练，或者有什么建议呢？我知道可能过拟合了，但是L2正则化不知道怎么加，dropout还没试过，CTCloss好像是封装好的。

以下是一些合成数据样例：

![image](https://user-images.githubusercontent.com/100906198/186793770-ae77f28d-d3da-437c-88dc-3224c200a971.png)
![image](https://user-images.githubusercontent.com/100906198/186793814-eaf617f0-2cab-4c0a-8595-162179e15980.png)
![image](https://user-images.githubusercontent.com/100906198/186793848-592d1345-db20-4d53-8463-e4a86b394505.png)
![image](https://user-images.githubusercontent.com/100906198/186793868-fec1c66a-903f-44e4-9b66-8218b0299f64.png)
![image](https://user-images.githubusercontent.com/100906198/186793888-5f5fd130-d753-4016-a7af-4a9b6a1d6aa7.png)
