### ISSUE TITLE
crnn_main 和ｃｒｎｎ_main_v2 loss差距这么大 

### ISSUE THREAD

**Issue by ganliqiang** [Sierkinhane/crnn_chinese_characters_rec#127]
ｃｒｎｎ_main 的ｌｏｓｓ开始是ｌoss 开始是７０左右，ｖ２的loss zhijie 就是０．２，能降到０．００几，我都是用的ｔｏｒｃｈ的ｃｔｃ＿ｌｏｓｓ,　差距为什么这么大？

**Comment by Sierkinhane** [comment]
你确定你没有说反？我测试的时候是crnn_main_v2.py的loss为70左右，这是因为criterion = torch.nn.CTCLoss(reduction='sum')，选择的参数不一样，v2的loss计算方法与warp-ctcloss计算方法一致。

**Comment by ganliqiang** [comment]
感谢回复，确实说错了，参数改成一样，训练结果就一致了，我一直以为ｌｍｄｂ格式的问题呢
