### ISSUE TITLE
关于图像预处理的问题

### ISSUE THREAD

**Issue by AemaH** [Sierkinhane/crnn_chinese_characters_rec#128]
您好，在仔细的阅读了您关于图像的预处理过程后发现，您并没有将图像像素值转化为(0,1)，但在后面进行了一步`image3.sub_(0.5).div_(0.5)`的操作，直观上来看是归一化操作，但因为先前并没有放缩到(0,1)，其实也没起到归一化的目的，反倒是像素值变为了509这样的范围，可以请教一下，这样做的目的吗？

**Comment by Sierkinhane** [comment]
你好，这是我的疏忽，修改时没注意。现在重新做了归一化和标准化，增加了计算数据集的均值与标准差的程序。

**Comment by AemaH** [comment]
@Sierkinhane 好的😊
