### ISSUE TITLE
test.py中的crnn_Rec_done_1.pth缺失，无法重现出测试图片

### ISSUE THREAD

**Issue by dc-chengchao** [Sierkinhane/crnn_chinese_characters_rec#129]
你好，我今天刚刚clone了这个repo，在进行测试的时候发现test.py中的crnn_Rec_done_1.pth并没有包含在repo内，trained_model文件夹内依然是10个月前的mixed_second_finetune_acc97p7.pth。

请问这个模型是最初的训练结果么？因为我在使用该模型进行测试并不能重现出博文中的结果，如图所示：
![issue](https://user-images.githubusercontent.com/49435542/62443872-95531580-b78e-11e9-938d-50cba1d17034.PNG)
其中一张图片甚至无法识别到文字。

我的pytorch版本是1.1.0，请问是否是在运行test.py前还有一些准备工作？

**Comment by Sierkinhane** [comment]
链接：https://pan.baidu.com/s/13Jk1q94BUZYvSYgPJkDr9Q 
提取码：t99a 
这是用新代码训练了一个epoch保存的模型，仅供测试。

**Comment by dc-chengchao** [comment]
> 链接：https://pan.baidu.com/s/13Jk1q94BUZYvSYgPJkDr9Q
> 提取码：t99a
> 这是用新代码训练了一个epoch保存的模型，仅供测试。

非常感谢！确实重现出了测试图的结果。
接下来要研究下怎么在我自己的数据集上训练了。
