### ISSUE TITLE
训练需要多久？

### ISSUE THREAD

**Issue by beimingmaster** [Sierkinhane/crnn_chinese_characters_rec#13]
我用的是csdn文章中提供的训练集。
修改了 batch_size = 128, worker = 8。
我的系统是Ubuntu 16.04 LTS, CPU I7 8Core，16G内存，带1块显卡Nvidia 1070（8G显存）。
训练了8个小时还没有结束，现在的准确度是95%。
Test loss: 0.232426, accuray: 0.959453

是不是我修改的worker或者batch_size太大了？

**Comment by Sierkinhane** [comment]
训练时长挺正常的，如果loss一直在在某个范围内震荡可以调节学习率（可以配合batchsize）走出鞍点

**Comment by Sierkinhane** [comment]
训练时长挺正常的，如果loss一直在在某个范围内震荡，可以先保存模型，调节学习率（可以配合batchsize）走出鞍点，我也是调了好几次超参数。

**Comment by beimingmaster** [comment]
> 训练时长挺正常的，如果loss一直在在某个范围内震荡，可以先保存模型，调节学习率（可以配合batchsize）走出鞍点，我也是调了好几次超参数。


Test loss: 0.051830, accuray: 0.989844
[14/300][7205/25622] Loss: 0.047560

1：我已经训练到第14轮了，准确率到了98.98%，最高曾经到了99.10%。loss现在0.01-0.05之间变化，是否可以结束训练了？
2：我现在训练的是印刷体，接下来我想训练手写体，怎样利用已有的印刷体模型，增量训练手写体呢？
感谢！

**Comment by haneSier** [comment]
可以试试印刷体、手写字体和其他字体混合在一个数据集，这样训练出的模型泛化能力比较robust
