### ISSUE TITLE
validation时可以正常识别，运行test.py无输出

### ISSUE THREAD

**Issue by zwy4896** [Sierkinhane/CRNN_Chinese_Characters_Rec#132]
![image](https://user-images.githubusercontent.com/25102200/62940713-bf4bae00-be06-11e9-88b7-bfc59ddb28ca.png)
训练过程中做validation是可以输出识别结果的，但是运行test.py时，输出全部为空。
![image](https://user-images.githubusercontent.com/25102200/62940836-08036700-be07-11e9-8e0f-c71bd2f6b778.png)

**Comment by dc-chengchao** [comment]
validation的时候和test的时候是同一批图集么？另外昨天刚更新过test.py里的图像预处理代码，你的repo是最新版本么？
