### ISSUE TITLE
关于调整代码以适应其它高度图片的训练

### ISSUE THREAD

**Issue by dc-chengchao** [Sierkinhane/CRNN_Chinese_Characters_Rec#133]
目前代码的CNN部分，在图片输入后运算得到的结果为C \* (H/16 - 1) \* (W/4 + 1)。所以在目前的代码中有检测图片高度是否为16的倍数，以及对于32的高度，最终得到的feature map的高度就是1，通道数为512。

但是由于我的应用场景比较特殊，字体颜色与背景图片比较接近，在放缩到32像素高度时很多图片都无法辨识出文字内容了，所以我在考虑将图片按比例放缩到64或128的高度进行训练。此时（以64高度为例）对于CNN的结果得到的尺寸为512 \* 3 \* (W / 4 + 1)，只需要将C \* 3 的部分都拉伸到通道内即可传送给接下来的RNN。不过这样操作我有两个疑问：

1. 在这个例子里，LSTM的输入从512变成了512 * 3，那么其中的隐藏层参数也需要按照这个比例（3倍）放大么？

1. 由于是等比例放缩，高度翻倍后，宽度也翻倍了，由于CNN的结果是将宽度上每一个像素为单位输入给RNN，所以最终的ctc的那个编码长度也翻倍了，但是我的图片中的文字长度其实没有变化。尤其是我在进一步放大图片输入网络进行训练后，这个编码长度会继续翻倍。所以相对于这样简单的拉伸CNN的结果来适应训练图片高度的变化，是不是还要再继续考虑在CNN的部分中加入跟多的卷积层，池化层等方式，来缩短ctc的编码长度？

**Comment by dc-wangjn** [comment]
打破0回复惨案

**Comment by adolf69** [comment]
我也有相同的问题
