### ISSUE TITLE
output all zeros?

### ISSUE THREAD

**Issue by JisongXie** [Sierkinhane/CRNN_Chinese_Characters_Rec#135]
I pull docker image from pytorch hub. My torch version is 1.1.0.
![图片](https://user-images.githubusercontent.com/28192557/63261971-5ad19880-c2b7-11e9-8efd-0d3e977b9484.png)
My python version is 3.6.8
![图片](https://user-images.githubusercontent.com/28192557/63262123-bac83f00-c2b7-11e9-8629-71b06df9d165.png)

I download the pretrained model from Baidu Yunpan, and run the test.py with the images in test_images. However, it output none. Then I output the preds.data, it's all zeros. It's confusing.

> test1.png

![图片](https://user-images.githubusercontent.com/28192557/63261640-8d2ec600-c2b6-11e9-8c7c-ee31721835ae.png)

> test2.png

![图片](https://user-images.githubusercontent.com/28192557/63261687-a768a400-c2b6-11e9-928f-d731c5b7dc30.png)
 
Can anyone help me please?

**Comment by wi162yyxq** [comment]
You should use the mixed_second_finetune_acc97p7.pth in the original trained_models folder

**Comment by JisongXie** [comment]
@wi162yyxq Thanks! Yes, I have tried the mixed_second_finetune_acc97p7.pth, it works fine. So, the crnn_Rec_done_1.pth is discarded?

**Comment by mangoHoli** [comment]
> @wi162yyxq Thanks! Yes, I have tried the mixed_second_finetune_acc97p7.pth, it works fine. So, the crnn_Rec_done_1.pth is discarded?

Mine same problem.
