### ISSUE TITLE
RuntimeError:cuda error:unspecified launch failure ，大神，求解

### ISSUE THREAD

**Issue by liudatutu** [Sierkinhane/crnn_chinese_characters_rec#137]
在训练模型的时候，在
cost = criterion(preds, text, preds_size, length) / batch_size
这句报错，关键是刚开始训练还好好的，每次都是中途报错跳出，如训练了190步，或者900步，或者1000步时报错，没有训练过完整的epoch，
各位大神，求解。

**Comment by liudatutu** [comment]
torch/nn/functionl.py, line 1732,in ctc_loss 
return torch.ctc_loss(log_probs, targets, input_lengths, target_lengths, blank, _Reduction.get_enum(reduction))
RuntimeError:cuda error:unspecified launch failure

**Comment by jdwuyao** [comment]
我也有相同的问题，后来解决了么

**Comment by JYH9351** [comment]
> 我也有相同的问题，后来解决了么

我也有同样的问题，我用的是torch
我的配置【Win10(1903),Python 3.7.4, RTX 2060 (driver version 441.20),torch.version==1.2.0,】
