### ISSUE TITLE
GPU训练crnn无故失败原因

### ISSUE THREAD

**Issue by vinceyzw** [Sierkinhane/CRNN_Chinese_Characters_Rec#138]
1、环境：win10+gpu2070(8G)+CUDA9.2+Pytorch1.2（torch0.4也试过）
2、CTC采用torch自带  torch.nn.CTCLoss()
3、失败位置：trainBatch中的cost.backward()，且无任何信息反馈

请大神们帮忙看看！感谢！
 @Sierkinhane @LJXLJXLJX

**Comment by vinceyzw** [comment]
大家是否可以提供下自己的环境给我参考下！
一直怀疑是ctc的问题，但是windows好像用不起来百度的ctc

**Comment by wwzh2015** [comment]
> 1、环境：win10+gpu2070(8G)+CUDA9.2+Pytorch1.2（torch0.4也试过）
> 2、CTC采用torch自带 torch.nn.CTCLoss()
> 3、失败位置：trainBatch中的cost.backward()，且无任何信息反馈
> 
> 请大神们帮忙看看！感谢！
> @Sierkinhane @LJXLJXLJX

params.py

> 1、环境：win10+gpu2070(8G)+CUDA9.2+Pytorch1.2（torch0.4也试过）
> 2、CTC采用torch自带 torch.nn.CTCLoss()
> 3、失败位置：trainBatch中的cost.backward()，且无任何信息反馈
> 
> 请大神们帮忙看看！感谢！
> @Sierkinhane @LJXLJXLJX
是不是这样？
https://ae01.alicdn.com/kf/H6e0dd3f9e4614a39b81998216e14b3deo.png

**Comment by LJXLJXLJX** [comment]
@wwzh2015 你这问题不太具体，没法回答。可以参考下我的代码找找问题 https://github.com/LJXLJXLJX/text_recognition

**Comment by wwzh2015** [comment]
> @wwzh2015 你这问题不太具体，没法回答。可以参考下我的代码找找问题 https://github.com/LJXLJXLJX/text_recognition

我是训练到了指定的epoch就结束了，准确率0，我样本很少，只有22张，不定长字符

**Comment by wwzh2015** [comment]
> @wwzh2015 你这问题不太具体，没法回答。可以参考下我的代码找找问题 https://github.com/LJXLJXLJX/text_recognition

你那个写的太乱了，不知道txt里的具体格式，啥也没说，还是这个具体，起码win10能跑起来

**Comment by LJXLJXLJX** [comment]
@wwzh2015 txt和这个一样

**Comment by wwzh2015** [comment]
> @wwzh2015 txt和这个一样
你那里的resnet和mobilenet是不是替换cnn特征用的？

**Comment by wwzh2015** [comment]
> @wwzh2015 你这问题不太具体，没法回答。可以参考下我的代码找找问题 https://github.com/LJXLJXLJX/text_recognition

你好，可否加你好友求教？
