### ISSUE TITLE
when model.eval() is used, the test result is bad

### ISSUE THREAD

**Issue by ganliqiang** [Sierkinhane/crnn_chinese_characters_rec#140]
i want to convert the pth to onnx,then to caffe2, but the result is bad ,i try many method ,i occasinaly find that when i used model.eval() before predicting,the pytorch predict result is the same as i used in onnx, so i want to know why the result is sooo bad when using model.eval() in pytorch version  .thanks.

**Comment by ganliqiang** [comment]
some results is  like this :
[46/1000][46/364400]
密                   , gt: 资进入中国均是为利益          
ncorrect: 0
[47/1000][47/364400]
@迪                  , gt: 学成回来再申请这边的          
ncorrect: 0
[48/1000][48/364400]
M                   , gt: 炮的M8式装甲火炮系          
ncorrect: 0
[49/1000][49/364400]
加m                  , gt: 同样会增加糖尿病的发          
ncorrect: 0
[50/1000][50/364400]
指、                  , gt: 但它们对股指、人气的          
ncorrect: 0
[51/1000][51/364400]
续放B营                , gt: 电池能连续播放4小时          
ncorrect: 0
[52/1000][52/364400]
播操密                 , gt: 播渠道的一个内容载体          
ncorrect: 0
[53/1000][53/364400]
“”                  , gt: 多家深谙“人才最贵”          
ncorrect: 0
[54/1000][54/364400]
，斋放                 , gt: 一看，“北斋要被拆了          
ncorrect: 0
[55/1000][55/364400]
Ra的                 , gt: “Razr的光环已渐          
ncorrect: 0
[56/1000][56/364400]
区                   , gt: 都军区参谋长吕登明告

**Comment by zgqball** [comment]
same as me. But why? model.eval() , the test.py result is blank

**Comment by ganliqiang** [comment]
> same as me. But why? model.eval() , the test.py result is blank
reload the model,the probleme is solved. i also do not know the reason.

**Comment by terrynx** [comment]
> some results is like this :
> [46/1000][46/364400]
> 密 , gt: 资进入中国均是为利益
> ncorrect: 0
> [47/1000][47/364400]
> @迪 , gt: 学成回来再申请这边的
> ncorrect: 0
> [48/1000][48/364400]
> M , gt: 炮的M8式装甲火炮系
> ncorrect: 0
> [49/1000][49/364400]
> 加m , gt: 同样会增加糖尿病的发
> ncorrect: 0
> [50/1000][50/364400]
> 指、 , gt: 但它们对股指、人气的
> ncorrect: 0
> [51/1000][51/364400]
> 续放B营 , gt: 电池能连续播放4小时
> ncorrect: 0
> [52/1000][52/364400]
> 播操密 , gt: 播渠道的一个内容载体
> ncorrect: 0
> [53/1000][53/364400]
> “” , gt: 多家深谙“人才最贵”
> ncorrect: 0
> [54/1000][54/364400]
> ，斋放 , gt: 一看，“北斋要被拆了
> ncorrect: 0
> [55/1000][55/364400]
> Ra的 , gt: “Razr的光环已渐
> ncorrect: 0
> [56/1000][56/364400]
> 区 , gt: 都军区参谋长吕登明告

你好，请问你转onnx的时候，图片输入尺寸是什么，我是这样设置的：dummy_input1 = torch.randn(1, 1, 280, 32)   ，但是一直报错：RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
