### ISSUE TITLE
Get cv2 'NoneType' error when data_generator

### ISSUE THREAD

**Issue by mangoHoli** [Sierkinhane/crnn_chinese_characters_rec#141]
Epoch:[0/1] Batch:[1271/2500] Loss: 101.630814
Epoch:[0/1] Batch:[1272/2500] Loss: 92.453171
Epoch:[0/1] Batch:[1273/2500] Loss: 101.025040
./data_generator/data_set/ ﻿val_set/6721.png
Traceback (most recent call last):
  File "crnn_main_v2.py", line 187, in <module>
    main(crnn, train_loader, val_loader, criterion, optimizer)
  File "crnn_main_v2.py", line 119, in main
    train(crnn, train_loader, criterion, Iteration)
  File "crnn_main_v2.py", line 88, in train
    for i_batch, (image, index) in enumerate(train_loader):
  File "/home/mangoholi/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mangoholi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mangoholi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mangoholi/HOLIWORK/crnn_chinese_characters_rec/dataset_v2.py", line 69, in __getitem__
    h, w = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

----------------------------------------------------------------------------------------------
Above is the error I got.

I generate self-designed data using './data_generator' folder, and I split the data into train.txt and test.txt. I found out that the error I got occurs when I tried to read the first-line data from train.txt (I print out the un-readable data './data_generator/data_set/ ﻿val_set/6721.png' to find out this reason).

I have tested the error happens whenever I use 10K or 100K data, or generate random data.

Could you help with this? Pls.

**Comment by dc-chengchao** [comment]
Looks like the image is not loaded. Also I notice that there is a space in your path "data_set/ val_set". Are you sure about this?

**Comment by mangoHoli** [comment]
> Looks like the image is not loaded. Also I notice that there is a space in your path "data_set/ val_set". Are you sure about this?

Thanks for the checking. I solved it by read encoding from 'utf-8' to 'utf-8-sig'. Problems with the head of the file, its utf-8 dom encoded.
