### ISSUE TITLE
请问怎么用CPU进行测试呢

### ISSUE THREAD

**Issue by YangWenwu1992** [Sierkinhane/crnn_chinese_characters_rec#145]
在test.py进行测试时，要调用CUDA，没有安装GPU，请问CPU怎么测试

**Comment by dc-chengchao** [comment]
目前的代码是自动检测是否有cuda，有则调用，没有则使用cpu

**Comment by YangWenwu1992** [comment]
> 目前的代码是自动检测是否有cuda，有则调用，没有则使用cpu
那请问有没有训练到最好的模型，能提供一下吗？

**Comment by YangWenwu1992** [comment]
@dc-chengchao 
请问有没有训练好的模型，能否提供一下
