### ISSUE TITLE
关于在同一个样本中存在不同颜色或不同字体的字符

### ISSUE THREAD

**Issue by changwh** [Sierkinhane/crnn_chinese_characters_rec#148]
在对模型进行训练时，同一个训练样本中字符的颜色与字体都是相同的。

这种情况下，使用训练好的模型进行识别时，若同一个测试样本中存在不同颜色或不同字体的字符，识别的效果将会比较不理想。

有没有什么办法能够解决这样的问题？

如果在构造训练数据时，在同一个训练样本中使用不同的颜色与字体，是否能够提高在上述情况下的识别准确度？有人有兴趣探究一下吗？：）

**Comment by dc-chengchao** [comment]
在我的操作经历中，颜色有影响，但可能不大，因为不管是训练还是检测都是转灰度图进行的。

训练集中添加不同的颜色与字体的样本，对于测试是有显然的帮助的。这主要是因为模型的拓展能力的一个很重要的假设就是训练和测试的分布要类似。你不能指望训练的时候用的都是单宽度的字体，到测试的时候碰上双宽度的“口昌”，模型能识别出“唱”而不是“口”和“昌”这两个字。

**Comment by changwh** [comment]
> 
> 
> 在我的操作经历中，颜色有影响，但可能不大，因为不管是训练还是检测都是转灰度图进行的。
> 
> 训练集中添加不同的颜色与字体的样本，对于测试是有显然的帮助的。这主要是因为模型的拓展能力的一个很重要的假设就是训练和测试的分布要类似。你不能指望训练的时候用的都是单宽度的字体，到测试的时候碰上双宽度的“口昌”，模型能识别出“唱”而不是“口”和“昌”这两个字。

目前在我的训练集中已经添加了不同颜色和不同字体的样本，但是对于每个单个的样本，样本中的颜色和字体都是统一的：
![1568621081_0](https://user-images.githubusercontent.com/22048098/65216333-1bc77a80-dae3-11e9-923b-ff5caeb8db7b.jpg)
![1568621082_0](https://user-images.githubusercontent.com/22048098/65216339-2124c500-dae3-11e9-9076-e39847db30b1.jpg)
![1568621084_8](https://user-images.githubusercontent.com/22048098/65216385-3f8ac080-dae3-11e9-9fed-bdfbc455b908.jpg)

但是在测试时如果在同一个样本中出现不同颜色或是不同字体时：
![2_5000_1](https://user-images.githubusercontent.com/22048098/65216557-e2dbd580-dae3-11e9-98b7-bde5c0821486.jpg)
类似这张图片，识别的效果往往不够理想，不知道您是否遇到过这样的情况？

**Comment by dc-chengchao** [comment]
> > 在我的操作经历中，颜色有影响，但可能不大，因为不管是训练还是检测都是转灰度图进行的。
> > 训练集中添加不同的颜色与字体的样本，对于测试是有显然的帮助的。这主要是因为模型的拓展能力的一个很重要的假设就是训练和测试的分布要类似。你不能指望训练的时候用的都是单宽度的字体，到测试的时候碰上双宽度的“口昌”，模型能识别出“唱”而不是“口”和“昌”这两个字。
> 
> 目前在我的训练集中已经添加了不同颜色和不同字体的样本，但是对于每个单个的样本，样本中的颜色和字体都是统一的：
> ![1568621081_0](https://user-images.githubusercontent.com/22048098/65216333-1bc77a80-dae3-11e9-923b-ff5caeb8db7b.jpg)
> ![1568621082_0](https://user-images.githubusercontent.com/22048098/65216339-2124c500-dae3-11e9-9076-e39847db30b1.jpg)
> ![1568621084_8](https://user-images.githubusercontent.com/22048098/65216385-3f8ac080-dae3-11e9-9fed-bdfbc455b908.jpg)
> 
> 但是在测试时如果在同一个样本中出现不同颜色或是不同字体时：
> ![2_5000_1](https://user-images.githubusercontent.com/22048098/65216557-e2dbd580-dae3-11e9-98b7-bde5c0821486.jpg)
> 类似这张图片，识别的效果往往不够理想，不知道您是否遇到过这样的情况？

那就在训练集里也加入这种图片再训练吧，应该能有提升。用合成器生成类似图片应该就行。

**Comment by changwh** [comment]
> 
> 
> > > 在我的操作经历中，颜色有影响，但可能不大，因为不管是训练还是检测都是转灰度图进行的。
> > > 训练集中添加不同的颜色与字体的样本，对于测试是有显然的帮助的。这主要是因为模型的拓展能力的一个很重要的假设就是训练和测试的分布要类似。你不能指望训练的时候用的都是单宽度的字体，到测试的时候碰上双宽度的“口昌”，模型能识别出“唱”而不是“口”和“昌”这两个字。
> > 
> > 
> > 目前在我的训练集中已经添加了不同颜色和不同字体的样本，但是对于每个单个的样本，样本中的颜色和字体都是统一的：
> > ![1568621081_0](https://user-images.githubusercontent.com/22048098/65216333-1bc77a80-dae3-11e9-923b-ff5caeb8db7b.jpg)
> > ![1568621082_0](https://user-images.githubusercontent.com/22048098/65216339-2124c500-dae3-11e9-9076-e39847db30b1.jpg)
> > ![1568621084_8](https://user-images.githubusercontent.com/22048098/65216385-3f8ac080-dae3-11e9-9fed-bdfbc455b908.jpg)
> > 但是在测试时如果在同一个样本中出现不同颜色或是不同字体时：
> > ![2_5000_1](https://user-images.githubusercontent.com/22048098/65216557-e2dbd580-dae3-11e9-98b7-bde5c0821486.jpg)
> > 类似这张图片，识别的效果往往不够理想，不知道您是否遇到过这样的情况？
> 
> 那就在训练集里也加入这种图片再训练吧，应该能有提升。用合成器生成类似图片应该就行。

这周有时间的话应该会试试的，之前的情况是两个字体不同的部分，一部分识别效果好，另一部分识别效果差，一直怀疑是不是crnn的网络结构造成的必然结果

**Comment by changwh** [comment]
最近构造了新的训练集，使一个训练样本中的文字分为两个部分，两部分的字体、字号，颜色都不同。

对基本的权重（数量最多、构成最简单的训练集训练得到的）使用新的训练集进行微调，再使用实际场景的数据再次微调。

对于字号相近的，字体（艺术字除外，因为训练集使用的字体基本为正体，不包含艺术字）和颜色对于识别结果影响不大。但是字号差距较大的，往往在字号较小部分与另一部分相邻处出现识别错误。

由于测试样本有限以及实际场景数据未包含与新训练集类似的数据，不能保证以上测试结果绝对准确，仅供参考。

**Comment by zcswdt** [comment]
> 最近构造了新的训练集，使一个训练样本中的文字分为两个部分，两部分的字体、字号，颜色都不同。
> 
> 对基本的权重（数量最多、构成最简单的训练集训练得到的）使用新的训练集进行微调，再使用实际场景的数据再次微调。
> 
> 对于字号相近的，字体（艺术字除外，因为训练集使用的字体基本为正体，不包含艺术字）和颜色对于识别结果影响不大。但是字号差距较大的，往往在字号较小部分与另一部分相邻处出现识别错误。
> 
> 由于测试样本有限以及实际场景数据未包含与新训练集类似的数据，不能保证以上测试结果绝对准确，仅供参考。
> 
> 如果有新的测试结果或是疑问，随时欢迎reopen issue。

可以分享一下你的文字合成代码吗？我也想训练类似场景的模型，谢谢了

**Comment by changwh** [comment]
> 
> 
> > 最近构造了新的训练集，使一个训练样本中的文字分为两个部分，两部分的字体、字号，颜色都不同。
> > 对基本的权重（数量最多、构成最简单的训练集训练得到的）使用新的训练集进行微调，再使用实际场景的数据再次微调。
> > 对于字号相近的，字体（艺术字除外，因为训练集使用的字体基本为正体，不包含艺术字）和颜色对于识别结果影响不大。但是字号差距较大的，往往在字号较小部分与另一部分相邻处出现识别错误。
> > 由于测试样本有限以及实际场景数据未包含与新训练集类似的数据，不能保证以上测试结果绝对准确，仅供参考。
> > 如果有新的测试结果或是疑问，随时欢迎reopen issue。
> 
> 可以分享一下你的文字合成代码吗？我也想训练类似场景的模型，谢谢了

代码是根据[TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator)魔改的，但是一直都没有整理，简单来说就是将生成的文字分为两部分，随机赋予颜色、字体、字号。
之后有时间整理好了会开源的，不过可能要过挺长一段时间的。
