### ISSUE TITLE
运行test.py results:为空

### ISSUE THREAD

**Issue by fantasy111** [Sierkinhane/crnn_chinese_characters_rec#150]
hi，作者你好：

为什么我下载下来运行test.py，results:为空呢。模型使用的是百度云提供的下载链接，没有requments.txt，所以缺什么自己就装，也不知道是不是版本的问题。依赖包如下：
numpy==1.17.2
opencv-python==4.1.1.26
Pillow==6.1.0
six==1.12.0
torch==1.1.0
torchvision==0.3.0
tqdm==4.36.1

**Comment by gordongwb** [comment]
同问

**Comment by wangxiaoyuwangdayu** [comment]
权重文件不是crnn_Rec_done_1.pth，代码里改成mixed_second_finetune_acc97p7.pth

**Comment by fantasy111** [comment]
@wangxiaoyuwangdayu 谢谢 ，可以了

**Comment by eiudng** [comment]
hi，你好
代码没动，测试图片也一样，只是模型文件分别用了你提供的，一个是用自己训练出来的，怎么结果不一样呢：用来你的模型文件结果正常，用了自己的模型文件结果是一串数字。
![微信图片_20191114224011](https://user-images.githubusercontent.com/21554401/68924450-d3af9600-07bb-11ea-9807-c68fb23d39f3.png)
![微信图片_20191115151911](https://user-images.githubusercontent.com/21554401/68924452-d4e0c300-07bb-11ea-9138-14358b7940db.png)
