### ISSUE TITLE
换了数据集，损失值一直很大，准确率为0

### ISSUE THREAD

**Issue by LXY34** [Sierkinhane/crnn_chinese_characters_rec#155]
我使用自己创建的两千多组图片作为数据集训练，进行算数题的识别（题目是印刷体，答案是手写体），迭代次数、批量大小、学习率修改之后，发现损失始终是几十多，准确率一直是0，我想请教下是什么原因？跟数据集太小有没有关系，还有印刷体跟手写体放在一起用CRNN算法是不是有问题？
![1](https://user-images.githubusercontent.com/56580617/66817098-c198c880-ef6d-11e9-9230-94147ff86ae5.png)

**Comment by Sierkinhane** [comment]
你好，和数据集大小应该有些关系，印刷体和手写字体一起应该也是可以实现的，需要你尝试其他方法，例如数据增强等慢慢调试

**Comment by 879255897** [comment]
> 我使用自己创建的两千多组图片作为数据集训练，进行算数题的识别（题目是印刷体，答案是手写体），迭代次数、批量大小、学习率修改之后，发现损失始终是几十多，准确率一直是0，我想请教下是什么原因？跟数据集太小有没有关系，还有印刷体跟手写体放在一起用CRNN算法是不是有问题？
> ![1](https://user-images.githubusercontent.com/56580617/66817098-c198c880-ef6d-11e9-9230-94147ff86ae5.png)
请问你的问题解决了么，我也是换了个两千多的纯手写体的数据集训练，loss往下降，但是准确率一直是0。

**Comment by 879255897** [comment]
@LXY34 您好，请问您的问题解决了么，我也是换了个两千多的纯手写体的数据集训练，loss往下降，但是准确率一直是0。
