### ISSUE TITLE
移动端实现问题

### ISSUE THREAD

**Issue by lebronjdw** [Sierkinhane/crnn_chinese_characters_rec#156]
你好，我在MNN板块看到你关于你用MNN部署这个工程的问题，我想问一下你部署成功之后，移动端的速度和精度怎么样呢

**Comment by lebronjdw** [comment]
因为目前我使用paddlelite的方式去训练cnn+s2s+attention的方式，速度还行，但是精度就比较差

**Comment by Sierkinhane** [comment]
你好， 我没有在移动端实现

**Comment by lebronjdw** [comment]
> 你好， 我没有在移动端实现

好的，谢谢
