### ISSUE TITLE
训练时loss很低，可以达到0.007，但是accuracy rate很低，最高只有60%

### ISSUE THREAD

**Issue by username111791** [Sierkinhane/crnn_chinese_characters_rec#159]
我自己生成了10000组10位数字的图片，训练时发现，accuracy rate在十回合左右之后就达到最高了，之后就和loss一起上下震荡了，但是这准确度实在太低了。我在处理图像时，加了一些常规的图像模糊和噪点，求求各位大佬提供一些指导和帮助，实在不想肝了，头发日渐稀少
谢谢各位！

**Comment by wangjialuu** [comment]
出现了同样的问题，请问怎样解决了？训练参数怎样设置的？ @username111791
