### ISSUE TITLE
多GPU版报错

### ISSUE THREAD

**Issue by lugeluge** [Sierkinhane/crnn_chinese_characters_rec#16]
![image](https://user-images.githubusercontent.com/16603407/47332594-55fd8180-d6b2-11e8-9e75-ce95556e48af.png)
把代码改成多GPU的train时候正常但是在val时候报错。上图用的是4GPU，数值差四倍
![image](https://user-images.githubusercontent.com/16603407/47332673-9a891d00-d6b2-11e8-8013-a0c485725124.png)
GPU代码加上了这句。
val代码加加上注释的那一句也报错
![image](https://user-images.githubusercontent.com/16603407/47332725-c86e6180-d6b2-11e8-8f62-b0374c1e4df3.png)
把 preds = preds.squeeze(2)注释掉后报错为
![image](https://user-images.githubusercontent.com/16603407/47333050-16379980-d6b4-11e8-80ff-ab0fa03d7ac2.png)

**Comment by Sierkinhane** [comment]
squeeze的参数要在-2， -1， 0， 1中选择，多GPU我没有试过，不好意思不能帮到你
