### ISSUE TITLE
是不是params.py里面的best_accuracy = 50有问题

### ISSUE THREAD

**Issue by fanhenghui** [Sierkinhane/crnn_chinese_characters_rec#165]
实际运行过程中是不是不超过1，所以是不是要改成0.5

**Comment by yerui2018** [comment]
我也遇到这个问题。我这只有0.005。1k个样本进行训练测试，也只能到0.005.

**Comment by fanhenghui** [comment]
有好几个地方要改呢，你加我qq 1256174071,我给你指点一下

**Comment by fanhenghui** [comment]
目前我改过之后训练正常了，准确率能达到95%,不过时间要好长啊

**Comment by wangjialuu** [comment]
您好请问怎样设置的训练参数能将准确率调到这么高？ @fanhenghui
