### ISSUE TITLE
希望用回以前的版本

### ISSUE THREAD

**Issue by sporterman** [Sierkinhane/crnn_chinese_characters_rec#167]
现在的新版本比以前的代码效果差很多， 希望把之前的代码加一个branch，谢谢。@Sierkinhane

**Comment by Sierkinhane** [comment]
你好，原代码也在现在的仓库，我名字区分了


| |
sierkinhane
|
|
邮箱：sierkinhane@163.com
|

Signature is customized by Netease Mail Master

在2019年11月15日 11:46，sporterman 写道：

现在的新版本比以前的代码效果差很多， 希望把之前的代码加一个branch，谢谢。@Sierkinhane

**Comment by sporterman** [comment]
@Sierkinhane 主要是现在的代码用着好奇怪， 之前用的版本跑训练很快， 10个epoch就可以收敛， 先在的版本， 跑几天才行，用了torch.nn.CTCLoss就变得很怪了，我目前torch版本1.12， 能跑吗

**Comment by sporterman** [comment]
@Sierkinhane 还有个问题请教， 我试了一下360w的数据训练和验证，发现在在训练时loss如下图
![image](https://user-images.githubusercontent.com/13059352/69029713-b4f60d00-0a10-11ea-88a2-2ee8238071a1.png)
但是我用这个模型测试训练数据和验证数据， 整个句子识别率都是75%， 字符的准确率96%， 请问这个是什么原因？过拟合了吗，中间模型我没有保存。

**Comment by Sierkinhane** [comment]
之前的loss也能用，pytorch的ctc是有点问题，有空我再完善一下。

**Comment by Sierkinhane** [comment]
我没看懂你说的准确率的问题。用360万数据集的话应该不会过拟合

**Comment by mrkind** [comment]
哪个是以前版本啊

**Comment by sporterman** [comment]
crnn_main.py

**Comment by sporterman** [comment]
> 我没看懂你说的准确率的问题。用360万数据集的话应该不会过拟合

就是在训练过程中显示的accuracy很高，但实际测试的时候就不行

**Comment by mrkind** [comment]
知道了，所有不带v2的都是旧版本

**Comment by sporterman** [comment]
有没有好的tensorflow版本的crnn推荐一下  貌似没有版本比较高的

**Comment by sporterman** [comment]
不是版本， star比较多的tensorflow版本crnn没找到
