### ISSUE TITLE
请问一下可以不定长训练吗

### ISSUE THREAD

**Issue by kylechang523** [Sierkinhane/crnn_chinese_characters_rec#168]
我在用真实数据进行model的finetuning，想问问不定长可以吗？我看设置n_test_disp = 10只在validation的部分用到了，感觉train的时候应该可以的吧

**Comment by Sierkinhane** [comment]
不定长需要对每个padding到统一长度才能concatenate成一个batch

**Comment by kylechang523** [comment]
> 不定长需要对每个padding到统一长度才能concatenate成一个batch

可是在getitem的地方不是做了一个resize吗？会把input resize到(160,32)的尺寸，为什么还需要padding呢？

**Comment by Sierkinhane** [comment]
360万数据是定长的，图片resize时文字是同等变化的。对于不定长数据，直接resize,会导致有的文字被拉伸，而有的文字被压缩，个人认为会影响最终效果（并没有做具体实验）。

**Comment by wangjialuu** [comment]
您好，可不可以解释一下“对每个padding到统一长度才能concatenate成一个batch”具体应该怎样做？初入门不太懂 @Sierkinhane 感谢！

**Comment by Sierkinhane** [comment]
@wangjialuu 选取文本数据中最长的样本的长度作为统一长度，其他的全部padding到这个长度，若是长度过长，建议剪裁。

**Comment by hualitlc** [comment]
> @wangjialuu 选取文本数据中最长的样本的长度作为统一长度，其他的全部padding到这个长度，若是长度过长，建议剪裁。

那padding 的时候对文本标注gt补充什么呢？
