### ISSUE TITLE
怎么识别笔画较多的地名，经常出错？

### ISSUE THREAD

**Issue by sporterman** [Sierkinhane/crnn_chinese_characters_rec#172]
@Sierkinhane 有没有什么建议  能够识别笔画较多的字，训练出来的模型对于地名识别错误率很高，主要错误集中在笔画较多的文字上面

**Comment by Sierkinhane** [comment]
因为这是端到端的识别，所以在训练数据方面增加该类样本会提升效果，或者解决样本不均衡的各种方法


| |
sierkinhane
|
|
邮箱：sierkinhane@163.com
|

Signature is customized by Netease Mail Master

在2019年12月03日 09:31，sporterman 写道：

@Sierkinhane 有没有什么建议 能够识别笔画较多的字，训练出来的模型对于地名识别错误率很高，主要错误集中在笔画较多的文字上面

**Comment by sporterman** [comment]
好的  只能多试试了
