### ISSUE TITLE
img.sub_(0.5).div_(0.5)

### ISSUE THREAD

**Issue by cqray1990** [Sierkinhane/crnn_chinese_characters_rec#179]
train images perform an  operation as img.sub_(0.5).div_(0.5)  but when test an images, why dont need to?
thank you

**Comment by fenguoerbian** [comment]
The actural dataloader is in dataset_v2.py, not dataset.py. And the actural test script is test_v2.py. The both normalize the image by `image.sub_(params.mean).div_(params.std)`
