### ISSUE TITLE
训练不定长数据集

### ISSUE THREAD

**Issue by andrewwyl** [Sierkinhane/crnn_chinese_characters_rec#180]
@Sierkinhane 感谢作者伟大的付出，麻烦问下，现在只能训练每个图片10个字符的数据集吗？不定长的数据集支持吗？非常感谢

**Comment by liangxin123456** [comment]
字符识别，只要使用了ctcloss ，就有对不定长的数据集进行训练的能力。
网络输出的字符个数>=（标签字符个数*2+1）就行。

**Comment by andrewwyl** [comment]
@liangxin123456 非常感谢您的回复，还有个问题想请教一下，您试过在自己的数据集（也就是在这个repo的data_generator生成的数据）在这个repo的crnn_main_v2.py训练吗？我用训练图片10000张，val数据集1000张，但是训练了300轮vall数据集的Test loss: 3.229111, accuray: 0.048000，accuray比较低，是我还需要增加训练次数，还是需要增加训练集的数量？还望大神不吝赐教！！！非常感谢

**Comment by liangxin123456** [comment]
用作者推荐的360万中文数据集，跑他的测试代码（训练那一块注释掉），精确度在79-80%左右。
在自己的数据上跑过拟合（1500张图片左右）精确度在50-70%。所以，我建议你先跑一个过拟合看看精确度是否能够达到90%以上，如果不能~~~

**Comment by andrewwyl** [comment]
> 用作者推荐的360万中文数据集，跑他的测试代码（训练那一块注释掉），精确度在79-80%左右。
> 在自己的数据上跑过拟合（1500张图片左右）精确度在50-70%。所以，我建议你先跑一个过拟合看看精确度是否能够达到90%以上，如果不能~~~

您的意思是先拿小的数据集（比如您的1500张）试试训练，训练数据和val数据集是同一个数据集？您训练了多少epoch呢？

**Comment by andrewwyl** [comment]
@Sierkinhane @liangxin123456 麻烦问一下出现下面的情况正常吗？
![image](https://user-images.githubusercontent.com/47967194/71876260-4eb07f80-3161-11ea-9481-dbfb56dfb1e4.png)

**Comment by liangxin123456** [comment]
我训练了300轮，训练数据和val数据集是同一个数据集（1500张图片）。发现精度能在0.5~0.6（个别的极限是0.7），我认为作者的模型只是从另一个训练器训练出来的，这个训练器只是跑通，并且有点效果（通过迁移训练）。
如果你使用的是Adam优化器，的确会出现这种情况（我用Adam,loss在5——>20 进行突变）（要么调整学习率，要么调整优化器），如果（加载预训练模型）出现nan（我只是跑测试（将计算梯度这些去掉了，也就是权重不更新），多半是学习率太大（可以在训练模块先打印loss，再进行反向传播，看是第几批loss就nan））

**Comment by andrewwyl** [comment]
> 我训练了300轮，训练数据和val数据集是同一个数据集（1500张图片）。发现精度能在0.5~0.6（个别的极限是0.7），我认为作者的模型只是从另一个训练器训练出来的，这个训练器只是跑通，并且有点效果（通过迁移训练）。
> 如果你使用的是Adam优化器，的确会出现这种情况（我用Adam,loss在5——>20 进行突变）（要么调整学习率，要么调整优化器），如果（加载预训练模型）出现nan（我只是跑测试（将计算梯度这些去掉了，也就是权重不更新），多半是学习率太大（可以在训练模块先打印loss，再进行反向传播，看是第几批loss就nan））

非常感谢您的回复，
我用的是作者默认的RMSprop优化器，学习率0.0001（我认为足够小了，还需要更小吗？），所以出现nan真的不知道什么原因，，，，
利用作者哪个训练一轮的模型我测试检测不出任何东西，但是看别人评论好像是有人会有效果，真的不知道什么原因，，，
正常训练是不是应该训练集和val验证集不是一个数据，但是这样训练遇到loss突变就很难输出训练模型，即使修改作者的代码强制输出模型也检测不出东西，，，
实在是头大

**Comment by liangxin123456** [comment]
正常训练是训练集和val验证集不是一个数据，（我训练集和测试集都是一个）但是我想看看作者的模型对我的数据能够达到多少（正确率）上限（过拟合 查看代码有没有问题 和查看性能上限）。我一个月之前测试过作者的代码（前文），发现效果不理想之后，就看其他人的代码。现在确定了，是我的服务器这边底层（量化）出来问题。
你可以先训练集和测试集都是同一个，看看精度稳定能不能达到90%以上（优化器使用Adadelta，学习率不给，nn.CTCloss() 里面不用sum).如果不能稳定达到效果，说明作者这个模型经过中文数据集特化，你就只是参考作者的代码，去找找其他这方面的代码。
如果能够‘稳定’达到90%以上（数据集不能太少），说明作者这条路是通的，应该从优化器 和学习率 损失函数（里面的sum）入手。

**Comment by liangxin123456** [comment]
作者网盘上的那个模型我也测试了一下，什么输出都没有。但是这种github上的pth文件倒是能够检查的比较准。
