### ISSUE TITLE
请问此项目可否应用于车牌、船名识别

### ISSUE THREAD

**Issue by mrlihellohorld** [Sierkinhane/crnn_chinese_characters_rec#182]
作者您好！
    我根据您的步骤重新训练了360w数据集，发现模型对固定场景的中英文识别较好（比如文本信息、身份证、world中的字体），但是对复杂背景的字体识别较差（例如车牌，船名等）。请问是否可以在现有基础上，进行fine-tune来识别车牌船名等图片？谢谢！

**Comment by Sierkinhane** [comment]
应该是可以的

**Comment by sssimpleboy** [comment]
> 作者您好！ 我根据您的步骤重新训练了360w数据集，发现模型对固定场景的中英文识别较好（比如文本信息、身份证、world中的字体），但是对复杂背景的字体识别较差（例如车牌，船名等）。请问是否可以在现有基础上，进行fine-tune来识别车牌船名等图片？谢谢！

请问您的效果如何呢？
