### ISSUE TITLE
很奇怪的现象,loss收敛问题

### ISSUE THREAD

**Issue by swy0915** [Sierkinhane/crnn_chinese_characters_rec#184]
我下载了代码,按照pytorch1.1版本的方式跑360万的那个数据集,在我的windows10的1080 ti上跑，loss快速到70多然后慢慢下降,训练1轮以后loss在1以下,验证96%.我把一样的代码和数据复制到我的centos7.6 显卡p40环境上,安装的也是pytorch1.1,但是运行的时候 loss下降很慢（loss从500多快速下降到200多），然后慢慢下降，,训练1轮以后loss在16左右,验证15%.
我现在定位是
1 操作系统问题
2 有些其他的包版本不一致导致
3 显卡或者显卡cuda版本的问题 windows上是1080 ti cuda9.0，centos上是p40 cuda10.0
4 pytorch的实现底层不一样导致的？

**Comment by flyindirt** [comment]
1，优化器用RMSprop；2，不使用pytorch 自带的ctc loss，用第三方自己编译的。

**Comment by Sierkinhane** [comment]
我更新了项目，训练了一轮可以达到94%准确率，似乎pytorch1.2.0的ctc loss没有bug

**Comment by Donaghys** [comment]
> 我下载了代码,按照pytorch1.1版本的方式跑360万的那个数据集,在我的windows10的1080 ti上跑，loss快速到70多然后慢慢下降,训练1轮以后loss在1以下,验证96%.我把一样的代码和数据复制到我的centos7.6 显卡p40环境上,安装的也是pytorch1.1,但是运行的时候 loss下降很慢（loss从500多快速下降到200多），然后慢慢下降，,训练1轮以后loss在16左右,验证15%.
> 我现在定位是
> 1 操作系统问题
> 2 有些其他的包版本不一致导致
> 3 显卡或者显卡cuda版本的问题 windows上是1080 ti cuda9.0，centos上是p40 cuda10.0
> 4 pytorch的实现底层不一样导致的？
您好，您这个问题最后解决了吗？
