### ISSUE TITLE
測試資料不同長度圖片,但預測字數都是固定

### ISSUE THREAD

**Issue by ekils** [Sierkinhane/crnn_chinese_characters_rec#186]
請問, 我在訓練時給圖片長度是固定imgw= 160, 圖片裡面的字是4字含空白（標籤就是4個字), 或是圖片裡面是5個字沒有空白(標籤就是5個字)。
為什麼我將訓練好的模型,拿不同長度，比如說imgh=300 裡面有約10個字, 預測出來的字也是4-5個字,想當然是全錯, 是為什麼？ 

1. 我在預測時候有等比例縮放圖片,就是固定高度32, 長度就等比例縮放
2. 
訓練和預測時候發現：
零健里改狹------------------------------------ => 零健里改狹               , gt: 腎健員步狹 
而不是像一般看到：
零-----健---里---改---------------------狹 ----=> 零健里改狹               , gt: 腎健員步狹 

會是這地方出問題嗎？或是跟keep-ratio=Ｔrue有關嗎

**Comment by Sierkinhane** [comment]
我更新了项目，训练一个epoch没有出现问题，你可以试试新的。
