### ISSUE TITLE
关于CTPN的选择

### ISSUE THREAD

**Issue by wpc11** [Sierkinhane/crnn_chinese_characters_rec#191]
请问一下如果将CRNN模型训练完成之后，有没有什么可以配套使用的CTPN配套使用呢，如果有的话希望能推荐下谢谢啦

**Comment by Sierkinhane** [comment]
近段时间没有做文本相关的工作，不过之前我倒是试了一下这个仓库https://github.com/hsddlz/faster-CTPN

**Comment by wpc11** [comment]
嗯好的我去试试，谢谢啦
