### ISSUE TITLE
char_std_5990.txt 和alphabets.py 有啥不同？

### ISSUE THREAD

**Issue by daixiangzi** [Sierkinhane/crnn_chinese_characters_rec#192]

**Comment by Sierkinhane** [comment]
一个是数据集的 图片名和标签， 一个是字典

**Comment by daixiangzi** [comment]
不是吧…这个txt里面都是字符哇

**Comment by Sierkinhane** [comment]
txt是文本图片与其文本内容

**Comment by daixiangzi** [comment]
……我说的是char_std这个文件…不是说的训练文件



---原始邮件---
发件人: "Louis."<notifications@github.com&gt;
发送时间: 2020年3月30日(周一) 晚上10:05
收件人: "Sierkinhane/crnn_chinese_characters_rec"<crnn_chinese_characters_rec@noreply.github.com&gt;;
抄送: "daixiangzi"<543826458@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Sierkinhane/crnn_chinese_characters_rec] char_std_5990.txt 和alphabets.py 有啥不同？ (#192)




 
txt是文本图片与其文本内容

**Comment by daixiangzi** [comment]
那我用自己的生成的训练集，应该用我的txt字典替换alphabets？

**Comment by Sierkinhane** [comment]
不好意思哈，太久没接触这个仓库了。 char_std是360万数据集的字典，原来的train.txt是 图片名 下标 这样的格式
```
    20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656
    20457281_3395886438.jpg 120 1061 2 376 78 249 272 272 120 1061
```
用下标来找到char_std对应的字符。alphabets是一个常用字字典，应该是包含了出现在360万中文数据的所有字符，还有一些其他字符等等。

**Comment by daixiangzi** [comment]
嗯，这样说我就明白了，也就是我如果用自己的数据，数据格式是“xxx.jpg 你好“ 类似这样的，那是不是就不要char_std了，

**Comment by daixiangzi** [comment]
只需要把自己的字典替换alphabets？

**Comment by Sierkinhane** [comment]
嗯嗯 你看一下readme，这两种格式我有写对应需要修改的东西， 这两种dataloader不一样

**Comment by oftenliu** [comment]
@Sierkinhane  你好，这两个为什么字符的总数不一样，一个是5990，另外一个是6735

**Comment by Sierkinhane** [comment]
@oftenliu 一个是数据集的字典，一个是常用的字符集
