### ISSUE TITLE
希望添加文本区域检测网络

### ISSUE THREAD

**Issue by gnipping** [Sierkinhane/crnn_chinese_characters_rec#193]
请问作者的网络是只给出了文字识别网络而没有给出文本区域检测网络吗？作者有打算添加文本区域检测网络吗？

**Comment by Sierkinhane** [comment]
有时间的话我会尝试下！

**Comment by Sierkinhane** [comment]
最近忙着其他项目，不一定会更新，你可以看看这个文本检测仓库https://github.com/hsddlz/faster-CTPN
