### ISSUE TITLE
关于ctc预测问题！！！

### ISSUE THREAD

**Issue by zhaoguoqing12** [Sierkinhane/crnn_chinese_characters_rec#194]
总在测试的时候，我的badcase有很多都是少预测一个字母，比如book会预测为bok这样的，求解答！！

**Comment by Sierkinhane** [comment]
我很久没有研究crnn了，不过你修改一下[decode](https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/stable/lib/utils/utils.py )这个方法应该可以解决你的问题，可以为其添加一个容易出错的连串的纠正字典 比如 book, look etc.
