### ISSUE TITLE
训练了一会就结束了？

### ISSUE THREAD

**Issue by wwzh2015** [Sierkinhane/crnn_chinese_characters_rec#195]
18张训练图，4张测试图，默认参数训练自己的模型
几分钟后，训练就结束了？这是正常的吗？

https://ae01.alicdn.com/kf/H6e0dd3f9e4614a39b81998216e14b3deo.png
-

**Comment by Sierkinhane** [comment]
我已经更新了项目，你可以使用新的代码。你这数据也太少

**Comment by wwzh2015** [comment]
> 我已经更新了项目，你可以使用新的代码。你这数据也太少

你这个cnn网络是不是vgg16的7层cnn？有没有加dense层？
