### ISSUE TITLE
note: fixed-length supported. yet you can modify note: fixed-length supported. yet you can modify dataloader to support random length. to support random length.

### ISSUE THREAD

**Issue by wwzh2015** [Sierkinhane/crnn_chinese_characters_rec#196]
哪有这个dataloader？

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec/blob/stable/lib/dataset/_own.py

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec/blob/stable/lib/dataset

**Comment by wwzh2015** [comment]
> https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec/blob/stable/lib/dataset

请问怎么修改可以支持不定长字符识别呢？

**Comment by Sierkinhane** [comment]
这个模型是支持不定长字符识别的，只是训练的时候需要定长

**Comment by wwzh2015** [comment]
> 这个模型是支持不定长字符识别的，只是训练的时候需要定长

这么写对吗？
13.jpg 男
15.jpg 汉
16.jpg 出生
17.jpg 2013 年 05 月 06 日
19.jpg 湖南省长沙市开福区巡道街
20.jpg 幸福小区居民组

**Comment by Sierkinhane** [comment]
我训练的时候是 图像定长，字符数也固定，你可以试试字符数不定，代码里好像是支持这个，如果报错你就改一下dataloader

**Comment by Sierkinhane** [comment]
之前有考虑字符数不固定的情况，具体有没有加上记不太清了

**Comment by wwzh2015** [comment]
> 我训练的时候是 图像定长，字符数也固定，你可以试试字符数不定，代码里好像是支持这个，如果报错你就改一下dataloader

现在不报错，就是训练完了，accuracey是0

**Comment by wwzh2015** [comment]
> 我训练的时候是 图像定长，字符数也固定，你可以试试字符数不定，代码里好像是支持这个，如果报错你就改一下dataloader

dataloader没找到在哪一行，好像你删去了吧？

**Comment by wwzh2015** [comment]
> 我训练的时候是 图像定长，字符数也固定，你可以试试字符数不定，代码里好像是支持这个，如果报错你就改一下dataloader

如果图像定长，字符数固定，这样本多难弄呀？
