### ISSUE TITLE
RuntimeError：参数＃2'目标'的张量在CPU上，但预计它在GPU上（同时检查ctc_loss_gpu的参数）

### ISSUE THREAD

**Issue by zhaoguoqing12** [Sierkinhane/crnn_chinese_characters_rec#197]
识别英语单词，中间有空格会出现这种情况，请问怎么解决？

**Comment by Sierkinhane** [comment]
报错是在哪个文件的第几行

**Comment by zhaoguoqing12** [comment]
![企业微信截图_15864099148811](https://user-images.githubusercontent.com/47818312/78956239-3c553180-7b14-11ea-9c16-019c7c5d6f05.png)

**Comment by Sierkinhane** [comment]
你下载新的代码试试
