### ISSUE TITLE
自己训练模型后用demo.py加载出错

### ISSUE THREAD

**Issue by fytwhiddleston** [Sierkinhane/crnn_chinese_characters_rec#198]
目前是可以使用大佬训练好的模型，自己训练过程中也没出错，没有出错信息准确率也正常计算，但是在使用demo.py加载自己模型的时候会报错这么一大串，除了路径和epoch数量其他都没有更改。想请教一下我这个情况是哪里出问题了吗
RuntimeError: Error(s) in loading state_dict for CRNN:
        Missing key(s) in state_dict: "cnn.conv0.weight", "cnn.conv0.bias", "cnn.conv1.weight", "cnn.conv1.bias", "cnn.conv2.weight", "cnn.conv2.bias", "cnn.batchnorm2.weight", "cnn.batchnorm2.bias", "cnn.batchnorm2.running_mean", "cnn.batchnorm2.running_var", "cnn.conv3.weight", "cnn.conv3.bias", "cnn.conv4.weight", "cnn.conv4.bias", "cnn.batchnorm4.weight", "cnn.batchnorm4.bias", "cnn.batchnorm4.running_mean", "cnn.batchnorm4.running_var", "cnn.conv5.weight", "cnn.conv5.bias", "cnn.conv6.weight", "cnn.conv6.bias", "cnn.batchnorm6.weight", "cnn.batchnorm6.bias", "cnn.batchnorm6.running_mean", "cnn.batchnorm6.running_var", "rnn.0.rnn.weight_ih_l0", "rnn.0.rnn.weight_hh_l0", "rnn.0.rnn.bias_ih_l0", "rnn.0.rnn.bias_hh_l0", "rnn.0.rnn.weight_ih_l0_reverse", "rnn.0.rnn.weight_hh_l0_reverse", "rnn.0.rnn.bias_ih_l0_reverse", "rnn.0.rnn.bias_hh_l0_reverse", "rnn.0.embedding.weight", "rnn.0.embedding.bias", "rnn.1.rnn.weight_ih_l0", "rnn.1.rnn.weight_hh_l0", "rnn.1.rnn.bias_ih_l0", "rnn.1.rnn.bias_hh_l0", "rnn.1.rnn.weight_ih_l0_reverse", "rnn.1.rnn.weight_hh_l0_reverse", "rnn.1.rnn.bias_ih_l0_reverse", "rnn.1.rnn.bias_hh_l0_reverse", "rnn.1.embedding.weight", "rnn.1.embedding.bias".
        Unexpected key(s) in state_dict: "state_dict", "epoch", "best_acc".

**Comment by wwzh2015** [comment]
你是定长训练的？训练集格式能给我看看嘛？我训练很快就结束了，准确率0

**Comment by fytwhiddleston** [comment]
> 你是定长训练的？训练集格式能给我看看嘛？我训练很快就结束了，准确率0

我用的就是大佬链接里提供的360的图片和标签，我看他是符合readme里面【20456343_4045240981.jpg 你好啊！祖国！】这种格式的就用了own_data的训练文件，只修改了图片路径。（我看readme那个示例，训练集标签是直接转换成了数字但是云盘里那个文件还是文字，而且直接用360训练文件读取时会出错，提示后面\n不能转换为int啥的，我把读取时每行的\n去了可以训练，但是读取模型还是会出一楼那个错）

**Comment by wwzh2015** [comment]
> > 你是定长训练的？训练集格式能给我看看嘛？我训练很快就结束了，准确率0
> 
> 我用的就是大佬链接里提供的360的图片和标签，我看他是符合readme里面【20456343_4045240981.jpg 你好啊！祖国！】这种格式的就用了own_data的训练文件，只修改了图片路径。（我看readme那个示例，训练集标签是直接转换成了数字但是云盘里那个文件还是文字，而且直接用360训练文件读取时会出错，提示后面\n不能转换为int啥的，我把读取时每行的\n去了可以训练，但是读取模型还是会出一楼那个错）

你能不能给几百张图片和文本标签给我？

**Comment by fytwhiddleston** [comment]
项目的readme文件里面有链接呀

**Comment by fytwhiddleston** [comment]
> > > 你是定长训练的？训练集格式能给我看看嘛？我训练很快就结束了，准确率0
> > 
> > 
> > 我用的就是大佬链接里提供的360的图片和标签，我看他是符合readme里面【20456343_4045240981.jpg 你好啊！祖国！】这种格式的就用了own_data的训练文件，只修改了图片路径。（我看readme那个示例，训练集标签是直接转换成了数字但是云盘里那个文件还是文字，而且直接用360训练文件读取时会出错，提示后面\n不能转换为int啥的，我把读取时每行的\n去了可以训练，但是读取模型还是会出一楼那个错）
> 
> 你能不能给几百张图片和文本标签给我？

项目的readme文件里面有链接呀

**Comment by wwzh2015** [comment]
> > > > 你是定长训练的？训练集格式能给我看看嘛？我训练很快就结束了，准确率0
> > > 
> > > 
> > > 我用的就是大佬链接里提供的360的图片和标签，我看他是符合readme里面【20456343_4045240981.jpg 你好啊！祖国！】这种格式的就用了own_data的训练文件，只修改了图片路径。（我看readme那个示例，训练集标签是直接转换成了数字但是云盘里那个文件还是文字，而且直接用360训练文件读取时会出错，提示后面\n不能转换为int啥的，我把读取时每行的\n去了可以训练，但是读取模型还是会出一楼那个错）
> > 
> > 
> > 你能不能给几百张图片和文本标签给我？
> 
> 项目的readme文件里面有链接呀

可以加我q吗，请教
174677002

我是直接按楼主说的的方式训练自己own_data的图片(图片我随便找了几张)，没有用字典、数字什么的，很快训练结束，而且准确率0。
还有楼主的那个dataloader是啥意思，我怎么找不到？

**Comment by zhangchunyang1995** [comment]
@fytwhiddleston 
model.load_state_dict(torch.load(args.checkpoint))  ->
model.load_state_dict(torch.load(args.checkpoint)['state_dict'])

**Comment by fytwhiddleston** [comment]
> ['state_dict']

喔喔，成功了，谢谢大佬！！！！

**Comment by wwzh2015** [comment]
> @fytwhiddleston
> model.load_state_dict(torch.load(args.checkpoint)) ->
> model.load_state_dict(torch.load(args.checkpoint)['state_dict'])

为什么我不成功？？？
demo.py: error: unrecognized arguments: --checkpoints output/checkpoints/mixed_second_finetune_acc_97P7.pth

这是故意玩我的吗

**Comment by wwzh2015** [comment]
不要加['state_dict']，没用的

这么做才行 ：
args = parser.parse_args(args=[])

**Comment by fytwhiddleston** [comment]
额，你把命令行的checkpoints改成checkpoint试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wwzh2015"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 上午10:08
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 
抄送: "shoto"<1482314995@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 自己训练模型后用demo.py加载出错 (#198)





  
@fytwhiddleston
 model.load_state_dict(torch.load(args.checkpoint)) -&gt;
 model.load_state_dict(torch.load(args.checkpoint)['state_dict'])
  
为什么我不成功？？？
 demo.py: error: unrecognized arguments: --checkpoints output/checkpoints/mixed_second_finetune_acc_97P7.pth
 
这是故意玩我的吗
