### ISSUE TITLE
正确率

### ISSUE THREAD

**Issue by Aurora11111** [Sierkinhane/crnn_chinese_characters_rec#2]
采用360万数据集,其他参数和你的一致,不管是 从头训练还是finetune最后正确率都在50左右震荡是怎么回事

**Comment by haneSier** [comment]
可以先保存模型，换个learning rate

**Comment by haneSier** [comment]
这些参数是我加了我自己生成的数据finetune的参数，如果你有条件，batch size 大一点会更好

**Comment by Aurora11111** [comment]
你是说降低学习率不断调试吗?
还有就是我看你的github下又多出一部分datagenerator,你是在调参的时候还加了数据?

**Comment by haneSier** [comment]
嗯，这个 data generator 是将模型调到我自己应用场景加的数据

**Comment by Aurora11111** [comment]
@haneSier 你的data generator里面的trian.txt怎么来的,随机截取文章里面的固定长度吗?

**Comment by haneSier** [comment]
嗯嗯对，标签和图片路径

**Comment by haneSier** [comment]
我在训练的时候，只要设置一个合适的学习率（当时我用的应该是0.001），loss能降到2左右，然后再换小一点的

**Comment by Aurora11111** [comment]
我 的loss都到0.0x了,accuracy还是在50左右震荡

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/test_images/4.png 这是我刚才跑了一下代码的结果，

**Comment by Aurora11111** [comment]
@Sierkinhane 只用了那360万数据?

**Comment by haneSier** [comment]
有加上自己的

**Comment by Aurora11111** [comment]
你这看着不是从头训练的吧,你是finetune的吧
