### ISSUE TITLE
训练自己的英文数据集，一直出现loss为nan

### ISSUE THREAD

**Issue by daixiangzi** [Sierkinhane/crnn_chinese_characters_rec#201]
标签格式如下
/media/raid0/recognize_ocr_data/0415/image/91359.jpg NLTK**Launch*the*****HBL***then***open*****NLTK***If

**Comment by wwzh2015** [comment]
这是什么标签格式？
我是这么写的
10.jpg 姓 名
11.jpg 代用名
12.jpg 性 别
结果出现这个错误，怎么改都不行（我是win10，真后悔重新git这个代码，前几天git的是可以用的但是准确率为零，再git就不行了）
这个项目全是坑！

cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
