### ISSUE TITLE
about demo.py

### ISSUE THREAD

**Issue by zcswdt** [Sierkinhane/crnn_chinese_characters_rec#202]
您好，我下载您的代码，什么都没有改变，执行了命令行，python demo.py --image_path images/test.png --checkpoints output/checkpoints/mixed_second_finetune_acc_97P7.pth。

然后给我报错，我不知道哪里出问题了，可以帮忙看一下吗？谢谢。报错如下：
usage: demo.py [-h] [--cfg CFG] [--image_path IMAGE_PATH]
               [--checkpoint CHECKPOINT]
demo.py: error: unrecognized arguments: --checkpoints output/checkpoints/mixed_second_finetune_acc_97P7.pth

**Comment by RABACCA8855** [comment]
这个demo的参数已经默认写入了，你可以不加参数直接运行这个脚本试试

**Comment by wwzh2015** [comment]
args = parser.parse_args(args=[])

**Comment by zcswdt** [comment]
> 这个demo的参数已经默认写入了，你可以不加参数直接运行这个脚本试试

不加参数已经可以运行，多谢大佬的帮助。

**Comment by zcswdt** [comment]
> args = parser.parse_args(args=[])

修改一下这个地方，加参数也能运行了，谢谢大佬的帮助。
