### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by zcswdt** [Sierkinhane/crnn_chinese_characters_rec#204]
您好，我生成了10万张文字不定长的图片，但是在训练的过程中，准确率一直不变，保持在0.625，请问一下这个大概是什么原因？
Epoch: [5][599/625]
Epoch: [5][609/625]
Epoch: [5][619/625]
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
----------------------------------------- =>                     , gt:                     
10000
16000
Test loss: 0.0000, accuray: 0.6250
is best: False
best acc is: 0.625
Epoch: [6][0/2813]	Time 0.169s (0.169s)	Speed 189.7 samples/s	Data 0.067s (0.067s)	Loss 0.00000 (0.00000)	
Epoch: [6][10/2813]	Time 0.113s (0.120s)	Speed 282.1 samples/s	Data 0.002s (0.008s)	Loss 0.00000 (0.00000)	
Epoch: [6][20/2813]	Time 0.116s (0.117s)	Speed 274.7 samples/s	Data 0.002s (0.005s)	Loss 0.00000 (0.00000)	
Epoch: [6][30/2813]	Time 0.112s (0.117s)	Speed 285.0 samples/s	Data 0.002s (0.004s)	Loss 0.00000 (0.00000)	
Epoch: [6][40/2813]	Time 0.117s (0.116s)	Speed 274.3 samples/s	Data 0.002s (0.003s)	Loss 0.00000 (0.00000)

**Comment by Sierkinhane** [comment]
检查一下标签对不对吧，你这个预测结果是空的

**Comment by zcswdt** [comment]
> 检查一下标签对不对吧，你这个预测结果是空的

 我的标签是对的啊，我检查了三天了，还是没查出来原因，换了你最早之前的版本训练还是一样为空，所以我实在是不知道哪里出问题了，可以留个联系方式，请教一下吗？

**Comment by Sierkinhane** [comment]
打印出来的gt怎么是空白呢? gt：

**Comment by zcswdt** [comment]
> 打印出来的gt怎么是空白呢? gt：

我看了源代码，找到了原因，我的训练标签，每行最后都有一个空格，所以读不到标签。谢谢回复。
