### ISSUE TITLE
关于测试场景

### ISSUE THREAD

**Issue by zcswdt** [Sierkinhane/crnn_chinese_characters_rec#206]
您好，我看您训练的模型，使用的图片是合成图片，都是没有颜色的，我想识别带颜色的文字图片，crnn能做吗？
![GkMHMFjlnBZFnE9XjK9Zsg](https://user-images.githubusercontent.com/43515926/80170645-fd969f80-861a-11ea-9821-b5a444dccc92.png)

**Comment by Sierkinhane** [comment]
用你的数据集训练，应该是没问题的
