### ISSUE TITLE
关于demo测试

### ISSUE THREAD

**Issue by zcswdt** [Sierkinhane/crnn_chinese_characters_rec#208]
您好，非常感谢您开源您的项目。我在我自己的数据集上使用了您的代码了，训练了一个模型，但是在测试执行python demo.py的时候报错。
![微信图片_20200426110843](https://user-images.githubusercontent.com/43515926/80296530-b214fa80-87ae-11ea-8246-6e53d420daf9.png)

我训练模型大小和您训练的模型大小不一样，您的是44.91M，我的是43.64M，是我训练出错了吗？
![微信图片_20200426111323](https://user-images.githubusercontent.com/43515926/80296559-f86a5980-87ae-11ea-9383-2c1e82c2ee89.png)

**Comment by Sierkinhane** [comment]
torch.save(
            {
                "state_dict": model.state_dict(),
                "epoch": epoch + 1,
                "best_acc": best_acc,
            },  os.path.join(output_dict['chs_dir'], "checkpoint_{}_acc_{:.4f}.pth".format(epoch, acc))
        )
你好，新仓库保存的时候是保存了这样一个字典，包含了epoch和best_acc，所以文件大小和你的不同， 在本仓库中，如果你要取模型的参数，应该state_dict['state_dict']这样取

**Comment by zcswdt** [comment]
谢谢您的百忙之中的回复，已经解决该问题。
