### ISSUE TITLE
中文数据集能再提供一下嘛！感谢

### ISSUE THREAD

**Issue by shuyansy** [Sierkinhane/crnn_chinese_characters_rec#209]

**Comment by Sierkinhane** [comment]
https://pan.baidu.com/s/1ufYbnZAZ1q0AlK7yZ08cvQ?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid= readme 有提供

**Comment by shuyansy** [comment]
收到，感谢您！
