### ISSUE TITLE
关于训练问题

### ISSUE THREAD

**Issue by zcswdt** [Sierkinhane/crnn_chinese_characters_rec#210]
您好，我为了训练一个繁体字识别模型，我合成了定长10字，32乘280的69万训练数据，图片如下：
![20200427094256](https://user-images.githubusercontent.com/43515926/80326548-beab5880-886b-11ea-9214-2148545aca03.png)
1.使用您的网络进行训练了100个epoch，但是在第19个epoch的时候，Loss下降到0.002左右。
![微信图片_20200427095204](https://user-images.githubusercontent.com/43515926/80326868-c61f3180-886c-11ea-9d01-ab35d4f59884.png)
2.但是在到第100个epoch的时候,loss下降到0，请问这属于正常吗？
![20200427094821](https://user-images.githubusercontent.com/43515926/80326931-f535a300-886c-11ea-86a0-5f053c4fd008.png)
3.我拿出来训练好的的第模型，测试图片，在测试集上表现的很好，但是我测试这张266乘135图片就出现测试错误。
![12](https://user-images.githubusercontent.com/43515926/80326995-31690380-886d-11ea-9980-5d46a445bd85.png)
测试结果如下：我想了一下，这个是和测试图片的尺寸和训练图片的尺寸不一样导致的吗？
![微信图片_20200427095743](https://user-images.githubusercontent.com/43515926/80327112-91f84080-886d-11ea-8e22-04a460d8586e.png)
希望得到您的指导，谢谢！

**Comment by Sierkinhane** [comment]
应该过拟合了， 看起来你测试的图片和训练的图片差别有点大

**Comment by zcswdt** [comment]
谢谢回复，测试是一些用户上传的图片，这个测试图片是rgb有颜色的图片，因为缺少标注，所以我合成了一些灰度图，但是我看到crnn在训练和测试的时候都会将图片给先转换成灰度图。所以，我就训练了，这个也会有影响吗？我才用的是定长十字训练，还有就是定长训练和不定长训练效果的话哪个更好呢？

在2020年04月28日 07:34，WoodGhost. 写道：

应该过拟合了， 看起来你测试的图片和训练的图片差别有点大

**Comment by Sierkinhane** [comment]
我没试过不定长训练，不过用定长训练效果还是很不错的，它只需要学习卷积后得到特征序列就行，而序列长短可能不会太影响最终的效果
