### ISSUE TITLE
预处理中发现了一个bug，导致训练失败，准确率一直为0

### ISSUE THREAD

**Issue by HansRen1024** [Sierkinhane/crnn_chinese_characters_rec#213]
总结：resizeNormalize类用来标准化opencv格式的图片，会让图片内容损坏，导致训练的时候输出全为“blank”，准确率一直为0。

详细：我是用的自己的数据处理方式，没用项目中的lmdb格式储存数据。我的方式最后拿到的图片是opencv格式，也就是储存在numpy中的。虽然改了resize等针对Image图片格式的操作，但是在训练中loss下降非常缓慢，准确率一直为0。打印出来的预测结果发现基本都是“blank”，后来发现是预处理resizeNormalize类导致图片内容被损坏了。我自己重写了标准化的代码后，问题就解决了。

**Comment by Sierkinhane** [comment]
你好，是新代码里面的问题吗？

**Comment by HansRen1024** [comment]
应该是新代码吧，我前几天刚下载的。

**Comment by Sierkinhane** [comment]
你好，可以把你修改的贴出来吗？我现在还不方便调试代码。

**Comment by HansRen1024** [comment]
我晕，我发错地方了。你这个没问题，另一个仓库有问题。抱歉！
