### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

### ISSUE THREAD

**Issue by jiaoxiaosong** [Sierkinhane/crnn_chinese_characters_rec#216]

**Comment by jiaoxiaosong** [comment]
python crnn_main_v2.py ， train.txt是从作者网盘下载的

**Comment by yedaorman** [comment]
我也出现了这个问题，作者可以解惑一下吗。感谢。

**Comment by Sierkinhane** [comment]
试一下新版本的代码

**Comment by yedaorman** [comment]
你的可以用了吗，我的问题是读取train.txt文件出了问题。utf-8读取会产生无效字符。open()的函数读也会出问题。test.txt没有问题。你的train.txt可以用UTF-8打开吗。要是可以可以共享我一份吗。感激。

**Comment by yedaorman** [comment]
或者说。当时下载了你的代码。里面的train.txt是空的。这个用什么方法可以解决。

**Comment by Sierkinhane** [comment]
train.txt需要下载

**Comment by Sierkinhane** [comment]
https://pan.baidu.com/s/1rd4tm0sCq5fFgB2ziUxcrA#list/path=%2F

**Comment by Sierkinhane** [comment]
旧版本需要提前准备好train.txt和val.txt，新版本不用

**Comment by yedaorman** [comment]
刚下了一下。新版本下载的话。test.txt是正常的，下载的train.txt是空的。在网页打开lib/txt/data/train.txt也是无法查看。而lib/txt/data/test.txt可以查看。可以重新上传一下吗。感谢。

**Comment by yedaorman** [comment]
百度网盘的下载后就是会出现'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte 问题

**Comment by Sierkinhane** [comment]
https://pan.baidu.com/s/1ufYbnZAZ1q0AlK7yZ08cvQ 这个文件里应该有train.txt val.txt，我现在不方便单独上传

**Comment by Sierkinhane** [comment]
eg. test.txt

    20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656
    20457281_3395886438.jpg 120 1061 2 376 78 249 272 272 120 1061
内容应该是这样的

**Comment by yedaorman** [comment]
我下载后test.txt的格式是这样的
`
20456343_4045240981.jpg 军（西点1912年班
20457281_3395886438.jpg 美丽的传说》——美丽
20458000_2937840822.jpg 投扑满。所以，他来托
`
而train.txt和这个类似，只不过使用UTF-8格式打开报了刚开始的错误。现在只能强制转换为UTF-8进行训练，还不清楚对结果的影响

**Comment by Sierkinhane** [comment]
链接：https://pan.baidu.com/s/1oOKFDt7t0Wg6ew2uZUN9xg 
提取码：eaqb

**Comment by Sierkinhane** [comment]
下载这里train.txt test.txt

**Comment by yedaorman** [comment]
可以用了，感谢感谢 @Sierkinhane

**Comment by Sierkinhane** [comment]
那close issue 吧


| |
sierkinhane
|
|
邮箱：sierkinhane@163.com
|

Signature is customized by Netease Mail Master

On 05/13/2020 20:16, yedaorman wrote:

可以用了，感谢感谢 @Sierkinhane
