### ISSUE TITLE
可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？

### ISSUE THREAD

**Issue by jiaoxiaosong** [Sierkinhane/crnn_chinese_characters_rec#218]

**Comment by Sierkinhane** [comment]
这个倒没实现

**Comment by first-wording** [comment]
> _No description provided._

你好，请问你实现了么，有问题想请教一下

**Comment by jiaoxiaosong** [comment]
实现了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sierkinhane/CRNN_Chinese_Characters_Rec"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 上午9:24
收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;;
抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218)





  
No description provided.
  
你好，请问你实现了么，有问题想请教一下

**Comment by terrynx** [comment]
> 实现了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，可以加个联系方式请教一下么，我qq是1850061652@qq.com

**Comment by terrynx** [comment]
> 实现了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，可以加个qq请教一下么，我qq是1850061652

**Comment by slackzh** [comment]
> 实现了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问如何实现，刚开始成功训练了

**Comment by jiaoxiaosong** [comment]
实现了



---原始邮件---
发件人: "Zhang Hu"<notifications@github.com&gt;
发送时间: 2021年3月8日(周一) 晚上10:57
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;;
抄送: "jiaoxiaosong"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218)




  
实现了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
请问如何实现，刚开始成功训练了

**Comment by dreamlychina** [comment]
> 实现了
> […](#)
> ---原始邮件--- 发件人: "Zhang Hu"<notifications@github.com&gt; 发送时间: 2021年3月8日(周一) 晚上10:57 收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送: "jiaoxiaosong"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) 实现了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问如何实现，刚开始成功训练了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬怎么实现？？？可以开源下代码？？大佬

**Comment by dreamlychina** [comment]
> 实现了
> […](#)
> ---原始邮件--- 发件人: "Zhang Hu"<notifications@github.com&gt; 发送时间: 2021年3月8日(周一) 晚上10:57 收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送: "jiaoxiaosong"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) 实现了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月27日(星期一) 上午9:24 收件人:&nbsp;"Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送:&nbsp;"伱ê承諾的愛"<872909437@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问如何实现，刚开始成功训练了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，可以请教怎么实现的？

**Comment by wangmengmeng99** [comment]
> > 实现了
> > […](#)
> > ---原始邮件--- 发件人: "Zhang Hu"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年3月8日(周一) 晚上10:57 收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<[CRNN_Chinese_Characters_Rec@noreply.github.com](mailto:CRNN_Chinese_Characters_Rec@noreply.github.com)>; 抄送: "jiaoxiaosong"<[872909437@qq.com](mailto:872909437@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) 实现了 … ------------------ 原始邮件 ------------------ 发件人: "Sierkinhane/CRNN_Chinese_Characters_Rec" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年7月27日(星期一) 上午9:24 收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<[CRNN_Chinese_Characters_Rec@noreply.github.com](mailto:CRNN_Chinese_Characters_Rec@noreply.github.com)>; 抄送: "伱ê承諾的愛"<[872909437@qq.com](mailto:872909437@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 可以把模型pth转onnx,onnx转ncnn,使用c++调用吗？ (#218) No description provided. 你好，请问你实现了么，有问题想请教一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问如何实现，刚开始成功训练了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 大佬，可以请教怎么实现的？
请问转化成功的ncnn里的param参数要怎么修改
