### ISSUE TITLE
please this code how HRNet relation?

### ISSUE THREAD

**Issue by daixiangzi** [Sierkinhane/crnn_chinese_characters_rec#219]

**Comment by Sierkinhane** [comment]
The projuect structure of this repository is based on hrnet project.

**Comment by daixiangzi** [comment]
Network structure？？？



---Original---

**Comment by Sierkinhane** [comment]
Code style.


| |
sierkinhane
|
|
邮箱：sierkinhane@163.com
|

Signature is customized by Netease Mail Master

On 05/22/2020 21:47, daixiangzi wrote:

Network structure？？？



---Original---
