### ISSUE TITLE
自己数据集（3W）如下。 怎么才能提高准确率

### ISSUE THREAD

**Issue by XueKX** [Sierkinhane/crnn_chinese_characters_rec#223]
![微信图片_20200525135032](https://user-images.githubusercontent.com/25972966/82783197-975aa200-9e90-11ea-800b-49748f3151a8.png)

**Comment by fenguoerbian** [comment]
合成数据，数据增强。我自己的项目大概只有2W的原始数据集，单纯使用来训练测试效果并不好（测试集准确率～70%）。后来一个是自己根据观察到的一些原始数据的特点来直接生成假的合成数据，一个是直接在原始数据集上进行数据增强（例如扭曲、截断、加噪声等）把我的训练集扩展到了100W，然后训练完的测试集上准确率就90%+了（我们因为数据的原因，还修改了网络结构使其支持更高分辨率的图片）

**Comment by wangguanhua** [comment]
> 合成数据，数据增强。我自己的项目大概只有2W的原始数据集，单纯使用来训练测试效果并不好（测试集准确率～70%）。后来一个是自己根据观察到的一些原始数据的特点来直接生成假的合成数据，一个是直接在原始数据集上进行数据增强（例如扭曲、截断、加噪声等）把我的训练集扩展到了100W，然后训练完的测试集上准确率就90%+了（我们因为数据的原因，还修改了网络结构使其支持更高分辨率的图片）

麻烦问一下您所使用数据增强的代码可否公开，我这边也是数据集不足想要进行数据增强，但找不到相应代码。

**Comment by fenguoerbian** [comment]
@wangguanhua 没啥好公开的，因为本来就是用的github上现成的。你搜text render或者synthetic text generater就行，比方说https://github.com/oh-my-ocr/text_renderer

**Comment by wangguanhua** [comment]
但是你不是说是在自己数据集的基础上进行处理的吗。还是我理解错了，你只是针对文字去生成图片而不是对图片进行二次处理？



---原始邮件---
发件人: "Chao Cheng"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 下午5:28
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 自己数据集（3W）如下。 怎么才能提高准确率 (#223)




 
@wangguanhua 没啥好公开的，因为本来就是用的github上现成的。你搜text render或者synthetic text generater就行，比方说https://github.com/oh-my-ocr/text_renderer

**Comment by fenguoerbian** [comment]
> 但是你不是说是在自己数据集的基础上进行处理的吗。还是我理解错了，你只是针对文字去生成图片而不是对图片进行二次处理？

都有阿，既做过根据文字合成图片，也做过在已有图片上进行二次处理的增强，用的就是现成github上能找到的代码。

**Comment by wangguanhua** [comment]
我想问的就是二次增强，我在github上找到的都是文字生成图片的代码。



---原始邮件---
发件人: "Chao Cheng"<notifications@github.com&gt;
发送时间: 2020年8月21日(周五) 下午2:30
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 自己数据集（3W）如下。 怎么才能提高准确率 (#223)




  
但是你不是说是在自己数据集的基础上进行处理的吗。还是我理解错了，你只是针对文字去生成图片而不是对图片进行二次处理？
  
都有阿，既做过根据文字合成图片，也做过在已有图片上进行二次处理的增强，用的就是现成github上能找到的代码。

**Comment by fenguoerbian** [comment]
> 我想问的就是二次增强，我在github上找到的都是文字生成图片的代码。

你需要再仔细找找，或者实际多看看那些项目源码。比方说一个从文字生成多种图片的repo，里面必然有对图片上面做特效的代码阿。我前面给你举例子的text_render里面就是的阿，既可以给文字生成，也可以直接调用它的特效代码到给定的图片上。

**Comment by wangguanhua** [comment]
好的，我再去看看，多谢你了



---原始邮件---
发件人: "Chao Cheng"<notifications@github.com&gt;
发送时间: 2020年8月21日(周五) 下午3:12
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 自己数据集（3W）如下。 怎么才能提高准确率 (#223)




  
我想问的就是二次增强，我在github上找到的都是文字生成图片的代码。
  
你需要再仔细找找，或者实际多看看那些项目源码。比方说一个从文字生成多种图片的repo，里面必然有对图片上面做特效的代码阿。我前面给你举例子的text_render里面就是的阿，既可以给文字生成，也可以直接调用它的特效代码到给定的图片上。

**Comment by lrfighting** [comment]
你好，我想问下你的图是怎么画的

**Comment by XueKX** [comment]
> 你好，我想问下你的图是怎么画的
这是tensorboard 可视化面板

**Comment by lrfighting** [comment]
谢谢回复，再打扰一下，请问您有这个程序计算评价指标的代码吗。在整毕设，真的很麻烦您了。
---原始邮件---
***@***.***&gt;
发送时间:2021年4月4日 星期日 下午3:15
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 自己数据集（3W）如下。 怎么才能提高准确率 (#223)



你好，我想问下你的图是怎么画的
这是tensorboard&nbsp;可视化面板

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
