### ISSUE TITLE
加载train.py时出错

### ISSUE THREAD

**Issue by freedom-xu-ming-xue** [Sierkinhane/crnn_chinese_characters_rec#229]
运行，python train.py --cfg lib/config/360CC_config.yaml
出现，(smile) F:\test\lianxi\OCR>python train.py --cfg lib/config/360CC_config.yaml
train.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://
msg.pyyaml.org/load for full details.
  config = yaml.load(f)
=> creating output\360CC\crnn\2020-06-14-15-25\checkpoints
=> creating output\360CC\crnn\2020-06-14-15-25\log
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 89, in main
    train_dataset = get_dataset(config)(config, is_train=True)
  File "F:\test\lianxi\OCR\lib\dataset\_360cc.py", line 33, in __init__
    string = ''.join([char_dict[int(idx)] for idx in indices])
  File "F:\test\lianxi\OCR\lib\dataset\_360cc.py", line 33, in <listcomp>
    string = ''.join([char_dict[int(idx)] for idx in indices])
ValueError: invalid literal for int() with base 10: '\n'
，我应该怎么办？

**Comment by Sierkinhane** [comment]
注意查看readme, 先把train.txt test.txt等文件放在相应的文件夹里

**Comment by freedom-xu-ming-xue** [comment]
好的好的，已经解决了，谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WoodGhost."; 
发送时间: 2020年6月22日(星期一) 上午10:20
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec";
抄送: "freedom-xu-ming-xue";"Author";
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 加载train.py时出错 (#229)





 
注意查看readme, 先把train.txt test.txt等文件放在相应的文件夹里
 
&mdash;
