### ISSUE TITLE
model和log的保存

### ISSUE THREAD

**Issue by gydlcc** [Sierkinhane/crnn_chinese_characters_rec#23]
我想请问一下model 和 log 实训连结束后 才保存到expr文件夹中的吗 我想可视化loss曲线怎么办

**Comment by Sierkinhane** [comment]
你用一个列表把loss存起来 用pyplot绘制保存就好

**Comment by gydlcc** [comment]
哦哦 那训练的模型呢 不自动保存吗

**Comment by haneSier** [comment]
有设置多少轮保存一次。你可以设置

**Comment by gydlcc** [comment]
ok 多谢了

**Comment by gydlcc** [comment]
那个 这个代码每次断掉都要重头开始训练，好像不能接着上次的模型继续训练埃

**Comment by Sierkinhane** [comment]
param.py中 设置crnn为你之前训练好的模型路径，主程序会判断是否reload

**Comment by gydlcc** [comment]
哦哦 知道了 多谢
