### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'FINETUNE'

### ISSUE THREAD

**Issue by first-wording** [Sierkinhane/crnn_chinese_characters_rec#233]
python train.py --cfg lib/config/OWN_config.yaml
train.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
=> creating output/OWN/crnn/2020-07-06-18-32/checkpoints
=> creating output/OWN/crnn/2020-07-06-18-32/log
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 81, in main
    if config.TRAIN.FINETUNE.IS_FINETUNE:
AttributeError: 'EasyDict' object has no attribute 'FINETUNE'
请问，在运行train.py时出现这个错误应该怎么修改呢？

**Comment by Sierkinhane** [comment]
已经修改

**Comment by first-wording** [comment]
>

> 已经修改

多谢大佬
