### ISSUE TITLE
    index = self.dict[char] KeyError: '闈'

### ISSUE THREAD

**Issue by lucasjinreal** [Sierkinhane/crnn_chinese_characters_rec#235]
I added this miss char to alphabet, but another charactor is key error, seems there were lots of chars missed in alphabet.
I using Synthetic Chinese String Dataset and I downloaded all data, but I can not reproduce your training because of key error.

What am I missing?

**Comment by Sierkinhane** [comment]
I find that there is no character ‘闈’ in char_std_5990.txt,  maybe it is a decoding error, you can check whether the character '闈' exists in your char_std_5990.txt. And  you should keep train.txt and test.txt in this format:
```
    20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656
    20457281_3395886438.jpg 120 1061 2 376 78 249 272 272 120 1061
```

**Comment by lucasjinreal** [comment]
@Sierkinhane using vscode on ubuntu open char_std_5900.txt by default, it looks like this:

![image](https://user-images.githubusercontent.com/21303438/87619828-aacb1080-c74f-11ea-9b93-efa14cd6af89.png)

After reopen it encode with gb2312, it now looks like this:
![image](https://user-images.githubusercontent.com/21303438/87619719-6f304680-c74f-11ea-8d29-4fe5289932b7.png)

So I resaved it with new encoding since it looks more reasonable.

But either one do not have a `闈` word, how does it possible got?

**Comment by lucasjinreal** [comment]
Solved, seems my resaved operation is unnecessary since code has handled it.

**Comment by JwDong2019** [comment]
您好，我也是使用了Chinese OCR数据集，用的是999999张图那部分，和你出现了同样的问题，你是具体怎么解决的呢？

**Comment by dreamlychina** [comment]
> 
这个感觉很累赘，他先是用char_std_5990.txt将label中的id转换为汉字，然后再通过他里面的alphabets.py将汉字转换为id，问题就出现在这个alphabets.py和char_std_5990.txt是不一致的，我的处理方法是用char_std_5990.txt中的内容替换为alphabets.py。

**Comment by dreamlychina** [comment]
替换alphabets.py还是会出现解码的问题，还要再_360cc.py下面的char.strip().decode('gbk', 'ignore') 换成char.strip().decode()
