### ISSUE TITLE
训练对GPU资源的要求？报内存不足

### ISSUE THREAD

**Issue by DLSeed** [Sierkinhane/crnn_chinese_characters_rec#25]
作者跑300万数据集用的GPU资源要多少？
我有一个2万张图片的数据集，做成lmdb格式也就800M，跑起来CPU模式报内存泄漏，GPU模式报Cuda计算错误——而且两者有时都是跑了一两个batch才出错的，怀疑是中间变量过大导致——把batch size从16改为1，GPU就可以正常跑了，但这样貌似没意义吧。。。
我的GPU用的是阿里云的P100，显存16G的

**Comment by Sierkinhane** [comment]
我1080 8G可以跑32batch， 应该是你设置方面出了纰漏， 16G内存很足够
