### ISSUE TITLE
您好请问训练的时候损失正常下降，但是验证集的预测为空，这是为什么

### ISSUE THREAD

**Issue by Donaghys** [Sierkinhane/crnn_chinese_characters_rec#251]
![image](https://user-images.githubusercontent.com/49194956/97100409-41538a00-16ce-11eb-8a1a-c016d731a445.png)

>

**Comment by chaochaozouzou** [comment]
> ![image](https://user-images.githubusercontent.com/49194956/97100409-41538a00-16ce-11eb-8a1a-c016d731a445.png)
> 
> >你好，请问这个问题是怎么解决的呢？
