### ISSUE TITLE
单机多卡

### ISSUE THREAD

**Issue by Donaghys** [Sierkinhane/crnn_chinese_characters_rec#261]
请问有朋友实现单机多卡吗

**Comment by sunjunlishi** [comment]
4年了没有实现

**Comment by sunjunlishi** [comment]
简单的尝试解决，更改维度：
        preds = model(inp).cpu()
        
        ps = preds.size()
        
        new_shape = ((int)(ps[0]/2), ps[1]*2, ps[2])
        preds = preds.view(*new_shape)
