### ISSUE TITLE
训练开始loss就是nan

### ISSUE THREAD

**Issue by cendelian** [Sierkinhane/crnn_chinese_characters_rec#263]
![image](https://user-images.githubusercontent.com/50360389/98927916-15306980-2514-11eb-9586-3cc0b3c8b4a9.png)
你好一开始就是nan，训练自己数据集一开始就是nan，请问该怎么解决

**Comment by NotUrNeighborMrWang** [comment]
请问您找到是哪里出错了嘛？

**Comment by cendelian** [comment]
> 请问您找到是哪里出错了嘛？

label问题，check下label是否对了

**Comment by NotUrNeighborMrWang** [comment]
> > 请问您找到是哪里出错了嘛？
> 
> label问题，check下label是否对了

您的训练集和测试集分别大概有多少数据呢？

**Comment by oszn** [comment]
我发现他如果序列过长，就会nan

**Comment by ML-Mr-J** [comment]
label的长度超过了序列的长度
