### ISSUE TITLE
关于windows下识别图片

### ISSUE THREAD

**Issue by laughing429** [Sierkinhane/crnn_chinese_characters_rec#27]
我把模型放在了windows下，识别训练的图片，发现没有识别出来。是因为在linux下训练的模型，在windows下就会出现问题吗？
原图
![image](https://user-images.githubusercontent.com/7918701/48412668-4e486e80-e780-11e8-98f0-2d4dc14e5d77.png)
识别结果：
![image](https://user-images.githubusercontent.com/7918701/48412681-5a343080-e780-11e8-8f7f-16f3a2d9031b.png)

**Comment by laughing429** [comment]
我知道什么原因了，谢谢哈。我现在用自己的数据在训练，我想请问下，在训练时，你们test loss降到多少了，accuray才不是0了呢?我现在训练集的loss已经0.5左右了，可是准确率还是0.
![image](https://user-images.githubusercontent.com/7918701/48463004-7b932c00-e815-11e8-9e94-c33fd453500e.png)

**Comment by haneSier** [comment]
看val loss

**Comment by laughing429** [comment]
这里的test loss就是val loss哦

**Comment by haneSier** [comment]
具体的我忘了，你再观察观察，或者可以在测试代码那里打印出验证的字符个数和验证正确的个数

**Comment by laughing429** [comment]
好的，那我再看看。
