### ISSUE TITLE
准确率一直为0，请问为什么，学习率调小了。每个标签集字符数必须一致吗（比如都是10个字符，标签集可不可以有不同长度的字符）

### ISSUE THREAD

**Issue by renxinlin** [Sierkinhane/crnn_chinese_characters_rec#29]
请帮忙看看，非常感谢

**Comment by haneSier** [comment]
可以不同长度，train loss降到一定程度才有预测的能力

**Comment by renxinlin** [comment]
嗯嗯，谢谢你。现在已经收敛了，训练了20个小时后，loss为0.5左右，nepoch到了15.每个epoch运行122次。在训练的时间上有什么优化的方式吗？

**Comment by haneSier** [comment]
训练速度和你的设备有关

**Comment by renxinlin** [comment]
@haneSier 我是用的虚拟机+cpu，理解了。非常感谢您的帮助！

**Comment by renxinlin** [comment]
训练时loss一直在4.5左右震荡，我设置了一个极小的学习率，依旧震荡，无法收敛。请问这是什么原因造成的？我的数据集如下
![img4679](https://user-images.githubusercontent.com/33437712/49167838-34f31500-f371-11e8-9c44-9d28127dc7ce.jpg)

**Comment by renxinlin** [comment]
之前训练的时候会将左右切割掉一部分，使得样本中字符占比更大，训练收敛了！现在的样本无法收敛，学习率和batch都设置的很小

**Comment by haneSier** [comment]
Batch有条件就设置大一点，初始学习率如果很小的话很有可能无法收敛，固定batch，设置学习率观察收敛趋势，不明显就换一个学习率

**Comment by EvenIsLee** [comment]
> @haneSier 嗯嗯，谢谢你。现在已经收敛了，训练了20个小时后，loss为0.5左右，nepoch到了15.每个epoch运行122次。在训练的时间上有什么优化的方式吗？

准确率是0可能是因为开始就没找到收敛点，你要多试几次，这个东西能不能训练上去有一定的随机性，要初始点比较好才能够上去，学习率0.001，要是训练样本比较难，你可能得换个base model
