### ISSUE TITLE
损失降下来之后突然又升上去了。。

### ISSUE THREAD

**Issue by CNU105** [Sierkinhane/crnn_chinese_characters_rec#3]
昨天训练的，损失降到0到1之间，准确率大约在88%左右吧。今早起来看损失又变成了50多，准确率是0，这是怎么回事？=.=另外作者数据集的label全是你一个一个打的吗？

**Comment by haneSier** [comment]
Label 是写了个程序生成的，晚点我传上去，那你的学习率可能太高了，loss小的时候可以先保存模型，用小的学习率学习
