### ISSUE TITLE
相反样本训练

### ISSUE THREAD

**Issue by laughing429** [Sierkinhane/crnn_chinese_characters_rec#30]
今天突然想到一个问题，假设我在训练CRNN的时候，开始我使用的白底黑字的样本，后来我又训练黑底白字样本。两种样本的风格完全相反。这样会对模型的准确率产生不好的影响吗？

**Comment by haneSier** [comment]
你的数据如果只包含其中一种就会降低，如果都包含就可以将预测泛化到这两种类型的数据

**Comment by laughing429** [comment]
好的，我现在构造了一些相反特征的样本，目前正在训练。到时候看是否有什么新的问题。

**Comment by daixiangzi** [comment]
> 好的，我现在构造了一些相反特征的样本，目前正在训练。到时候看是否有什么新的问题。

请问下，你是怎么构造相反样本的
