### ISSUE TITLE
对倾斜或弯曲字体的识别效果很差

### ISSUE THREAD

**Issue by zzhaohao** [Sierkinhane/crnn_chinese_characters_rec#31]
@Sierkinhane 你好，我使用了你训练好的模型，对横向的且清晰的文字识别率较高，但是对带有倾斜、弯曲或变形的文字识别效果很差。我尝试了对图片进行预处理矫正再使用模型预测，结果还是很差，那我是不是要在生成样本时加入一些倾斜弯曲的操作，我看你的generator.py里面没有补全旋转、噪声和字体拉伸函数。
# 旋转函数
def rotate_func():
    pass
# 噪声函数
def random_noise_func():
    pass
# 字体拉伸函数
def stretching_func():
    pass

**Comment by haneSier** [comment]
这个模型没有在这几类样本训练，所以识别效果会差，你可以增加这几类训练本去训练

**Comment by zzhaohao** [comment]
好的，谢谢，那我试一下
