### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by huazai-1994** [Sierkinhane/crnn_chinese_characters_rec#33]
大佬您好，谢谢您的分享。想请教个问题，我的数据集的图片大小是不固定的，各种尺寸都有，那么我应该怎么使用您的代码？

**Comment by haneSier** [comment]
数据最好是定高定宽，这样做不定长预测方便些。数据定高不定宽的话，test.py需要改一下

**Comment by huazai-1994** [comment]
谢谢你的回答，还有换了数据集的话，那个alphabets.py是不是也要换成自己的

**Comment by haneSier** [comment]
嗯

**Comment by huazai-1994** [comment]
嗯嗯，那这个alphabets我应该怎么做？可以提供一些代码吗

**Comment by haneSier** [comment]
将你的所有标签去重，

**Comment by yulinxuanzhi** [comment]
你好，请问尝试试过用大于32高度的图像做训练吗？如果改的话，该怎么改呢？

**Comment by zjsen668** [comment]
> 你好，请问尝试过用大于32高度的图像做训练吗？如果改的话，该怎么改呢？

我也遇到这个问题了，请问有解决办法了吗？

**Comment by huazai-1994** [comment]
> 数据最好是定高定宽，这样做不定长预测方便些。数据定高不定宽的话，test.py需要改一下

我想进行不定高不定长训练，然后进行不定长不定高预测，这可以实现吗？我的数据集中各种宽高比例都有，如何resize到某一尺寸，感觉会失真很严重

**Comment by haneSier** [comment]
1-resize成固定尺寸
2-或是修改网络参数适应你的尺寸。

**Comment by haneSier** [comment]
高度为32个像素，到最后一层卷积的输出值刚好是一个像素

**Comment by leigaoxiang** [comment]
你好，w = int(image.size[0] / (280 * 1.0 / 160))，不定宽训练的时候这个280要怎么换？？
@haneSier
