### ISSUE TITLE
我是inter显卡，这个该怎么运行起来

### ISSUE THREAD

**Issue by OKhyc** [Sierkinhane/crnn_chinese_characters_rec#35]
现在ctc  都配置完成了，运行报错：
 cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:51
不知道有没有解决方案

**Comment by haneSier** [comment]
运行crnn_main.py报错？ cuda是Nvidia的运算平台...你的是intel显卡
