### ISSUE TITLE
AttributeError: Can't get attribute '_rebuild_tensor_v2'

### ISSUE THREAD

**Issue by DLUTfangping** [Sierkinhane/crnn_chinese_characters_rec#36]
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/data8T/fangping/anaconda2/envs/pytorch_py36/lib/python3.6/site-packages/torch/_utils.py'>
我使用的pytorch版本为0.3.1,貌似是pytorch版本不对，请问你的版本是多少呢？

**Comment by DLUTfangping** [comment]
我的cuda版本是cuda80。

**Comment by haneSier** [comment]
运行什么程序出错

**Comment by DLUTfangping** [comment]
> 运行什么程序出错
运行 python test.py出错

**Comment by DLUTfangping** [comment]
@haneSier 运行 python test.py出错

**Comment by haneSier** [comment]
Python 版本多少？

**Comment by DLUTfangping** [comment]
@haneSier 3.6

**Comment by Sierkinhane** [comment]
我的版本应该是0.4，这个问题应该是pytorch版本的冲突
