### ISSUE TITLE
finetune

### ISSUE THREAD

**Issue by Jasontachiangwu** [Sierkinhane/crnn_chinese_characters_rec#37]
请问您在finetune时使用生成的数据都是10个字符的长度的吗？

**Comment by Sierkinhane** [comment]
是的

**Comment by Jasontachiangwu** [comment]
也就是说所有的训练数据的长度都是10个字符，测试集长度是随意的吧

**Comment by Jasontachiangwu** [comment]
@Sierkinhane 也就是说所有的训练数据都是10个字符的长度，而测试集是任意长度吧！这样设定的原因是为了训练更有效率还是其他原因？

**Comment by Sierkinhane** [comment]
中文数据集是十个字符，原因的话不太好说，倒是序列长度适中的话前后联结关系会强点吧，我finetune采用了具有语义信息的中文数据。

**Comment by Jasontachiangwu** [comment]
@Sierkinhane 好的，多谢解答！

**Comment by huazai-1994** [comment]
你好，我是通过train_test_split()函数去直接分的，不知道怎么让数据集来自同一分布呢。

**Comment by haneSier** [comment]
可能你的数据集太单一，不够多样化，我一开始制作的数据集很简单，就出现了过拟合的问题，我一开始有试过是 单一的白底黑字，结果过拟合很严重

**Comment by haneSier** [comment]
应该是你的数据集的对这个网络来说很容易学习，你可以加正则化，或者加dropout避免过拟合
