### ISSUE TITLE
关于test.py图像缩放参数问题

### ISSUE THREAD

**Issue by zhifengqi** [Sierkinhane/crnn_chinese_characters_rec#39]
作者您好 我想问一下test.py 对图像进行缩放w的取值问题，为什么有个280/160 这个能解释一下么

**Comment by haneSier** [comment]
我试了几个，发现这个尺寸好一些

**Comment by zhifengqi** [comment]
@haneSier 那如果正常的预测是不能试的啊，怎么去判定这个宽w的取值多少合适那，还是如果我的训练样本够充分，覆盖面比较多，就可以避免这个问题

**Comment by haneSier** [comment]
两种方法都行

**Comment by haneSier** [comment]
我用的是第一种，在测试的时候保持神经网络在训练集学习的比例就能识别

**Comment by zhifengqi** [comment]
好的 多谢
