### ISSUE TITLE
在制作数据集lmdb时候，提示有错误

### ISSUE THREAD

**Issue by yhz5256** [Sierkinhane/crnn_chinese_characters_rec#4]
Traceback (most recent call last):
  File "tolmdb.py", line 90, in <module>
    createDataset(outputPath, imagePathList, labelList)
  File "tolmdb.py", line 55, in createDataset
    imageBin = f.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by haneSier** [comment]
使用Python 2

**Comment by haneSier** [comment]
我试了一下，用Python3制作就是有问题，即使制作数据集没报错，但是读取数据训练的时候会报错

**Comment by beimingmaster** [comment]
> 使用Python 2

python3上执行是ok，有几个地方代码需要调整一下就即可。

[https://github.com/Sierkinhane/crnn_chinese_characters_rec/issues/6](url)

**Comment by beimingmaster** [comment]
> > 使用Python 2
> 
> python3上训练是ok，不过有几个地方的代码需要调整一下。参考这个issue：
> 
> [https://github.com/Sierkinhane/crnn_chinese_characters_rec/issues/6](url)

**Comment by wkgg168** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)
@beimingmaster 请问下这又是哪里有问题呢（在python2下运行的tolmdb.py)可以帮我解答下吗谢谢

**Comment by Sierkinhane** [comment]
你好，已经更新Python 2 Python 3支持的版本

**Comment by Crescentz** [comment]
python3 仍然有问题。
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-46: ordinal not in range(128)
