### ISSUE TITLE
val_root 验证集路径  

### ISSUE THREAD

**Issue by OKhyc** [Sierkinhane/crnn_chinese_characters_rec#41]
这个验证集  路径是哪个，我仅仅是生成了 lmdb文件 而已，不知道这个参数是什么意思

**Comment by Sierkinhane** [comment]
路径是存放lmdb文件的目录 不需要指定具体的lmdb文件

**Comment by Sierkinhane** [comment]
你需要将train_lmdb 与 val_lmdb分别用两个文件夹存储

**Comment by OKhyc** [comment]
我运行了您提供的例子将train_images里面的图片生成了data.mdb与lock.mdb。  运行 crnn_main.py  ，然而输出的都是1，不知道是否正常。  
还有pth 文件是怎么生成的。

**Comment by Sierkinhane** [comment]
crnn_main.py是训练网络的程序， .pth是保存网络参数的格式， 具体的你需要看代码的条件

**Comment by OKhyc** [comment]
博主你好，我现在手头有非常多的生僻字，
1. 我训练是否需要修改alphabet.py文件里面的内容。
2. 我将这些生僻字弄成随机10万张图片作为训练集数据，测试集大概多少合适？ 
3. 我测试集能不能偷懒，从训练集里面随机捞一点出来这样来弄呢？
4. 我看了源码，这个train_lmdb文件夹下的lmdb文件是训练集lmdb，val_lmdb文件夹下存放的是测试集lmdb我的理解正确吗，因为我有一些代码没怎么看懂。

**Comment by Sierkinhane** [comment]
1.  添加不存在于alphabet中的生僻字
2.  随机生成的10万可以取其中10%作为验证集，其余作为训练集
3. train--放训练集 val--放验证集

**Comment by OKhyc** [comment]
@Sierkinhane   好的  谢谢您的耐心解答

**Comment by OKhyc** [comment]
@Sierkinhane    楼主你好，我又来了，我想问一下： 繁体字怎么训练，我需要将繁体字以及对应的简体字都添加到alphabet中么。
以及 测试集有一部分数据和训练集是一样的，行不行呢。
