### ISSUE TITLE
有关训练的问题

### ISSUE THREAD

**Issue by loralyc** [Sierkinhane/crnn_chinese_characters_rec#42]
您好，我想请问下，我采用了同样的360万的数据集和标签文件，其它参数也一致，训练的时候准确率也可以达到98%，但是在另外生成的白底黑字的数据上进行测试准确率只有六十几，而且和您给的模型准确率也有所差距，请问下您有对数据进行其它什么额外的处理，还有就是另外生成的测试和训练数据非常相似，但是准确率确远不如训练的精度是什么原因呢？可以的话能否指点一下，谢谢！

**Comment by Sierkinhane** [comment]
训练集，验证集，测试集，只有这三个数据集来自同一分布，训练好的模型才能在验证集和测试集上表现更好

**Comment by Sierkinhane** [comment]
360万数据集和你生成的白底黑字还是有很大区别…你不能将在某一种分布下训练的模型去测试另外一种分布的数据

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/tree/master/data_generator

**Comment by loralyc** [comment]
好的，非常感谢，我再尝试一下finetune到新的数据集看看效果。还有个问题，不知您方不方便说一下是采用何种方法计算字符准确率的，我采用了编辑距离来计算，但是感觉计算结果不唯一，不知道还要就没有其它更合适的方法。

**Comment by huazai-1994** [comment]
@Sierkinhane 请问一下char_std_5990.txt和preprocessing是干什么用的?

**Comment by haneSier** [comment]
这是将360万中文数据集标签格式转换成这个仓库需要的格式 需要的字典和程序




------------------ 原始邮件 ------------------
发件人: "huazai-1994"<notifications@github.com>;
发送时间: 2019年2月19日(星期二) 下午3:57
收件人: "Sierkinhane/crnn_chinese_characters_rec"<crnn_chinese_characters_rec@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Sierkinhane/crnn_chinese_characters_rec] 有关训练的问题 (#42)




@Sierkinhane 请问一下char_std_5990.txt和preprocessing是干什么用的?

**Comment by huazai-1994** [comment]
/home/jinhua/图片/2019-02-19 21-21-14屏幕截图.png
@Sierkinhane @haneSier 不知道为何我这loss怎么直接为0了？

**Comment by huazai-1994** [comment]
@Sierkinhane 麻烦帮我看看我这loss怎么直接为0了？

![2019-02-19 21-21-14](https://user-images.githubusercontent.com/33715651/53061459-acf85380-34f8-11e9-8846-1b404485a615.png)

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/issues/29 可以参考最后一个回答
