### ISSUE TITLE
训练的模型与字体问题

### ISSUE THREAD

**Issue by aabbcc1234mxd** [Sierkinhane/crnn_chinese_characters_rec#44]
作者你好，首先非常感谢你提供的已训练模型和代码，这里有两个问题想问你一下：

1. 当时训练的时候是用的什么字体？是generator文件夹里面的几个吗？

2. 我现在想在你的基础上增加一些特殊字符的识别，大概数据规模需要多少呢？另外，做修改的话是否只要在alphabets.py中进行更改，然后按照README进行训练就行？

麻烦您有空解答一下，感激不尽！

**Comment by haneSier** [comment]
预训练用的是360万数据集，字体是很丰富的，增加特殊字符需要保证alphabet中存在这些字符，我在finetune的时候用了100万的数据

**Comment by aabbcc1234mxd** [comment]
哦哦，因为是这样的，我最近想对一些数学方面的进行训练，发现对于斜体times new roman的字母识别效果有些不尽人意，我是准备对于对于这种字体一定规模数据集进行训练，然后在alphabet中减少一些生僻字，您看这样的思路是否正确？另外，finetune使用的数据是generator文件夹中工商方面的信息对吧？

**Comment by haneSier** [comment]
你可以生成该种字体混合到之前的训练集中

**Comment by aabbcc1234mxd** [comment]
你好，还有一个问题想请教一下，generator.py中一定要输出280*32的图片尺寸吗？这个图片大小对于训练有影响吗，谢谢！

**Comment by aabbcc1234mxd** [comment]
我能否将长度扩展一些，保持32的宽度我知道好像跟训练有关系，因为10字的句子句意感觉不太完整
