### ISSUE TITLE
关于英文识别中的空格问题

### ISSUE THREAD

**Issue by zhifengqi** [Sierkinhane/crnn_chinese_characters_rec#45]
@haneSier @Sierkinhane   如何识别空格，是应该在训练集合中加入空格，作为label训练么？这样这个空格与ctc loss中的空格是否有影响，实际预测需要输出空格，该怎么做？

**Comment by haneSier** [comment]
这个我倒没实验过，- 预测的就是字符之间的空隙，你可以对比一下效果
