### ISSUE TITLE
训练   loss一直很大，训练效果非常不理想

### ISSUE THREAD

**Issue by OKhyc** [Sierkinhane/crnn_chinese_characters_rec#46]
根据一百种字体生成将近50万张图片，45万张作为训练集，5万张作为测试集，训练loss 一直徘徊在20.几左右。训练完了，除了训练集里面的图片能识别，其他同样字体图片都不能识别。我是需要调整什么参数呢

**Comment by haneSier** [comment]
Validation loss多少？可以发几张图片看看吗？训练loss 20多是一个很大的loss这导致没有泛化能力

**Comment by OKhyc** [comment]
crnn_main 我clone 下来就没动过，我替换了一下 alphabets 现在 loss 已经是2.0几，我试试看  现在行不行 ，但是楼主你的博客图里面是0.几  ，不知道你是怎么达到的

**Comment by OKhyc** [comment]
![default](https://user-images.githubusercontent.com/8369293/51892399-bb14f180-23dc-11e9-9025-bd52119320b2.jpg)
上面是我的其中一个训练集的图片。  
![default](https://user-images.githubusercontent.com/8369293/51892493-0d561280-23dd-11e9-93ec-1bc6d12eefe2.jpg)
上面是我的一张用来做测试集图片。
我训练完成后，这个测试集图片内文字居然一个都不能识别。训练集的图片文字都是能正常识别。不知道哪弄错了。
我现在只挑选了一部分内容： 训练集3500张图片，测试集： 500张图片，尺寸都是*320*32，字体都是同一个

**Comment by OKhyc** [comment]
![2019-01-29 17-05-18](https://user-images.githubusercontent.com/8369293/51896770-26b08c00-23e8-11e9-8c3e-7f6ab3e3c0f9.png)
我居然才216..是因为我图太少了么

**Comment by haneSier** [comment]
总数/batch size =216

**Comment by OKhyc** [comment]
![2019-01-30 13-44-33](https://user-images.githubusercontent.com/8369293/51960814-81ec8800-2495-11e9-8c29-5515395b6ec5.png)
你好，这是我现在训练的结果，是不是有问题。
