### ISSUE TITLE
您好，请问用于训练的数据一定是280*32大小吗，可不可以是不定长宽？上面必须是10个字符吗？谢谢！

### ISSUE THREAD

**Issue by Lemonyue** [Sierkinhane/crnn_chinese_characters_rec#47]

**Comment by Sierkinhane** [comment]
高度32 宽度可变，字符数可以变

**Comment by Lemonyue** [comment]
如果我生成的数据字符数多于10个，那图片是不是也要成比例加长？我的意思是必须保证每个字符占28个像素吗，少于28个像素可不可以

**Comment by Sierkinhane** [comment]
没有要求，字体大小是随机的，只要字符能出现在图片中就行

**Comment by juventi** [comment]
@Sierkinhane  训练不定长度的数据代码需要修改么？是要对一个batch中的不用长度进行补齐么？ 我lmdb制作ok了，直接跑的话跑不起来，代码运行到 cost = criterion(preds, text, preds_size, length) / batch_size  这行就会段错误，求教

**Comment by haneSier** [comment]
我在训练时字符数和宽高都是定的，只需要在测试时修改一小部分代码就可以实现不定长识别， 可以把报错的信息发出来吗

**Comment by juventi** [comment]
你好，我的训练数据是定宽32，不定长的， 是训练代码出错的 ，目前只显示了Segment fault ..

**Comment by Lemonyue** [comment]
请问生成数据的字间距有影响吗，如果我需要识别的数据字间距比较大，那我是不是也要生成相同间距的数据用于训练呢？




------------------ 原始邮件 ------------------
发件人: "IdleCell."<notifications@github.com>;
发送时间: 2019年2月27日(星期三) 下午5:07
收件人: "Sierkinhane/crnn_chinese_characters_rec"<crnn_chinese_characters_rec@noreply.github.com>;
抄送: "柠檬不萌"<2953143236@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Sierkinhane/crnn_chinese_characters_rec] 您好，请问用于训练的数据一定是280*32大小吗，可不可以是不定长宽？上面必须是10个字符吗？谢谢！ (#47)




没有要求，字体大小是随机的，只要字符能出现在图片中就行

**Comment by haneSier** [comment]
可以

**Comment by Lemonyue** [comment]
我的意思是如果我生成的间距与真实数据不一样，会不会影响识别效果呀？

**Comment by hwwu** [comment]
> 你好，我的训练数据是定宽32，不定长的， 是训练代码出错的 ，目前只显示了Segment fault ..

我也尝试固定高度为32，将长度根据原始大小按比例缩放，结果训练不了，可能输入input的shape必须一样，可是缩放到固定比例，训练数据字数差别很大，少的两个字，多的十几个字，拉伸太厉害，识别效果不理想，不知道有什么好的解决方法没

**Comment by daming98** [comment]
高度固定到32的话，也就是说，竖排文字就没法用了。

**Comment by stillarrow** [comment]
> 高度固定到32的话，也就是说，竖排文字就没法用了。

对的，因为高度固定32是为了保证CNN的部分最后一层输出的宽是1，这样才能进到RNN层里面。我感觉如果你想做竖版文字识别的话首先训练集得有竖版文字，其次要把crop出来的竖版文字图像旋转一下再做resize然后传入网络。
