### ISSUE TITLE
数据字符问题

### ISSUE THREAD

**Issue by chenxu93** [Sierkinhane/crnn_chinese_characters_rec#49]
您好我看这个360w数据集中的字符为6736.个 ，的数据集中有一些特殊繁体字，与alphabet.py中的字合并后成为9116个字。但是用这个新的alphabet.py文件后不能在测试成功。报以下错误

oading pretrained model from trained_models/mixed_second_finetune_acc97p7.pth
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    model.load_state_dict(torch.load(crnn_model_path))
  File "/home/imc/XR/anaconda3/envs/crnn-chinese/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CRNN:
	size mismatch for rnn.1.embedding.weight: copying a param with shape torch.Size([6736, 512]) from checkpoint, the shape in current model is torch.Size([9116, 512]).
	size mismatch for rnn.1.embedding.bias: copying a param with shape torch.Size([6736]) from checkpoint, the shape in current model is torch.Size([9116]).
(crnn-chinese) imc@imc-NO108:~/XR/models/chenxu/crnn_chinese$
请问在网络中是不是 字符长度个数是写死了的？
为何怎么提示shape不匹配？要如何修改呢？

**Comment by Sierkinhane** [comment]
类别在rnn部分固定了

**Comment by aabbcc1234mxd** [comment]
同问要怎么修改。。求各位大佬指点一下

**Comment by Sierkinhane** [comment]
可以只导入cnn部分的参数，rnn部分重新训练
