### ISSUE TITLE
Why the image tensor with shape(imgH, imgH) but not shape(imgH, imgW) ?

### ISSUE THREAD

**Issue by Fighting-JJ** [Sierkinhane/crnn_chinese_characters_rec#51]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/c0b51081ef95e8bf5840e5e78d9d88f25e260b36/crnn_main.py#L158

**Comment by Fighting-JJ** [comment]
@Sierkinhane  I will be apreatiate for your reply

**Comment by Sierkinhane** [comment]
just a variable， it will be resized in utils.loaddata()

**Comment by Fighting-JJ** [comment]
> just a variable， it will be resized in utils.loaddata()

Thanks a lot.
