### ISSUE TITLE
在windows环境下，运行出现了如下错误，可以帮忙看一下，问题在哪里么？

### ISSUE THREAD

**Issue by Fighting-JJ** [Sierkinhane/crnn_chinese_characters_rec#52]
![image](https://user-images.githubusercontent.com/17001854/53780200-3dde1e80-3f3e-11e9-9d1b-f562d8b7b16c.png)

@Sierkinhane 
我是在python3  windows环境下生成的data.mdb

**Comment by haneSier** [comment]
最好用Ubuntu 16.04

**Comment by Fighting-JJ** [comment]
> 最好用Ubuntu 16.04

恩，已经放弃windows啦，一堆坑。
