### ISSUE TITLE
请教关于微调的问题

### ISSUE THREAD

**Issue by jackstraw2012** [Sierkinhane/crnn_chinese_characters_rec#55]
非常感谢楼主把代码贡献出来，为大家提供了很好的学习机会。
我想问一下，如果我要增加自己的业务数据作为训练数据，我应该怎么做呢？
另外有什么工具可以用来标注数据，自动生成图形文件+文本文件呢？

**Comment by Sierkinhane** [comment]
可以参考我写的data_generator，

**Comment by jackstraw2012** [comment]
@Sierkinhane data_generator是生成模拟数据吧，如果我要加入部分实际业务数据呢？例如发票，有什么好用的标注工具呢？

**Comment by Sierkinhane** [comment]
我应该会收集发票背景，然后用相似的字体生成模拟数据
