### ISSUE TITLE
In test.py, you resized the w of input_data by  w = int(image.size[0] / (280 * 1.0 / 160)) , can you tell me why you do this ?

### ISSUE THREAD

**Issue by Fighting-JJ** [Sierkinhane/crnn_chinese_characters_rec#56]
def crnn_recognition(cropped_image, model):

    converter = utils.strLabelConverter(alphabet)
  
    image = cropped_image.convert('L')

    ## 
    w = int(image.size[0] / (280 * 1.0 / 160))
    transformer = dataset.resizeNormalize((w, 32))
    image = transformer(image)

Will the factor 280 or other number affects the accuracy of prediction?

**Comment by Fighting-JJ** [comment]
另外，加个微信？或者搞一个微信群？还有几个问题请教一下。

1、你在synth90k的数据集上训练过吗？accuracy能达到多少？我使用的pytorch自带的nn.CTCLoss, 当前训练的accuracy在0.86，不知道还能提高不？

2、关于输入图像resize的问题。  代码中每个batch的图形都resize到了（H : 32, W : batch 相关）
@Sierkinhane @haneSier

**Comment by haneSier** [comment]
It keeps the scaling factor in line with training then works for recognition of unlimited strings

**Comment by haneSier** [comment]
My WeChat id:Szlkinhane

**Comment by Fighting-JJ** [comment]
> My WeChat id:Szlkinhane

你是不是把通过微信号添加好友的方式关闭了？搜索不到微信号。
我微信ID： lovezed6300

**Comment by stillarrow** [comment]
> It keeps the scaling factor in line with training then works for recognition of unlimited strings

I am just wondering how comes the value of 160. I understand that the value of 280 represent the train image's width and the input height should be locked to 32 (for this network). But how comes the value of 160?
