### ISSUE TITLE
模型泛化能力问题

### ISSUE THREAD

**Issue by Z-J-Z** [Sierkinhane/crnn_chinese_characters_rec#60]
作者您好，

我在训练的时候，train-loss能够降到0.0几，但是val-loss依旧在20以上，并且val-accuracy只有0.35，我的训练集和验证集分别为5万：1万随机划分，请问如何才能提高模型的泛化能力呢？

**Comment by Sierkinhane** [comment]
一般小数量的数据集按8:2， 7:3这样分

**Comment by Sierkinhane** [comment]
你的模型已经过拟合了你的训练集

**Comment by Z-J-Z** [comment]
能否提供下载360万数据集下训练的预训练模型进行finetune

**Comment by Z-J-Z** [comment]
你好作者，
我使用360万数据集，按你的划分训练，训练loss下降的很快，验证loss还是很高？ 请问怎么回事
