### ISSUE TITLE
下载的中文数据集只能解压出约60万的图片，在windows下用好压无法修复

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#61]

**Comment by Sierkinhane** [comment]
试试 winRAR

**Comment by monologue1107** [comment]
> 试试 winRAR

生成lmdb数据的时候需要根据train.txt和test.txt分别生成两个lmdb数据文件嘛？

**Comment by monologue1107** [comment]
训练时出现报错：
python crnn_main.py --trainroot ./to_lmdb/lmdb/train/ --valroot ./to_lmdb/lmdb/test/ --cuda 
Namespace(cuda=True, trainroot='./to_lmdb/lmdb/train/', valroot='./to_lmdb/lmdb/test/')
Traceback (most recent call last):
  File "crnn_main.py", line 132, in <module>
    train_dataset = dataset.lmdbDataset(root=opt.trainroot)
  File "/data/rwd/code/crnn_chinese_characters_rec-master/dataset.py", line 25, in __init__
    meminit=False)
lmdb.Error: ./to_lmdb/lmdb/train/: No such file or directory

生成lmdb文件有data和lock两个文件，目前的文件结构是
-to_lmdb
  --lmdb
    ---train
      train_data.mdb
      train_lock.mdb
    ---test
      test_data.mdb
      test_lock.mdb
不知道为什么lmdb打开有错误

**Comment by monologue1107** [comment]
python crnn_main.py --trainroot /data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/train --valroot /data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/test
Namespace(cuda=False, trainroot='/data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/train', valroot='/data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/test')
204972
段错误(吐核)

为什么会发生段错误了 求助

**Comment by monologue1107** [comment]
我尝试减少训练集和测试集的规模，也仍然会发生段错误
