### ISSUE TITLE
训练发生段错误

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#62]
python crnn_main.py --trainroot /data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/train --valroot /data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/test
Namespace(cuda=False, trainroot='/data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/train', valroot='/data/rwd/code/crnn_chinese_characters_rec-master/to_lmdb/lmdb/test')
204972
段错误(吐核)

为什么会发生段错误了，求助。尝试将训练集内容变小但仍然会报段错误

**Comment by Sierkinhane** [comment]
确定一下生成的lmdb文件是否正确，段错误很可能是你文件里没内容

**Comment by monologue1107** [comment]
> 确定一下生成的lmdb文件是否正确，段错误很可能是你文件里没内容

我使用了最新更新的to_lmdb.py文件，但是出现错误
Traceback (most recent call last):
  File "tolmdb.py", line 101, in <module>
    createDataset(outputPath, imgPathList, labelList)
  File "tolmdb.py", line 77, in createDataset
    writeCache(env, cache)
  File "tolmdb.py", line 30, in writeCache
    txn.put(str(k).encode('utf-8'), str(v).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
如果按照原来的txn.put(k,v)的确会导致lmdb数据文件格式损坏，这样要怎么处理？

**Comment by monologue1107** [comment]
我想问一下生成的lmdb文件如果直接cat的话是不是乱码的？
因为对图片文件进行read，感觉如果直接cat的确有可能是乱码？

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/blob/master/to_lmdb/to_lmdb_py2.py 你尝试一下python2版的程序

**Comment by monologue1107** [comment]
是这样的，我用了python2版的程序后生成有大小有内容的lmdb数据文件，在服务器用cat直接看data.mdb是乱码，不过下载到本地用sublime text看就是规整的二进制数字。不过直接f.read读到的图片信息个人感觉应该就是这样子的（？）
但是重新试了一下还是存在段错误，不知道要从何处开始排查。是个新手，有点蒙圈了。

**Comment by juventi** [comment]
lz 解决了吗  我也是段错误，py2生成的lmdb，py3跑的train代码

**Comment by monologue1107** [comment]
> lz 解决了吗 我也是段错误，py2生成的lmdb，py3跑的train代码

并没有。。渐入自闭不知道为啥

**Comment by juventi** [comment]
我把代码和lmdb数据拷到ubuntu14.04下直接跑就可以了；
python3.6+torch 1.0.0+centos 段错误
python3.5+torch 0.4.0 +ubuntu 直接可以训练

**Comment by monologue1107** [comment]
> 我把代码和lmdb数据拷到ubuntu14.04下直接跑就可以了；
> python3.6+torch 1.0.0+centos 段错误
> python3.5+torch 0.4.0 +ubuntu 直接可以训练

多谢你，我把torch版本降到0.4.1以后在centos上也可以正常训练了
