### ISSUE TITLE
accuracy问题

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#64]
测试过程中一开始显示为
Start val
----------------------------------------- =>                     , gt: 联盟第4位，我反正二          
----------------------------------------- =>                     , gt: 块雕花的细节都可成就          
----------------------------------------- =>                     , gt: 年没有因健康原因住院          
----------------------------------------- =>                     , gt: APA是世界上历史最          
----------------------------------------- =>                     , gt: 中央电视台著名主持人          
----------------------------------------- =>                     , gt: 论坛)都有杰出的表现          
----------------------------------------- =>                     , gt: kie("sport          
----------------------------------------- =>                     , gt: 中的胆固醇和脂肪含量          
----------------------------------------- =>                     , gt: 发动机的核心部位。“          
----------------------------------------- =>                     , gt: 登陆艇在发射管后铺设          
0
1600
Test loss: 64.552345, accuray: 0.000000

后续会变成
Start val
--楼--，---袁--隆--平---奖--则---颁--给---了------- => 楼，袁隆平奖则颁给了          , gt: 楼，袁隆平奖则颁给了          
-地---区---和--平---与--稳---定--做---出--更------- => 地区和平与稳定做出更          , gt: 地区和平与稳定做出更          
--结---合---中---国---古---代---科---学---思---想-- => 结合中国古代科学思想          , gt: 结合中国古代科学思想          
--游---总----局--、、----四--川川---[-图----库--]-- => 游总局、四川[图库]          , gt: 游总局、四川[图库]          
-A-mm-e-r--i-c-aa-n-s--f----------------- => Americansf          , gt: Americansf          
--潜--艇--常--被---美-国---海--军--用--来---------- => 潜艇常被美国海军用来          , gt: 潜艇常被美国海军用来          
-0-9--目---前---已--基基---本--敲---定---的------- => 09目前已基本敲定的          , gt: 09目前已基本敲定的          
--注---重---培---训训--，----捷---克---V-S--意---- => 注重培训，捷克VS意          , gt: 注重培训，捷克VS意          
--他---们---在---背---后--已----经---做---了---许-- => 他们在背后已经做了许          , gt: 他们在背后已经做了许          
--构--、、---本---人---所---知---情---的---范---围-- => 构、本人所知情的范围          , gt: 构、本人所知情的范围          
12561
1600
Test loss: 0.096455, accuray: 7.850625

请问accuracy在这个数值是正常的吗，看起来训练效果应该还不错为什么只有7.8

**Comment by JingLiJJ** [comment]
你好。你解决这个问题了嘛？我的accuracy也很低。。。。

**Comment by monologue1107** [comment]
> 你好。你解决这个问题了嘛？我的accuracy也很低。。。。

如果你是像我一样accuracy大于1，那事实上accuracy应该是在0-1之间的，我这里出现了7点几我后来排查了一下，是因为计算公式出现了问题，你可以核对一下这个问题。

**Comment by vlzzhou** [comment]
请问你解决accurancy这个问题了没？怎么解决的啊
