### ISSUE TITLE
准确率归一化问题

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#65]
训练过程中效果如下
Start val
--计--有---一--定---压--力---。--春---节--将------- => 计有一定压力。春节将          , gt: 计有一定压力。春节将          
--三---大---营---养--物---质---的---来---源---和--- => 三大营养物质的来源和          , gt: 三大营养物质的来源和          
--些--常常--见---的---实--例---。--i-n-v--------- => 些常见的实例。inv          , gt: 些常见的实例。inv          
““--这---些---导---弹---都---是--为为--大---陆----- => “这些导弹都是为大陆          , gt: “这些导弹都是为大陆          
--大--厦--附--近---多--家--旅--行--社--发---------- => 大厦附近多家旅行社发          , gt: 大厦附近多家旅行社发          
--简---历--、---组---织---笔---试---、--层---层---- => 简历、组织笔试、层层          , gt: 简历、组织笔试、层层          
--不---会---讲---德----语--，，--2---．---工---程-- => 不会讲德语，2．工程          , gt: 不会讲德语，2．工程          
--上--海--申--花--队---这--场--比--赛--打---------- => 上海申花队这场比赛打          , gt: 上海申花队这场比赛打          
--塞---，---全---了---性---命---，---正---好---针-- => 塞，全了性命，正好针          , gt: 塞，全了性命，正好针          
--道---后--，，---么--经---?--”----那---些--和---- => 道后，么经?”那些和          , gt: 道后，么经?”那些和          
11601
1600
Test loss: 0.616874, accuray: 7.250625
问一下要怎么对准确率进行归一化呢？

**Comment by Sierkinhane** [comment]
nT/nV (预测正确的字数/验证集中的字数)
