### ISSUE TITLE
关于训练集的几个问题

### ISSUE THREAD

**Issue by infinitisun** [Sierkinhane/crnn_chinese_characters_rec#7]
想请教下 你的mixed_second_finetune_acc97p7.pth 模型文件 是基于360万张开源数据集+自己本地脚本生成的，一些本地常用文字组合的数据集 一次训练出来的呢 还是基于开源数据集训练生成的模型 再而二次训练生成的？
还有一个问题是 我试了一下你的模型文件 对于白底黑字识别精度挺好的 但是对于复杂一些的背景识别结果一般，和网上一些其他开源的模型文件识别结果有差距 是因为你用的360万张数据集本身的背景不够多样化导致的吗

**Comment by haneSier** [comment]
对的，个人认为对于不同场景的文本识别需要使用特定的数据来做增强训练，我这个模型是增强了白底黑字这类数据的

**Comment by infinitisun** [comment]
> 对的，个人认为对于不同场景的文本识别需要使用特定的数据来做增强训练，我这个模型是增强了白底黑字这类数据的

ok 了解了 我看到了你的alphabet长度是大于5530的 应该是包含了繁体中文的对吧。事实上我现在是想要训练繁体中文 想问一下 如果要构造繁体中文的数据集 构造的量级大概是多少比较合适？可否也基于之前的模型做二次训练呢？

**Comment by haneSier** [comment]
可以生成一个简体少繁体多的数据集，做迁移学习收敛会更快

**Comment by infinitisun** [comment]
明白了 我试一下 后面有问题再来请教 3q

**Comment by infinitisun** [comment]
> 可以生成一个简体少繁体多的数据集，做迁移学习收敛会更快

我试着在已有ckpt基础上 生成了一些繁体+简体的数据集 做了迁移学习以后 发现对识别准确率较之前反而下降了

**Comment by Lemonyue** [comment]
@haneSier 您好，请问验证集和测试集要如何分配？还有就是如何进行批量测试，而不是只测试一张图片？

**Comment by haneSier** [comment]
验证集是用来衡量模型的泛化能力，测试集是测试实际应用中的泛化能力，我用的360万数据集中训练集和测试的分配是9-1，没有测试集，

**Comment by haneSier** [comment]
你想多张测试看效果的话可以参考验证的代码

**Comment by Lemonyue** [comment]
为什么算准确率的时候验证集总数是1600呢

**Comment by Lemonyue** [comment]
算准确率是按照单个字符算的，还是按照整个标签序列算的？也就是统计对的字符数还是统计对的标签数？

**Comment by haneSier** [comment]
具体可以看源代码的实现

**Comment by jjccyy** [comment]
你好，我想请教一下，数据集是如何制作的

**Comment by haneSier** [comment]
有360万的现成数据，然后代码中有
datagenerator程序可以生成数据

**Comment by elena9243** [comment]
> > 可以生成一个简体少繁体多的数据集，做迁移学习收敛会更快
> 
> 我试着在已有ckpt基础上 生成了一些繁体+简体的数据集 做了迁移学习以后 发现对识别准确率较之前反而下降了

你好，可以分享一下迁移学习的代码吗，感谢

**Comment by OKhyc** [comment]
应该怎么训练，我现在照片的背景都是花花绿绿的，如何进行训练

**Comment by haneSier** [comment]
可以先去虑除噪点，但是不要太过度。如果只剩下黑白，数据集就太单一

**Comment by OKhyc** [comment]
我先在利用opencv将图片灰度处理了，我用这个tolmdb.py  生成的lmdb数据集，是否在别的crnn ocr项目也可用呢
