### ISSUE TITLE
实现多语言同时翻译的方法

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#71]
作者给定的语料库中，可以同时实现对中英文夹杂的文本识别。但是如果是要实现多语言的话，比如中文和藏文的夹杂识别，除了扩充数据集，把包含中文和藏文的数据集进行同时训练外，有没有其他的可实现的方法？

**Comment by Sierkinhane** [comment]
1, 数据增强
2, 用具有语义信息的语料库

**Comment by monologue1107** [comment]
> 1, 数据增强
> 2, 用具有语义信息的语料库

这些方法都是通过更改数据集的方法来实现同时翻译的支持，作者有没有什么推荐的改进是在神经网络本身结构或者外接类似于决策树的方式来实现同时翻译。我个人想想就是这样的改动就会有点大了，但是不知道有什么可以着手的方向，现在看了一下论文也没有太多的头绪。

**Comment by ZhuoyaYang** [comment]
用具有语义信息的语料库是指？
