### ISSUE TITLE
用于识别车牌字符

### ISSUE THREAD

**Issue by wkgg168** [Sierkinhane/crnn_chinese_characters_rec#72]
你好，我在用你提供的网络，训练小量的真实车牌数据集（670张），bitchsize=64迭代了5000次，利用训练集里的图片去测试发现车牌字符识别效果非常差，请问你能提供点什么建议吗？（新手），非常感谢

**Comment by Sierkinhane** [comment]
模型收敛的怎么样呢，train loss 和val loss 分别是多少

**Comment by wkgg168** [comment]
你好，训练的时候一切正常收敛得不错能训练集和验证集都是同一个数集，val里能非常正常的显示，如下
Start val
苏AA---------------G----7---33---33-----LL => 苏AG733L             , gt: 苏AG733L             
苏AAH-----------------66----8----77---000- => 苏AH6870             , gt: 苏AH6870             
NY---------------00---00---000----4----00 => NY00040             , gt: NY00040             
苏AAD----------------11--11--11---33--33-- => 苏AD11133            , gt: 苏AD11133            
苏AA--------------SS----8----NN---55---33- => 苏AS8N53             , gt: 苏AS8N53             
苏AA---------------44----V----GG---66---66 => 苏A4VG66             , gt: 苏A4VG66             
苏AAH-----------------66----55---333---555 => 苏AH6535             , gt: 苏AH6535             
苏AA--------------99----2----B----00---55- => 苏A92B05             , gt: 苏A92B05             
苏AA---------------R-----7----8---99-----W => 苏AR789W             , gt: 苏AR789W             
苏AA----------------8---99---99---L----99- => 苏A899L9             , gt: 苏A899L9             
2995
3000
Test loss: 0.000038, accuray: 0.998333
[0/1][301/324] Loss: 0.000496

但是当我抽出训练集里的一些图片拿训练好的模型去测试（用的test.py去测试的）的时候却根本不能识别出什么东西。不知道是哪里出问题了，能提供一点思路吗，谢谢

**Comment by Sierkinhane** [comment]
可以给几个样本看看吗？

**Comment by wkgg168** [comment]
你好，我发现应该是你的test.py文件有问题。我用别人的预测代码载入用你的代码训练出来的模型来检测能识别出图像中比较多的字符。由于是新手，我找不出问题在哪里，下面我给你几个样本看看，非常感谢你能在繁忙之中，关注这个问题。
![one_line_10292_bright0-7](https://user-images.githubusercontent.com/35217610/55671962-0e695b80-58c8-11e9-924a-5c0aaccf4d42.jpg)
![one_line_1240_sharpness0-7](https://user-images.githubusercontent.com/35217610/55671997-63a56d00-58c8-11e9-92f5-ff7ed1d9d83e.jpg)
![one_line_9851](https://user-images.githubusercontent.com/35217610/55672056-1675cb00-58c9-11e9-8e16-b70e4e0a4805.jpg)

**Comment by wkgg168** [comment]
另外我发现。我利用github上的开源车牌生成器生成的车牌拿来训练（3万张），只需要迭代很小的次数就能能很好的识别训练集里的图片（用的是你的test.py），而且非常准确,但是用别人的预测代码载入模型来识别得到的结果却很不理想。生成的假车牌图片有固定的宽度和高度（272 * 72）真实车牌不具有固定宽度与高度
![demo3000](https://user-images.githubusercontent.com/35217610/55672780-81c39b00-58d1-11e9-83a0-d01284da5487.png)
![test3000](https://user-images.githubusercontent.com/35217610/55672782-85572200-58d1-11e9-8efd-b5230aed8ea1.png)

**Comment by Sierkinhane** [comment]
在我的test.py中有一个比率放缩，你留意到这个点没？

**Comment by wkgg168** [comment]
w = int(image.size[0] / (280 * 1.0 / 160))
    transformer = dataset.resizeNormalize((w, 32))
是这两行吧，由于没什么经验，请问博主对于此类车牌图像的字符识别有什么比较好的值推荐吗？，谢谢
以前听说过宽高比会影响图像的识别

**Comment by Sierkinhane** [comment]
因为在训练时的时候我有将宽为280的图片resize成160,所以在预测的时候也需要将图片按这个比例放缩

**Comment by wkgg168** [comment]
非常感谢你提供的帮助，已经非常完美的解决了我的问题，你的代码为我提供了不少的帮助，已经给你点亮了star。可以顺便问下你为什么你的代码在训练和检测时resize的尺寸要设置成不一样的呢？有什么特殊的用处吗？

**Comment by Sierkinhane** [comment]
当时是为了节省显存
