### ISSUE TITLE
Why is Nonetype?And i use the right mdb still have this wrong.

### ISSUE THREAD

**Issue by softwaregitgub** [Sierkinhane/crnn_chinese_characters_rec#73]
![04ddd507600677322a576aabf068622](https://user-images.githubusercontent.com/40431492/55568403-38891500-5732-11e9-9472-9b153256cb11.png)
![471434d2791bdc67372b7c8d0ff832b](https://user-images.githubusercontent.com/40431492/55568405-38891500-5732-11e9-8a9a-a3ca1cadba5e.png)
![bf46cf9f07af1d67535c62aa61aa78c](https://user-images.githubusercontent.com/40431492/55568406-38891500-5732-11e9-881d-1904726828d7.jpg)

**Comment by Sierkinhane** [comment]
检查一下路径是否正确

**Comment by softwaregitgub** [comment]
> 检查一下路径是否正确

我刚刚解决了这个问题。需要用python2来制作lmdb格式的训练集。好奇，为什么Python3制作的就会有问题呢？

**Comment by mitsuily** [comment]
> > 检查一下路径是否正确
> 
> 我刚刚解决了这个问题。需要用python2来制作lmdb格式的训练集。好奇，为什么Python3制作的就会有问题呢？

您好，我也遇到了这个问题，用您的这种方式，改用Python2来制作lmdb的训练集鄂，还是跑着跑着就出这个错，您解决了么

**Comment by mitsuily** [comment]
> 检查一下路径是否正确

检查什么的路径？？
