### ISSUE TITLE
发票微调训练的问题

### ISSUE THREAD

**Issue by apapa2018** [Sierkinhane/crnn_chinese_characters_rec#75]
我在原来的模型参数文件下进行微调用自己制作的数据集，数据集图片如下。但是训练和train loss很低了，但是test loss很高，只能识别一个字而且识别效果也下降了，我用了3000张图片进行训练的。图片来自医院的发票的截选文字图片。希望可以解答
![000001_9_0](https://user-images.githubusercontent.com/40136150/55773287-7b484580-5ac2-11e9-8858-030578d6a418.jpg)
![000003_8_1](https://user-images.githubusercontent.com/40136150/55773303-88fdcb00-5ac2-11e9-8d7d-38097a3ab6bf.jpg)
![559232665649758958](https://user-images.githubusercontent.com/40136150/55773311-8dc27f00-5ac2-11e9-8569-3940d6e72d18.jpg)

**Comment by Sierkinhane** [comment]
过拟合了，你需要增加训练集

**Comment by leigaoxiang** [comment]
你好，你微调的时候有把自己的数据加到360万的数据里面？

**Comment by leigaoxiang** [comment]
@apapa2018

**Comment by Cocoalate** [comment]
你好，请问您的数据集是怎么生成的呢，可以分享一下数据集嘛？
