### ISSUE TITLE
自己的数据集，训练中出的错

### ISSUE THREAD

**Issue by mitsuily** [Sierkinhane/crnn_chinese_characters_rec#76]

**Comment by mitsuily** [comment]
是训练中，代码跑了一段时间就停了，报错是这样
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by junkojunko** [comment]
你好，请问您是怎么解决的的这个问题，已经被这个问题困扰了几天了

**Comment by Sierkinhane** [comment]
请问你们使用python几制作的lmdb文件

**Comment by mitsuily** [comment]
我还没有解决，应该是从lmdb文件中读取数据的时候出的错，有可能是某张图片没有转化成功，或者转化成功了但是并没有成功读取






在 2019-04-11 13:17:40，"junkojunko" <notifications@github.com> 写道：


你好，请问您是怎么解决的的这个问题，已经被这个问题困扰了几天了

**Comment by mitsuily** [comment]
我用2和3都做了一遍，都不行





在 2019-04-11 13:18:58，"IdleCell." <notifications@github.com> 写道：


请问你们使用python几制作的lmdb文件

**Comment by junkojunko** [comment]
@Sierkinhane 你好博主，我用p2和p3都试了一遍，都会出错，而且找不到哪里出错，我尝试在写入lmdb时候判断是不是None，结果发现写入时候没有错误，都是bytes，而在读取数据的时候我发现错误的地方读取出的数据类型为Nonetype，不知道什么原因引起的。

**Comment by vlzzhou** [comment]
您好，不知道您的loss一直增大之后怎么进行处理，让他降低的？
