### ISSUE TITLE
第一个epoch training loss就很小，validation时候accuracy为0

### ISSUE THREAD

**Issue by shengyucaihua** [Sierkinhane/crnn_chinese_characters_rec#77]
作者你好，按照readme用360万数据制作了lmdb格式的数据开始训练，在刚开始的时候training loss就达到了零点零几，但在validation的时候完全学不到东西，想请问下您，这可能是因为什么原因导致的呢？

**Comment by Sierkinhane** [comment]
调整下学习率，我训练时候初始的loss在80左右

**Comment by Sierkinhane** [comment]
调整下学习率，我训练时候初始的loss在80左右

**Comment by intgogo** [comment]
我的初始学习率也只有零点零几
@Sierkinhane 我看到你是分了好几个阶段来训练的，请问下分别用什么学习率和优化算法，我看你到你代码里支持Adam Adadelta RMSprop三种，是不是有什么讲究？

**Comment by Sierkinhane** [comment]
推荐使用adam或rmsprop
