### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by wuxiaolianggit** [Sierkinhane/crnn_chinese_characters_rec#78]
Traceback (most recent call last):
  File "./crnn_main.py", line 197, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "./crnn_main.py", line 112, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "./crnn_main.py", line 90, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/data/wuxl/crnn_chinese_characters_rec/utils.py", line 106, in encode
    index = self.dict[char1]
KeyError: u'\u516c'

请问大神，有遇到过这个问题吗？

**Comment by Sierkinhane** [comment]
很可能是Python 版本不同引起的编码问题，请问你是用什么版本生成的lmdb文件

**Comment by wuxiaolianggit** [comment]
我用的时python3生成的lmdb，用python2执行的训练脚本，这样会出错，是吗？

**Comment by Sierkinhane** [comment]
Py2制作，py3训练

**Comment by wuxiaolianggit** [comment]
好的，多谢大神，还想问一下，这个版本支持不定长训练吗

**Comment by wuxiaolianggit** [comment]
我看数据集都是定长10个字符

**Comment by Sierkinhane** [comment]
没问题的

**Comment by Sierkinhane** [comment]
支持
