### ISSUE TITLE
测试代码

### ISSUE THREAD

**Issue by DNSun** [Sierkinhane/crnn_chinese_characters_rec#79]
作者能给下测试部分的代码吗,现在没了,那个net参数是生成的模型吗

**Comment by Sierkinhane** [comment]
test.py就是测试代码

**Comment by DNSun** [comment]
@Sierkinhane 那个val函数呢

**Comment by Sierkinhane** [comment]
crnn main里面包含验证，我只将数据集分为训练集和验证集，没有分配测试集

**Comment by DNSun** [comment]
@Sierkinhane 是的，但是crnn main里现在没有调用val来验证，这个函数要怎么调用呢，自己试了下感觉结果好像不太对

**Comment by DNSun** [comment]
> crnn main里面包含验证，我只将数据集分为训练集和验证集，没有分配测试集

是的，但是crnn main里现在没有调用val来验证，这个函数要怎么调用呢，自己试了下感觉结果好像不太对
