### ISSUE TITLE
安装warp-ctc出问题

### ISSUE THREAD

**Issue by Lemonyue** [Sierkinhane/crnn_chinese_characters_rec#8]
yue@yue-Vostro-3668:~/crnn_chinese_characters_rec$ cd warp-ctc/pytorch_binding
yue@yue-Vostro-3668:~/crnn_chinese_characters_rec/warp-ctc/pytorch_binding$ python setup.py install
Torch was not built with CUDA support, not building warp-ctc GPU extensions.
generating build/warpctc_pytorch/_warp_ctc/__warp_ctc.c
(already up-to-date)
not modified: 'build/warpctc_pytorch/_warp_ctc/__warp_ctc.c'
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-8801.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.5/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by haneSier** [comment]
你是安装的时候出错吗

**Comment by haneSier** [comment]
还是使用

**Comment by haneSier** [comment]
推荐用Ubuntu 16.04系统

**Comment by Lemonyue** [comment]
是的，难道跟cuda有关？

**Comment by Lemonyue** [comment]
是的，难道跟cuda有关？

**Comment by Lemonyue** [comment]
是的，难道跟cuda有关？

**Comment by haneSier** [comment]
编译试下加sudo. 我的是pytorch-gpu cuda9.0

**Comment by Sierkinhane** [comment]
@Lemonyue https://github.com/SeanNaren/Warp-ctc/issues可以参考这里提的issue解决方案

**Comment by beimingmaster** [comment]
> yue@yue-Vostro-3668:/crnn_chinese_characters_rec$ cd warp-ctc/pytorch_binding
> yue@yue-Vostro-3668:/crnn_chinese_characters_rec/warp-ctc/pytorch_binding$ python setup.py install
> Torch was not built with CUDA support, not building warp-ctc GPU extensions.
> generating build/warpctc_pytorch/_warp_ctc/__warp_ctc.c
> (already up-to-date)
> not modified: 'build/warpctc_pytorch/_warp_ctc/__warp_ctc.c'
> running install
> Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
> ```
> [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-8801.pth'
> ```
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
> ```
> /usr/local/lib/python3.5/dist-packages/
> ```
> Perhaps your account does not have write access to this directory? If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account. If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
> https://pythonhosted.org/setuptools/easy_install.html
> 
> Please make the appropriate changes for your system and try again.

“Permission denied” 这种错误一般就是权限问题，命令加sudo即可。

**Comment by huazai-1994** [comment]
@Sierkinhane ![default](https://user-images.githubusercontent.com/33715651/49585189-a9910980-f998-11e8-99d7-32bceb7a56f6.png)编译出错，不知道怎么弄。请问你知道哪里出了问题吗？

**Comment by haneSier** [comment]
你是Ubuntu 什么版本

**Comment by huazai-1994** [comment]
@Sierkinhane 16.04

**Comment by huazai-1994** [comment]
@haneSier 16.04

**Comment by tbfly** [comment]
18.04 ubuntu system, can replace by: https://github.com/jpuigcerver/pytorch-baidu-ctc.

**Comment by Sierkinhane** [comment]
Good job

**Comment by sunzjz** [comment]
> @Sierkinhane ![default](https://user-images.githubusercontent.com/33715651/49585189-a9910980-f998-11e8-99d7-32bceb7a56f6.png)编译出错，不知道怎么弄。请问你知道哪里出了问题吗？

我也遇到同样的问题，请问你解决了吗，非常感谢
