### ISSUE TITLE
竖排文本识别

### ISSUE THREAD

**Issue by chengjie11** [Sierkinhane/crnn_chinese_characters_rec#80]
请问答主
1. 我看了crnn的paper了解了 英文字符识别其实是像state这样的单词中间加blank等各种情况的转移（有点类似马尔科夫链） 请问中文字符的识别是什么情况呢 没有想明白
2.如果我要做竖排文本识别 有什么比较好的思路吗

**Comment by Develkone** [comment]
请问竖排文本识别你找到什么好的思路了吗
