### ISSUE TITLE
TypeError:a bytes-like object is required,not 'NoneType'

### ISSUE THREAD

**Issue by mitsuily** [Sierkinhane/crnn_chinese_characters_rec#82]
![00d04e9e42bbf4f9a65ea56f2d9e519](https://user-images.githubusercontent.com/32731991/56093176-d9788c80-5ef7-11e9-9ed4-40fbe5f2e10b.png)
如上所示，lmdb用的是py2制作，训练是python3，检查了路径也没有错，各位有什么思路么？

**Comment by Sierkinhane** [comment]
你的数据集完整吗？

**Comment by mitsuily** [comment]
数据集完整吗？我不太理解你说的意思，你是说标注信息之类的完整性？

**Comment by mitsuily** [comment]
> 你的数据集完整吗？

完整的啊

**Comment by mariembs01** [comment]
Comment the #index += 1 in __getitem_b and change 
def __len__(self):
        return self.nSamples + 1
To
def __len__(self):
        return self.nSamples

That fixed my issue.

**Comment by mitsuily** [comment]
> Comment the #index += 1 in **getitem** and change
> def **len**(self):
> return self.nSamples + 1
> To
> def **len**(self):
> return self.nSamples
> 
> That fixed my issue.

In my program，this method can't solve my problem.Thank you all the same!

**Comment by mariembs01** [comment]
You can make your program print which image is giving the Nonetype problem. And it'll print the your nSample + 1 image which doesn't exist. 

It may not help but I'm giving suggestions ^-^

And you're welcome.

**Comment by shengyucaihua** [comment]
请问下楼主解决这个问题了么？我也遇到了同样的问题

**Comment by mitsuily** [comment]
> 请问下楼主解决这个问题了么？我也遇到了同样的问题
没有，试了楼上的方法，没有用，期待作者有什么方法解决。

**Comment by shengyucaihua** [comment]
我似乎解决了 打印index发现 生成的txt文件里最后两张图片的路径有问题，将生成的txt最后两行删掉在我这里就不会报错了

**Comment by mitsuily** [comment]
> 我似乎解决了 打印index发现 生成的txt文件里最后两张图片的路径有问题，将生成的txt最后两行删掉在我这里就不会报错了

你是说你用那个data_generator来做的数据，在生成label的时候图片路径有错误？

**Comment by shengyucaihua** [comment]
是的

**Comment by mariembenslama** [comment]
I'm the same @mariembs01 ^^
Based on shengyucaihua experience,
Here for those using data_generator:
def __len__(self):
        return self.nSamples - 1 #<--- change this like this

    def __getitem__(self, index):
        assert index < len(self), 'index range error' # <--- instead of <= change it to <
        
        with self.env.begin(write=False) as txn:
            img_key = 'image-%09d' % index
            imgbuf = txn.get(img_key.encode('utf-8'))

            buf = six.BytesIO()
            buf.write(imgbuf)
            buf.seek(0)
            try:
                img = Image.open(buf).convert('L')
            except IOError:
                print('Corrupted image for %d' % index)
                return self[index + 1]

            if self.transform is not None:
                img = self.transform(img)

            label_key = 'label-%09d' % index
            label = txn.get(label_key.encode())

            if self.target_transform is not None:
                label = self.target_transform(label)
        index += 1 # <-- put the index += 1 here
        return (img, label)

# This won't print the last two empty cases that produces the Nonetype error

**Comment by CS2JOONGKI** [comment]
> I'm the same @mariembs01 ^^
> Based on @shengyucaihua experience,
> Here for those using data_generator:
> def **len**(self):
> return self.nSamples - 1 #<--- change this like this
> 
> ```
> def __getitem__(self, index):
>     assert index < len(self), 'index range error' # <--- instead of <= change it to <
>     
>     with self.env.begin(write=False) as txn:
>         img_key = 'image-%09d' % index
>         imgbuf = txn.get(img_key.encode('utf-8'))
> 
>         buf = six.BytesIO()
>         buf.write(imgbuf)
>         buf.seek(0)
>         try:
>             img = Image.open(buf).convert('L')
>         except IOError:
>             print('Corrupted image for %d' % index)
>             return self[index + 1]
> 
>         if self.transform is not None:
>             img = self.transform(img)
> 
>         label_key = 'label-%09d' % index
>         label = txn.get(label_key.encode())
> 
>         if self.target_transform is not None:
>             label = self.target_transform(label)
>     index += 1 # <-- put the index += 1 here
>     return (img, label)
> ```
> This won't print the last two empty cases that produces the Nonetype error

I try this but get the same wrong,do you deal with it?

**Comment by mariembenslama** [comment]
Check out issue #81

**Comment by Holmeyoung** [comment]
@mitsuily  i borrowed some code from author, you can have a try
https://github.com/Holmeyoung/crnn_pytorch

**Comment by CS2JOONGKI** [comment]
> Check out issue #81

thank you

**Comment by D201830280253** [comment]
> Comment the #index += 1 in **getitem** and change
> def **len**(self):
> return self.nSamples + 1
> To
> def **len**(self):
> return self.nSamples
> 
> That fixed my issue.

This method fixed my issue, too! Thank you very much!
