### ISSUE TITLE
代码问题。

### ISSUE THREAD

**Issue by JingLiJJ** [Sierkinhane/crnn_chinese_characters_rec#83]
你好。我有一个问题

在utils.py文件里

`self.alphabet = alphabet + '-'  # for `-1` index`

是什么意思呀？‘-’不是在字典里已经有了吗？怎么代表eos呢？

**Comment by ws-lin** [comment]
@Sierkinhane 除此之外，代码字符集里面还有将‘1.’当成一个字符的操作。
