### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by liamrhli** [Sierkinhane/crnn_chinese_characters_rec#85]
使用py2跑tolmdb_py3会报UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte错误，使用py3.6制作数据集没错但是训练时会报  TypeError: a bytes-like object is required, not 'NoneType'

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec/issues/82

**Comment by liamrhli** [comment]
> #82
打扰您了，我用py2制作数据集，会报这个错误，好像是在输出路径那里，
lmdb.Error: ./model: Unknown error
输出路径是这样写的：outputPath = './model'，请问有什么问题吗？

**Comment by Sierkinhane** [comment]
一个文件夹存train lmdb 一个文件夹存val lmdb

**Comment by liamrhli** [comment]
> 一个文件夹存train lmdb 一个文件夹存val lmdb

您好，train lmdb 和val lmdb不是应该读取不同的.txt文件分别制作吗

**Comment by Sierkinhane** [comment]
是的

**Comment by liamrhli** [comment]
> 是的
感谢您的回复，那我分两次制作做就ok啊，我还是不太懂问题出在哪里，方便的话加我q1060856705，我详细向您询问！！再次感谢

**Comment by liamrhli** [comment]
谢谢您，我跑通了，您的模型在我的场景下效果不好，我需要重新训练，对你的97的模型再训练时lr=0.0001，loss=nan，请问怎么调参，我是一枚小白，希望能得到您的指导，感谢！！

**Comment by puhui888** [comment]
请问您是怎么跑通的？我也遇到这个问题了，试了很多方法都解决不了。烦请教一下，谢谢！

**Comment by shihuangxiong** [comment]
Traceback (most recent call last):
  File "D:/lunwen9.16/crnn/lib/create_lmdb_dataset.py", line 100, in <module>
    createDataset(outputPath, imagePathList, labelList)
  File "D:/lunwen9.16/crnn/lib/create_lmdb_dataset.py", line 73, in createDataset
    writeCache(env, cache)
  File "D:/lunwen9.16/crnn/lib/create_lmdb_dataset.py", line 31, in writeCache
    txn.put(k, v)
TypeError: Won't implicitly convert Unicode to bytes; use .encode()
制作lmdb  程序报错这么回事啊？本人小白一枚
