### ISSUE TITLE
更改batchsize可以训练吗以及TypeError:a bytes-like object is required,not 'NoneType'

### ISSUE THREAD

**Issue by 2snoopy88** [Sierkinhane/crnn_chinese_characters_rec#86]
我更改了batchsize为100,但是训练准确率一直是0,同样遇到TypeError:a bytes-like object is required,not 'NoneType'问题,请问有成功的解决方法吗,我试了上一个issue的方法,好像不行

**Comment by Sierkinhane** [comment]
检查下是不是缺漏照片？

**Comment by CS2JOONGKI** [comment]
> 检查下是不是缺漏照片？

已经可以训练了，但是预训练模型是不是不能用，因为最后文字分类参数不一样，我现在自己训练半天准确率能有35%左右，达不到那么高，是因为数据集不够吗，我训练测试都是1w的数据集。

**Comment by yanno2** [comment]
@CS2JOONGKI 你好，请问nonetype的问题你是怎么解决的？我用的自己的训练集，我用py2和py3制作的lmdb文件都不可以使用，训练时会出现TypeError: a bytes-like object is required, not 'NoneType'的问题

**Comment by CS2JOONGKI** [comment]
> @CS2JOONGKI 你好，请问nonetype的问题你是怎么解决的？我用的自己的训练集，我用py2和py3制作的lmdb文件都不可以使用，训练时会出现TypeError: a bytes-like object is required, not 'NoneType'的问题

#82 参考这个还有前面那个关于NoneType的issue

**Comment by CS2JOONGKI** [comment]
> @CS2JOONGKI 你好，请问nonetype的问题你是怎么解决的？我用的自己的训练集，我用py2和py3制作的lmdb文件都不可以使用，训练时会出现TypeError: a bytes-like object is required, not 'NoneType'的问题

#82 #81 参考这两个issue

**Comment by yanno2** [comment]
@CS2JOONGKI 好的，谢谢

**Comment by houyangcan** [comment]
> @CS2JOONGKI 好的，谢谢

您好，请问您解决这个问题了吗？

**Comment by jokaon** [comment]
我也出现了这个错误，但是解决了，问题出在我们生成的lmdb文件并不是正确的．因为从文档中随机选取的10个文字里面包含空格，然而在生成lmdb文件的时候，需要通过split(' ')来进行分割txt文件里面的内容，来找到文件名和图片内容，然而图片内容里面包含空格，例如:
```
>>> a = 'img_0.jpg  abcd ef g  h '
>>> a.split(' ')
['img_0.jpg', '', 'abcd', 'ef', 'g', '', 'h', '']
>>> a.split(' ')[-1]
''
>>> a.split(' ')[0]
'img_0.jpg'
>>> a.split(' ')[1]
''
```
甚至可能导致取的图片内容和真实的不同,只是真实内容的一部分，但却不会报nonetype的错误．
@yanno2 @Sierkinhane

**Comment by jokaon** [comment]
还有就是你需要修改dataset.py下的__getitem__里的代码:
```
 def __getitem__(self, index):
        assert index < len(self), 'index range error'
        with self.env.begin(write=False) as txn:
            img_key = 'image-%09d' % index
            imgbuf = txn.get(img_key.encode('utf-8'))

            buf = six.BytesIO()
            buf.write(imgbuf)
            buf.seek(0)
```

**Comment by yanno2** [comment]
非常感谢 @jokaon

**Comment by wutianye** [comment]
> 还有就是你需要修改dataset.py下的__getitem__里的代码:
> 
> ```
>  def __getitem__(self, index):
>         assert index < len(self), 'index range error'
>         with self.env.begin(write=False) as txn:
>             img_key = 'image-%09d' % index
>             imgbuf = txn.get(img_key.encode('utf-8'))
> 
>             buf = six.BytesIO()
>             buf.write(imgbuf)
>             buf.seek(0)
> ```

我根据你的回答解决了这个bug  但是又报：
RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()
请问您遇到过吗

**Comment by jokaon** [comment]
> > 还有就是你需要修改dataset.py下的__getitem__里的代码:
> > ```
> >  def __getitem__(self, index):
> >         assert index < len(self), 'index range error'
> >         with self.env.begin(write=False) as txn:
> >             img_key = 'image-%09d' % index
> >             imgbuf = txn.get(img_key.encode('utf-8'))
> > 
> >             buf = six.BytesIO()
> >             buf.write(imgbuf)
> >             buf.seek(0)
> > ```
> 
> 我根据你的回答解决了这个bug 但是又报：
> RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()
> 请问您遇到过吗

非常抱歉，我没遇见过这个问题。帮不到你，也许你需要新开一个issue.

**Comment by itomorrower08** [comment]
@2snoopy88 
> 已经可以训练了，但是预训练模型是不是不能用，因为最后文字分类参数不一样，我现在自己训练半天准确率能有35%左右，达不到那么高，是因为数据集不够吗，我训练测试都是1w的数据集。
您好，我想请问下按照issue81和82的解决方法，不会报错Nontype，但是loss一直为0.。之后我把batch改为几十之后，loss很快降下来，准确率也上去了，但是又会出现Nontype的问题，请问是什么原因呢？lmdb数据制作成功，理论上应该不存在图片为空的情况的啊。标签中也没有空格了。期待收到您的回复，谢谢。

**Comment by leigaoxiang** [comment]
> > 检查下是不是缺漏照片？
> 
> 已经可以训练了，但是预训练模型是不是不能用，因为最后文字分类参数不一样，我现在自己训练半天准确率能有35%左右，达不到那么高，是因为数据集不够吗，我训练测试都是1w的数据集

你好，请问你有改什么？
标签中不能有空格？

**Comment by Lanme** [comment]
我也是改了但还是继续报错。

**Comment by Lanme** [comment]
关键是这是中文，中文是没有空格的，我看那些图片示例也没有一个是有空格的，所以应该是其他问题。
