### ISSUE TITLE
定长识别问题。

### ISSUE THREAD

**Issue by JingLiJJ** [Sierkinhane/crnn_chinese_characters_rec#87]
你好。我看了issues的回答有点糊涂了。这个模型到底是定长识别还是不定长识别呢？

**Comment by Sierkinhane** [comment]
不定长识别

**Comment by Sierkinhane** [comment]
定长训练，不定长测试。

**Comment by JingLiJJ** [comment]
测试的时候按照等比例缩放是嘛？根据每张图片的长度的不同，不一定是/280*160？

**Comment by leigaoxiang** [comment]
代码里面w = int(image.size[0] / (280 * 1.0 / 160))写的太死了，感觉测试效果不好

**Comment by Sierkinhane** [comment]
280和160是训练集图片放缩前后的尺寸，视不同的训练情况而定，并没有写死。

**Comment by leigaoxiang** [comment]
那如果我的图片是不定长的，w = int(image.size[0] / (280 * 1.0 / 160))这个280要怎么改

**Comment by Sierkinhane** [comment]
如果你的训练集是不定长的，那你在训练的时候就不需要压缩（压缩不是必要的，只是为了减少内占用），然后测试时把这公式去掉。

**Comment by Sierkinhane** [comment]
或者直接将280改成你测试图片的宽度，我没尝试过这样可不可行

**Comment by leigaoxiang** [comment]
我尝试过，效果不好，自己数据不可能是定长的啊，我尝试过先把自己的数据统一搞到32*160，那w就是160，效果也有的行有的不行

**Comment by leigaoxiang** [comment]
对于自己不定长数据训练你有训练过？

**Comment by leigaoxiang** [comment]
自己的不一定长数据可以加到360万的数据里面一起训练？

**Comment by WangXuanBT** [comment]
> 定长训练，不定长测试。

你好，不定长测试效果很差呀。我直接下载的已经提供出来的模型，用test.py测试test_images下的图片效果很好，但是测试自己的图片，比如是37*187的图片效果就很差。关于这个设置：w = int(image.size[0] / (280 * 1.0 / 160))我没怎么看懂什么意思，总之应该就是图片拉伸不合理导致的效果很差，我想知道到底应该怎样拉伸图片才是合理的拉伸(高度32，宽度怎样计算)？

**Comment by Sierkinhane** [comment]
可以提供一下你的测试图片？

**Comment by Sierkinhane** [comment]
@WangXuanBT

**Comment by WangXuanBT** [comment]
> 可以提供一下你的测试图片？

![img_0009494](https://user-images.githubusercontent.com/8284999/62188313-8ccd9a00-b39e-11e9-9401-6592e2649067.jpg)
比如这个图片，原尺寸是655*54的，我通过宽度拉伸遍历发现只有在w=250的时候效果最好。。

**Comment by Sierkinhane** [comment]
应该与训练集有关，我提供的模型是针对于白底黑字。（280和160是训练集图片放缩前后的尺寸，我在很多issue里已经解释了很多次了）

**Comment by changwh** [comment]
> > 可以提供一下你的测试图片？
> 
> ![img_0009494](https://user-images.githubusercontent.com/8284999/62188313-8ccd9a00-b39e-11e9-9401-6592e2649067.jpg)
> 比如这个图片，原尺寸是655*54的，我通过宽度拉伸遍历发现只有在w=250的时候效果最好。。

试试看先将height缩放至32，width等比例缩放；再将width按照训练时的缩放比例进行缩放，具体如下：
>  w = int((image.size[0] / (image.size[1] * 1.0 / 32)) / (280 * 1.0 / 160))
