### ISSUE TITLE
加载预训练模型继续训练

### ISSUE THREAD

**Issue by 2snoopy88** [Sierkinhane/CRNN_Chinese_Characters_Rec#89]
预训练模型已经有很高精度,但是我再继续finetune的时候,为什么加载模型后预测训练开始准确率是0,不是应该是预训练的精度吗(我自己在模型上加了点东西,但是用前面几层的参数去加载,)

**Comment by Lanme** [comment]
你加载不会报错么？我是报错了：
UnpicklingError: invalid load key,
