### ISSUE TITLE
关于nclass的问题

### ISSUE THREAD

**Issue by liuyiyiyiyi** [Sierkinhane/crnn_chinese_characters_rec#9]
中文一个字符占3个字节，比如说我有5个字符，那我的nclass不就是3×5+1=16了，这样的话标签的种类不就有16个，而不是3+1=4

**Comment by Sierkinhane** [comment]
在解析的时候对应的是一个字符，并不是每个字节

**Comment by liuyiyiyiyi** [comment]
我遇到了一个问题，就是我用生成的样本进行训练，识别的准确率蛮好的，损失率也比较低，我用demo.py对自己从自然场景下抠出来的文本进行识别，

**Comment by liuyiyiyiyi** [comment]
我遇到了一个问题，就是我用生成的样本进行训练，识别的准确率蛮好的，损失率也比较低，我用demo.py对自己从自然场景下抠出来的文本进行测试，预测出来的标签序列包含了大量的我标签中没有的中文字符，我的猜想是由于中文字符占三个字节，但是nclass为字符种类*3+1，一个字节作为一个类，导致出现了我标签中不包含的字符

**Comment by liuyiyiyiyi** [comment]
我遇到了一个问题，就是我用生成的样本进行训练，识别的准确率蛮好的，损失率也比较低，我用demo.py对自己从自然场景下抠出来的文本进行测试，预测出来的标签序列包含了大量的我标签中没有的中文字符，我的猜想是由于中文字符占三个字节，但是nclass为字符种类*3+1，一个字节作为一个类，导致出现了我标签中不包含的字符

**Comment by Sierkinhane** [comment]
字符是根据你给定的alphabet中的字符预测，出现训练loss小，测试loss大的情况说明你过拟合了你的训练集，你给定的训练集和测试集并不来自同一分布，建议生成多样化且接近你测试集的训练样本，这样的泛化能力会更好。
