### ISSUE TITLE
test.py运行时间长

### ISSUE THREAD

**Issue by berylyellow** [Sierkinhane/crnn_chinese_characters_rec#90]
我有cuda，检测一张图片要0.2左右，我看作者只要0.01，是怎么回事？

**Comment by Sierkinhane** [comment]
什么配置？

**Comment by berylyellow** [comment]
@Sierkinhane RTX2060,cuda10.1, cudnn7.5, pytorch1.1.0a0+7e73783,笔记本

**Comment by Sierkinhane** [comment]
刚启动的时候是比较慢的，你循环测试一下速度

**Comment by berylyellow** [comment]
@Sierkinhane 我昨天用8张图for循环测试了下，也是0.2，不知道是不是cpu，gpu交互占的时间多
