### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by JingLiJJ** [Sierkinhane/crnn_chinese_characters_rec#91]
你好。我在训练时设定keep_ratio为True，固定高度32，等比缩放宽度。batch size为32。就会出现显卡内存不足的情况。请问你的代码可以实现多卡训练嘛？

**Comment by Sierkinhane** [comment]
你好，由于实验设备有限，我并没有尝试多卡训练

**Comment by JingLiJJ** [comment]
哦哦。谢谢~那我再问一下。你有尝试过不定长训练嘛？

**Comment by Sierkinhane** [comment]
应该是支持不定长训练的

**Comment by JingLiJJ** [comment]
我把keep_ratio设为True以后，就会显示CUDA OUT OF MEMORY的错误。如果我做不定长训练出了改这个参数还需要修改别的地方么？

**Comment by Sierkinhane** [comment]
GPU内存不足的话你得调小batch
Size ， 应该不是不用调其他参数

**Comment by JingLiJJ** [comment]
好哒。我试试。谢谢~
