### ISSUE TITLE
测试过程疑似图片risize的问题

### ISSUE THREAD

**Issue by monologue1107** [Sierkinhane/crnn_chinese_characters_rec#94]
在测试过程中，如果我使用原来测试集里的图片进行测试，效果非常好（训练准确率95%），但是我使用同样的label字符串但用不同的字体大小时，效果就表现得很糟糕。
如：
いけばいい」バンティングはあた
的识别效果就会变为
しゝけ(ごしNしゝ〵」ノ﹅ンン9ーィクンピ(女だと
由于训练的图片大小时统一的32*160，看起来似乎是图片risize的时候把比例给拉宽了，导致识别效果急剧下降。
可以问问有什么方法可以避免这种问题的出现？

**Comment by 2017TJM** [comment]
训练的时候就提高图片尺寸呀


------------------ 原始邮件 ------------------
发件人: "monologue1107"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 上午9:57
收件人: "Sierkinhane/crnn_chinese_characters_rec"<crnn_chinese_characters_rec@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Sierkinhane/crnn_chinese_characters_rec] 测试过程疑似图片risize的问题 (#94)




在测试过程中，如果我使用原来测试集里的图片进行测试，效果非常好（训练准确率95%），但是我使用同样的label字符串但用不同的字体大小时，效果就表现得很糟糕。
 如：
 いけばいい」バンティングはあた
 的识别效果就会变为
 しゝけ(ごしNしゝ〵」ノ﹅ンン9ーィクンピ(女だと
 由于训练的图片大小时统一的32*160，看起来似乎是图片risize的时候把比例给拉宽了，导致识别效果急剧下降。
 可以问问有什么方法可以避免这种问题的出现？

**Comment by zhangdaxia1** [comment]
请问您的问题解决了么
