### ISSUE TITLE
验证集准确率97%，用验证集数据测试结果只有74%

### ISSUE THREAD

**Issue by KouJiaWei** [Sierkinhane/crnn_chinese_characters_rec#97]
训练数据为30 X  ？ ，高度固定，宽度不定。训练数据10000，验证集数据2000，训练过程中验证集的准确率95%～99%，但是当我用验证集的数据做测试的时候准确率只有74% ，请问有什么办法可以解决吗？
下面是我的数据
![01](https://user-images.githubusercontent.com/48576827/57435210-c57c2e00-720a-11e9-92d0-a99295a7d023.png)

**Comment by winsonxxxx** [comment]
你好，这些数据是拿工具生成的吗

**Comment by mitsuily** [comment]
我也遇到了这个问题，请问楼主解决了么

**Comment by Lanme** [comment]
test.py预处理不太合理，图片输入只是在某个方向压缩了

**Comment by Lanme** [comment]
test.py预处理不太合理

**Comment by YukMingLaw** [comment]
我也遇到这种情况，后来把test.py里面的35,36,37行改为跟dataset_v2.py里同步就好了：
h, w = image.shape
image = cv2.resize(image, (0,0), fx = float(params.imgW / w), fy = float(params.imgH / h), interpolation=cv2.INTER_CUBIC)
image = (np.reshape(image, (params.imgH, params.imgW, 1))).transpose(2, 0, 1)
